Bisonai/orakl

contracts/src/v0.1/Prepayment.sol
contracts/test/v0.1/Prepayment.test.ts

Remove OZ AccesscontrolEnumerable library from prepayment.sol
Edit test cases
Fixes # https://github.com/Bisonai/orakl/issues/205

remove OZ AccessControl from prepayment

---

core/docker-compose.build.yaml
core/src/Dockerfile.dev

fixed dockerfile and add previous pushed version of image

---

core/src/cli/orakl-cli/src/index.ts

Orakl cli is not working at the existing Kubernetes.
Added code for customizable directory

hotfix for ORAKL_DIR settings ENV for docker image or Kubernetes

---

contracts/config/baobab/request-response.json
contracts/config/baobab/vrf.json
contracts/config/localhost/request-response.json
contracts/config/localhost/vrf.json
contracts/test/v0.1/RequestResponse.config.ts
contracts/test/v0.1/VRF.config.ts

This PR adjusts the maxGasLimit to 2500000 in VRF and RR configs

adjsut maxGasLimit to 2500000

---

contracts/scripts/v0.1/admin-aggregator/update-oracles.ts
core/aggregator/baobab/eth-usd.aggregator.json
core/src/errors.ts
core/src/listener/aggregator.ts
core/src/reporter/aggregator.ts
core/src/reporter/utils.ts
core/src/worker/aggregator.ts

This PR is collection few small changes:
* Use `wait(1)` in `sendTransaction` to speed up reporter job and include new fixed job faster to queue
* Set fixed `gasLimit` in aggregator reporter (gas amount depends on the order of submission which can change after gas estimation at node)
* Addresses stored in aggregator should be stored in lower case
* Added more debug logs

Lower number of confirmations & misc

---

.github/workflows/request-response.integration.test.yaml
contracts/scripts/v0.1/request-response/integration/read-data.ts
contracts/scripts/v0.1/request-response/integration/request-data.ts

This Pr added github actions for RR integration test.
Fixes # https://github.com/Bisonai/orakl/issues/316

integration test for request response

---

contracts/config/baobab/request-response.json
contracts/config/baobab/vrf.json
contracts/config/localhost/request-response.json
contracts/config/localhost/vrf.json
contracts/deploy/1-RequestResponseCoordinator.ts
contracts/deploy/2-VRFCoordinator.ts
contracts/scripts/v0.1/types.ts

update deployment scripts for VFR and RR, including set minBalance
Fixes # https://github.com/Bisonai/orakl/issues/308

set config minBalance in deployment scripts(vrf,request-response)

---

cli/docker-compose.build.yaml
cli/src/Dockerfile

add dockerFile for orakl-cli and docker-compose for building.

add docker build for orakl-cli

---

.github/workflows/delegator.test+build.yaml
delegator/README.md
delegator/src/sign/sign.service.spec.ts
delegator/src/sign/sign.service.ts

This PR is for setup Hithub actions to check `test` & `build` for `Delegator` while on `push`.
https://github.com/Bisonai/orakl/issues/378
https://github.com/Bisonai/orakl/issues/377

Setup github actions for delegator

---

.github/workflows/request-response.integration.test.yaml
.github/workflows/vrf.integration.test.yaml

This PR modifies Github actions for integration test, grab the private from .env instead of sqlite database
Fixes https://github.com/Bisonai/orakl/issues/368

Update integration test with hardhat public and private keys for reporter

---

cli/package.json

Deploy `@bisonai/orakl-cli` v0.4.0 including migrations from SQLite to Orakl Network API & PostgreSQL state.

Deploy `@bisonai/orakl-cli` v0.4.0

---

api/docker-compose.build.yaml
api/package.json
api/prisma/schema.prisma
api/src/Dockerfile

Dockerize and fixed prisma setting

---

core/src/worker/api.ts
fetcher/docker-compose.build.yaml
fetcher/src/Dockerfile

fixed worker api basic call address

---

core/src/worker/aggregator.ts

This PR is solving deadlock issue in a reporter job when aggregator with a single reporter fails.
Remove reporter job on failure.

Remove aggregator reporter job on failure

---

.github/workflows/api.image+upload.yaml
.github/workflows/cli.image+upload.yaml
.github/workflows/core.image+upload.yaml
.github/workflows/fetcher.image+upload.yaml
api/package.json

Image tage include package.json version info

Image tag with version

---

api/src/adapter/adapter.service.ts

Throw HttpException bad request error with description as intent
Fixes #492

Fix 500-server-error (#492)

---

core/src/worker/request-response.ts

This PR fixes a Request-Response issue which kills worker when request cannot be correctly parsed for whatever reason.

[bugfix] Reraise error for BullMQ to know that job failed

---

.github/workflows/api.image+upload.yaml
.github/workflows/cli.image+upload.yaml
.github/workflows/core.image+upload.yaml
.github/workflows/delegator.image+upload.yaml
.github/workflows/fetcher.image+upload.yaml
delegator/docker-compose.build.yaml
delegator/package.json
delegator/prisma/schema.prisma
delegator/src/Dockerfile

This PR is building image and upload to ECR for delegator

Delegator git actions building image

---

.github/workflows/contracts.publish.yaml
.github/workflows/contracts.test.yaml
contracts/hardhat.config.cjs
contracts/package.json
contracts/scripts/v0.1/utils.cjs
contracts/src/v0.1/Prepayment.sol
contracts/yarn.lock

This PR includes a missing changes from https://github.com/Bisonai/orakl/pull/531.
* removing commented code
* upgrading `@bisonai/orakl-vrf` in `@bisonai/orakl-contracts`
* fixing issue in `Prepayment.isValid` (not sure why it has not broke before 😢 )

Add missing changes from #531

---

contracts/test/v0.1/Median.test.cjs

This PR includes updated Median test for values defined as `ethers.BigNumber`.

Improve test for Median with BigNumber

---

contracts/hardhat.config.cjs
contracts/src/v0.1/Account.sol
contracts/src/v0.1/Prepayment.sol
contracts/src/v0.1/RequestResponseConsumerFulfill.sol
contracts/src/v0.1/RequestResponseCoordinator.sol
contracts/src/v0.1/VRFCoordinator.sol
contracts/src/v0.1/interfaces/IPrepayment.sol
contracts/src/v0.1/mocks/RequestResponseConsumerMock.sol
contracts/test/v0.1/Median.test.cjs
contracts/test/v0.1/Prepayment.test.cjs
contracts/test/v0.1/RequestResponse.config.cjs
contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
contracts/test/v0.1/State.utils.cjs
contracts/test/v0.1/VRF.config.cjs
contracts/test/v0.1/VRF.test.cjs
contracts/test/v0.1/utils.cjs

This PR is a review for https://github.com/Bisonai/orakl/pull/524. It fixes some of the problems, but the others are just highlighted and will be fixed in another PR.

Review for #495

---

contracts/src/v0.1/RequestResponseCoordinator.sol
contracts/src/v0.1/VRFCoordinator.sol
contracts/src/v0.1/interfaces/IRequestResponseCoordinator.sol
contracts/src/v0.1/interfaces/IVRFCoordinator.sol
contracts/src/v0.1/mocks/RequestResponseConsumerMock.sol
contracts/src/v0.1/mocks/VRFConsumerMock.sol
contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
contracts/test/v0.1/VRF.test.cjs

This PR includes an implementation of request cancelation in VRF and slight update to request in Request-Response.

Cancel request

---

contracts/src/v0.1/Account.sol
contracts/src/v0.1/Prepayment.sol
contracts/src/v0.1/RequestResponseCoordinator.sol
contracts/src/v0.1/VRFCoordinator.sol

This PR fixes some warnings from Slither: Uninitialized local variables

fixed variable never initialized warning from slither

---

contracts/src/v0.1/Prepayment.sol

This PR fixes some Reentrancy warnings from slither.

fixed reentrancy warning from silther in prepayment

---

api/package.json
delegator/package.json

CICD : prisma database migration in production

---

contracts/src/v0.1/Prepayment.sol
contracts/src/v0.1/VRFCoordinator.sol
contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
contracts/test/v0.1/VRFCoordinator.test.cjs

This PR includes tests for increasing nonce of [regular] accounts in coordinators (`VRFCoordinator`, `RequestResponseCoordinator`). The nonce is increased indirectly inside of Account contract (EOA -> Consumer Request -> Coordinator Request -> Prepayment -> Account).

Increase `nonce` test

---

contracts/src/v0.1/RequestResponseConsumerBase.sol
contracts/src/v0.1/RequestResponseConsumerFulfill.sol
contracts/src/v0.1/RequestResponseCoordinator.sol
contracts/src/v0.1/interfaces/IRequestResponseCoordinatorBase.sol
contracts/src/v0.1/mocks/ConversionTest.sol
contracts/src/v0.1/mocks/RequestResponseConsumerMock.sol
contracts/test/v0.1/Conversion.test.cjs
contracts/test/v0.1/RequestResponseConsumerContract.test.cjs

This PR fixes issue described at https://github.com/Bisonai/orakl/issues/569.

Update data type conversion and change `uint256` job to `uint128` job

---

contracts/src/v0.1/mocks/RequestResponseConsumerRevertFulfillmentMock.sol
contracts/src/v0.1/mocks/VRFConsumerRevertFulfillmentMock.sol
contracts/test/v0.1/CoordinatorRevertFulfillment.test.cjs
contracts/test/v0.1/Prepayment.utils.cjs
contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
contracts/test/v0.1/RequestResponseCoordinator.utils.cjs
contracts/test/v0.1/VRFCoordinator.test.cjs
contracts/test/v0.1/VRFCoordinator.utils.cjs
contracts/test/v0.1/utils.cjs

This PR tests accomplishment of reverted fulfillment submission and its payment.

Test VRFCoordinator & RequestResponseCoordinator reversion of fulfillment

---

contracts/test/v0.1/CoordinatorBase.test.cjs
contracts/test/v0.1/CoordinatorBase.utils.cjs
contracts/test/v0.1/Prepayment.utils.cjs
contracts/test/v0.1/VRFConsumerMock.utils.cjs
contracts/test/v0.1/VRFCoordinator.test.cjs
contracts/test/v0.1/VRFCoordinator.utils.cjs

This PR defines tests for canceling invalid VRF request and cancelation of request with sender that did not initiate the request.

Test for canceling invalid requests or canceling request with sender that did not initiate the request

---

contracts/src/v0.1/mocks/CoordinatorBaseMock.sol
contracts/test/v0.1/CoordinatorBaseMock.test.cjs

This PR defines a test for fee tier calculation. The smallest non-zero price for service is one millionth of $KLAY (1 $KLAY / 1,000,000).

Fee tier test

---

contracts/src/v0.1/Account.sol
contracts/src/v0.1/Prepayment.sol
contracts/src/v0.1/mocks/CoordinatorBaseMock.sol
contracts/test/v0.1/Account.test.cjs
contracts/test/v0.1/CoordinatorBase.test.cjs
contracts/test/v0.1/CoordinatorRevertFulfillment.test.cjs
contracts/test/v0.1/Prepayment.test.cjs
contracts/test/v0.1/Prepayment.utils.cjs
contracts/test/v0.1/VRFCoordinator.test.cjs
contracts/test/v0.1/VRFCoordinator.utils.cjs

This PR focuses on Account and Prepayment tests.

Account & Prepayment tests

---

contracts/src/v0.1/RequestResponseConsumerBase.sol
contracts/src/v0.1/RequestResponseCoordinator.sol
contracts/src/v0.1/interfaces/IRequestResponseCoordinatorBase.sol
contracts/test/v0.1/CoordinatorRevertFulfillment.test.cjs
contracts/test/v0.1/RequestResponseConsumerContract.test.cjs

This PR fixes the following smart contract security issues:
* `RequestResponseCoordinator.sol` - Unverify `jobId` when oracle submits `fulfillDataRequestData`
* `RequestResponseCoordinator.sol` - Unverify `isDirectPayment` value when oracle submits
`fulfillDataRequestData`
* `RequestResponseCoordinator.sol` - Reentrancy in `fulfillDataRequestUint128`
* `RequestResponseConsumerBase.sol` - Incorrectly initialize a function selector that maps to a `jobId`

Reflect audit findings

---

admin/src/components/Common/TabContextProvider/index.tsx
admin/src/components/Common/TabList/index.tsx
admin/src/components/Common/TabList/styled.ts
admin/src/components/Common/TabPanel/index.tsx
admin/src/components/Common/TabPanel/styled.ts
admin/src/components/Template/BullMonitor/DetailHeader/index.tsx
admin/src/components/Template/BullMonitor/DetailHeader/styled.ts
admin/src/components/Template/BullMonitor/DetailTab/index.tsx
admin/src/components/Template/BullMonitor/DetailTable/index.tsx
admin/src/components/Template/BullMonitor/detail.tsx
admin/src/hook/useTabContext.ts
admin/src/utils/api.ts
admin/src/utils/types.ts

1. Connect data to the detail table component.
2. Implement routing for the component.
3. Add a status tab.
//TODO 
each table is receiving a large amount of data that I'm not familiar with
so discuss with jo where each data should be displayed.

Feat detail page tab component

---

admin/src/components/Common/BasicButton/index.tsx
admin/src/components/Common/Header/styled.ts
admin/src/components/Common/NavigationDropdown/styled.ts
admin/src/components/Common/TabList/styled.ts
admin/src/components/Common/TabPanel/styled.ts
admin/src/components/Template/BullMonitor/DetailHeader/index.tsx
admin/src/components/Template/BullMonitor/DetailHeader/styled.ts
admin/src/components/Template/BullMonitor/DetailTable/index.tsx
admin/src/components/Template/BullMonitor/DetailTable/styled.ts
admin/src/components/Template/BullMonitor/MonitorTable/index.tsx
admin/src/components/Template/BullMonitor/MonitorTable/styled.ts
admin/src/components/Template/BullMonitor/TableHeader/index.tsx
admin/src/components/Template/BullMonitor/TableHeader/styled.ts
admin/src/components/Template/BullMonitor/detail.tsx
admin/src/theme/globals.css
admin/src/theme/theme.tsx
admin/src/utils/api.ts
admin/src/utils/index.ts

Feat add detail table and pagination

---

admin/.env
admin/.gitignore
admin/package.json
admin/src/app/layout.tsx
admin/src/components/Common/Toast/index.tsx
admin/src/components/Common/Toast/styled.ts
admin/src/components/Common/ToastProvider/index.tsx
admin/src/components/Template/BullMonitor/AggregatorTable/index.tsx
admin/src/components/Template/BullMonitor/DetailTable/index.tsx
admin/src/components/Template/BullMonitor/DetailTable/styled.ts
admin/src/components/Template/BullMonitor/RequestResponseTable/index.tsx
admin/src/components/Template/BullMonitor/VrfTable/index.tsx
admin/src/hook/useToastContext.ts
admin/src/theme/theme.tsx
admin/src/utils/api.ts
admin/src/utils/types.ts
admin/yarn.lock

hide endpoint 
refetch button and toast 

enhance UI/UX

---

admin/src/app/layout.tsx
admin/src/components/Common/NavigationDropdown/styled.ts
admin/src/components/Common/TabList/index.tsx
admin/src/components/Template/BullMonitor/AggregatorTable/index.tsx
admin/src/components/Template/BullMonitor/DetailHeader/index.tsx
admin/src/components/Template/BullMonitor/DetailTable/index.tsx
admin/src/components/Template/BullMonitor/MonitorTable/index.tsx
admin/src/components/Template/BullMonitor/MonitorTable/styled.ts
admin/src/components/Template/BullMonitor/RequestResponseTable/index.tsx
admin/src/components/Template/BullMonitor/TableHeader/index.tsx
admin/src/components/Template/BullMonitor/VrfTable/index.tsx
admin/src/components/Template/BullMonitor/detail.tsx
admin/src/components/Template/BullMonitor/main.tsx
admin/src/utils/api.ts
admin/src/utils/types.ts
admin/yarn.lock

fix layout 
data fetch logic
connect queueInfo data
logs display method

Feat connect info data

---

admin/src/app/configuration/[configType]/page.tsx
admin/src/app/configuration/layout.tsx
admin/src/app/configuration/page.tsx
admin/src/components/Common/BasicButton/index.tsx
admin/src/components/Common/DimmedPopup/index.tsx
admin/src/components/Common/DimmedPopup/styled.ts
admin/src/components/Common/DimmedPopupProvider/index.tsx
admin/src/components/Common/NavigationDropdown/index.tsx
admin/src/components/Template/Configuration/Chain/index.tsx
admin/src/components/Template/Configuration/Chain/styled.ts
admin/src/components/Template/Configuration/ConfigurationTable/TwoColumnTable/index.tsx
admin/src/components/Template/Configuration/ConfigurationTable/TwoColumnTable/styled.ts
admin/src/components/Template/Configuration/Service/index.tsx
admin/src/components/Template/Configuration/detail.tsx
admin/src/components/Template/Configuration/index.tsx
admin/src/hook/useDimmedPopupContext.ts
admin/src/utils/api.ts
admin/src/utils/route.ts
admin/src/utils/types.ts

routing settings, dimmed popup provider, and service and chain components.
//TODO
Currently, it is dummy data. Once the CORS error is resolved, Will connect Data.

Feat configuration related component

---

delegator/README.md
delegator/prisma/migrations/20230607023009_delegator_fix_function_name_uniquness/migration.sql
delegator/prisma/schema.prisma
delegator/src/sign/sign.service.spec.ts

Changes:
- Fix delegator function name unique constrain, by making it unique together with `function name` and `contractId`

fix unique constrains on delegator

---

contracts/package.json

Publish new contract npm package. 

bump-up contract version from 0.6.0 to 1.0.0

---

core/package.json
core/src/types.ts
core/src/worker/request-response.utils.ts
core/yarn.lock

This PR is for increase `orakl-contract` package version from `orakl-core` to make it compatible with latest package. 

increase `orakl-contract` package version to 1.0.0

---

admin/package.json
admin/src/app/layout.tsx
admin/src/components/Common/NavigationDropdown/index.tsx
admin/src/components/Common/NavigationDropdown/styled.ts
admin/src/components/Common/ScrollButton/index.tsx
admin/src/components/Common/ScrollButton/styled.ts
admin/src/components/Template/BullMonitor/DetailTable/index.tsx
admin/src/components/Template/BullMonitor/MonitorTable/index.tsx
admin/yarn.lock

The issue where the queue names were changing order upon refresh has been resolved.
Modify the dropdown header to navigate to the selected page upon clicking, refactor the code, and create a scroll-to-top button.

Fix admin QA issues

---

admin/src/components/Template/BullMonitor/TableHeader/index.tsx
admin/src/components/Template/Configuration/Chain/index.tsx
admin/src/components/Template/Configuration/ConfigurationTable/TwoColumnTable/index.tsx
admin/src/components/Template/Configuration/Service/index.tsx
admin/src/utils/api.ts

Removed the dummy data and connected it with real data.
Can perform additions and deletions from the admin page

Feat connecting api to the services and chain in the admin

---

contracts/test/v0.1/Aggregator.test.cjs

This test shows that `oracleRoundState` recommends the right `roundId` to report on at the time of the call. If there is second reporter that submits in the meantime, before the first reporter finishes submission, the recommendation can become outdated.
To limit the times when submission `roundId` becomes outdates, we have to synchronize data feed workers through listeners. We can additionally test whether the submission `roundId` is still appropriate right before the submission, however it would not be necessary if data feed workers synchronize correctly.

Aggregator suggests to skip rounds

---

fetcher/src/job/job.processor.ts

Removes an unnecessary log in Orakl Network Fetcher.

Remove decimals log in Fetcher

---

delegator/prisma/migrations/20230627015728_add_transactions_timestamp/migration.sql
delegator/prisma/migrations/20230627070124_add_transactions_timestamp/migration.sql
delegator/prisma/schema.prisma
delegator/src/sign/dto/sign.dto.ts
delegator/src/sign/sign.service.spec.ts
delegator/src/sign/sign.service.ts

Changes:
- add `timestamp` to `delegator transaction` table
- resolve miss assigning of `reporterId` and `functionId` 
- improve `orakl-delegator` test

add delegator transaction timestamp

---

api/prisma/migrations/20230703061810_error_alter_error_code_type/migration.sql
api/prisma/schema.prisma
api/src/error/dto/error.dto.ts
api/src/error/error.service.spec.ts
core/src/types.ts
core/src/worker/request-response.ts

This PR is ready to review and merge. Main change on this PR is to fix `code` type in orakl-api `error table`. Previously `code` is defined as number, but it is not always the case.  

fix error code data type

---

admin/package.json
admin/src/components/Common/ScrollButton/index.tsx
admin/src/components/Common/ScrollButton/styled.ts
admin/src/components/Template/Home/Login/index.tsx
admin/src/components/Template/Home/Login/styled.ts
admin/src/components/Template/Home/index.tsx
admin/src/lib/authenticatedAxios.ts
admin/src/lib/cookies.ts
admin/src/utils/api.ts
admin/yarn.lock

I created a login system so that user can't access the data if user didn't receive the token.

Feat admin login system

---

delegator/src/app.settings.ts
delegator/src/sign/sign.service.spec.ts
delegator/src/sign/sign.service.ts

Changes: 
- Add check if wallet for fee payer is initialized. 
- Enable `Cors` for delegators

Fix delegator initialization

---

contracts/src/v0.1/L2Registry.sol
contracts/src/v0.1/L2endpoint.sol
contracts/src/v0.1/Registry.sol
contracts/src/v0.1/interfaces/IL2Aggregator.sol
contracts/test/v0.1/L2Endpoint.test.cjs
contracts/test/v0.1/Registry.test.cjs
contracts/test/v0.1/Registry.utils.cjs

+ Registry contract on L1
+ Enpoint contract on L2
+ Basic test cases
- [ x] New feature (non-breaking change which adds functionality)
- [ x] This change requires a documentation update
- [x ] I have performed a self-review of my code.
- [x ] If it is a core feature, I have added thorough tests.
- [x ] Should publish npm package

747 registry contract for l2

---

admin/src/components/Common/BasicButton/index.tsx
admin/src/components/Common/NavigationDropdown/index.tsx
admin/src/components/Common/TabList/index.tsx
admin/src/components/Common/TabList/styled.ts
admin/src/components/Template/BullMonitor/DetailTab/index.tsx
admin/src/components/Template/BullMonitor/DetailTable/styled.ts
admin/src/utils/route.ts
admin/src/utils/types.ts

Fixed Nav dropdown issue
Added the feature to display the number of data on the right side of the list tab.

Feat improve admin UI/UX

---

monitor/Dockerfile

[HOTFIX] Add migrations into the dockerfile for deploy monitor pod
fixes #762

[HOTFIX] Add migrations into the dockerfile

---

contracts/src/v0.1/Registry.sol
contracts/test/v0.1/Registry.test.cjs
contracts/test/v0.1/Registry.utils.cjs

Changes:
- Remove startRound on Registry contract

remove startRound from Registry

---

monitor/src/accounts/accounts.service.ts

Fix wrong condition
Fixes #764 

Fix wrong condition

---

contracts/deploy/Registry/Registry.cjs
contracts/package.json
contracts/scripts/v0.1/registry/proposeChain.cjs

This PR is to increase package version of Orakl Contract to include `Registry` and `L2endpoint` contracts. Additions to that, I also add Registry deployment, and confirmChain scripts. 

Increase orakl contract package version to include Registry, and L2Endpoint

---

admin/src/components/Template/Configuration/Adapter/index.tsx
admin/src/components/Template/Configuration/Aggregator/index.tsx
admin/src/components/Template/Configuration/ConfigurationTable/DataTable/index.tsx
admin/src/components/Template/Configuration/ConfigurationTable/TwoColumnTable/index.tsx
admin/src/components/Template/Configuration/Service/index.tsx
admin/src/utils/types.ts

Fix build error
Fix components

Fix admin qa issues

---

contracts/src/v0.1/L1Endpoint.sol
contracts/test/v0.1/L1Endpoint.test.cjs

This PR implements L1endpoint contract for VRF request from L2

L1 endpoint contract for vrf request from L2

---

contracts/src/v0.1/L1Endpoint.sol
contracts/src/v0.1/Registry.sol
contracts/src/v0.1/interfaces/IL1Endpoint.sol
contracts/src/v0.1/interfaces/IRegistry.sol
contracts/test/v0.1/L1Endpoint.test.cjs
contracts/test/v0.1/Registry.test.cjs
contracts/test/v0.1/Registry.utils.cjs

This PR implements Registry and L1 endpoint for L2 VRF consumers

777 registry for vrf service on l2

---

monitor/src/accounts/accounts.repository.ts
monitor/src/accounts/accounts.service.ts
monitor/src/accounts/dto/balance.dto.ts
monitor/src/app.module.ts
monitor/src/app.service.ts

Remove balance check from `monitor-api`
Fixes #794 

Remove balance check from monitor-api

---

core/src/settings.ts

increased to 650k

---

LICENSE

This PR is to put Licence on Orakl Network main  github directory. 

put `LICENCE` on orakl main directory

---

contracts/src/v0.1/L2endpoint.sol
contracts/test/v0.1/L2Endpoint.test.cjs

added more checks

---

core/src/reporter/utils.ts

This PR is to fix the issue with reporter call() methods input params. 

Fix reporters call method input params

---

core/src/settings.ts

VRF verification process sometimes spikes and requires more gas than we expected.

Make `VRF_FULFILL_GAS_MINIMUM` 1M

---

contracts/src/v0.1/VRFCoordinator.sol

VRF price computation was wrong. It should not depend on number of requested words.

VRF allows only 1 submission

---

core/src/reporter/utils.ts

This PR prints a single debug response from delegator request called from reporter.

Print response from Orakl Network Delegator

---

.github/workflows/delegator.image+upload.yaml

Remove duplicated on push trigger

---

contracts/src/v0.1/L2endpoint.sol
contracts/src/v0.1/interfaces/IL2Endpoint.sol
contracts/src/v0.1/mocks/L2VRFConsumerMock.sol
contracts/test/v0.1/non-vrf/L2Endpoint.test.cjs
contracts/test/v0.1/vrf/L2VRFConsumerMock.cjs

Modify L2Endpoint contract for VRF/RR

---

api/src/adapter/adapter.controller.ts
api/src/aggregator/aggregator.controller.ts
api/src/feed/feed.controller.ts
api/src/listener/listener.controller.ts
api/src/proxy/proxy.controller.ts
api/src/reporter/reporter.controller.ts

return list in ascending order to find recently added items easily

return cli list in id ascending order

---

.github/workflows/core.image+upload.yaml

Temporary solution
https://github.com/Bisonai/orakl/issues/952

Copy fetcher auxiliary files

---

.github/workflows/core.image+upload.yaml

`workflow_dispatch` core

---

.github/workflows/core.image+upload.yaml

Copy POR files

---

core/package.json
core/yarn.lock

Increased `orakl-contract` package version to match the package version. 

increase `orakl-contract` for core

---

api/src/aggregate/aggregate.service.ts

This PR replaces an autogenerated Prisma query with faster one for fetching the latest data aggregate given `aggregatorHash`.
The aggregated data are stored in `aggregates` table with one single column index on `aggregate_id` and multi-column index on `aggregator_id,"timestamp"DESC`. Since the goal of query is to fetch the *latest* aggregates given *aggregator hash*, we decided to optimize query rather than updating indexes.
Below you can see `AS-IS` and `TO-BE` versions of queries on table `data_ag_2023_11_04` (1.14M rows) seeking the latest aggregate value for `0xe87c49db104f27110170d10b10505220f0436fcdeb98754c076848903943fa89` aggregator hash. Five interleaving execution of queries have been conducted. Execution times for respective queries are shown below. The improvement in execution …

Use faster query to fetch the latest aggregate

---

api/prisma/migrations/20231116075406_add_proxy_location/migration.sql
api/prisma/migrations/20231116080058_set_proxy_location_optional/migration.sql
api/prisma/migrations/20231122081517_proxy_add_location/migration.sql

previously there were 2 migration file which is adding location column with not null condition and then removing not null condition. this fixes the unnecessary process

Fix prisma migration file

---

api/src/app.module.ts
fetcher/src/job/job.utils.ts
fetcher/src/tools/run-adapter.ts

minor fixes found from `yarn lint` command

Minor fixes based on linter command

---

core/src/worker/data-feed.ts

Adds state check from aggregatorJob to prevent `AggregatorNotFoundInState` Error
For more detail for how this PR has been made, please check the issue https://github.com/Bisonai/orakl/issues/940
this issue blocks following issue
https://github.com/Bisonai/orakl/issues/938

Add state check from aggregator job & submit heartbeat job

---

contracts/src/v0.1/L2EndpointBase.sol
contracts/src/v0.1/L2EndpointRequestResponse.sol
contracts/src/v0.1/L2endpoint.sol
contracts/src/v0.1/interfaces/IL2Endpoint.sol
contracts/src/v0.1/mocks/L2RequestResponseConsumerMock.sol
contracts/test/v0.1/non-vrf/L2RequestResponseConsumer.test.cjs

This PR implements L2enpoint and L2 consumer mock for RR on L2

Added L2 RR request and fulfill functions + testcase

---

api/src/proxy/proxy.service.spec.ts

test code modification to add missing cleanup code

Add missing cleanup code

---

contracts/migration/cypress/Aggregator/20231128200638_BORA-KRW_register.json
contracts/migration/cypress/Aggregator/20231128200638_CHF-USD_register.json
contracts/migration/cypress/Aggregator/20231128200638_EUR-USD_register.json
contracts/migration/cypress/Aggregator/20231128200638_GBP-USD_register.json
contracts/migration/cypress/Aggregator/20231128200638_JOY-USDT_register.json
contracts/migration/cypress/Aggregator/20231128200638_JPY-USD_register.json
contracts/migration/cypress/Aggregator/20231128200638_KRW-USD_register.json
contracts/migration/cypress/Aggregator/20231128200638_KSP-KRW_register.json
contracts/migration/cypress/Aggregator/20231128200638_MBX-KRW_register.json
contracts/migration/cypress/Aggregator/20231128200638_WEMIX-USDT_register.json

This PR includes migration scripts to register KF's reporter to `Aggregator` contracts.

Register 10 KF's data feed aggregators

---

.github/workflows/contracts.test.yaml
.github/workflows/vrf.contracts.test.yaml
contracts/package.json
contracts/yarn.lock

this PR rollbacks github yaml node version and supports `contracts` package to use node version `18.12`
enable yarn commands from `contracts` package with node version `18.12`

Rollback with node version compatibility

---

contracts/migration/localhost/POR/20230831181923_deploy.json

PR to include step written in document

Add reporter for por local migraion

---

.github/workflows/cli.build+publish.yaml
.github/workflows/contracts.test.yaml
.github/workflows/core.test+build.yaml
cli/package.json
contracts/package.json
core/package.json
dockerfiles/orakl-cli.Dockerfile
dockerfiles/orakl-core.Dockerfile

sets up `prebuild` hook in package.json, automatically runs hook whenever build command is called
building local dependency workspace is now included in `prebuild` hook, removing related steps from docker images
* for contracts, compiling contracts is included in prebuild hook

Set prebuild hook

---

dockerfiles/orakl-core.Dockerfile

Fixes dockerImage folder copy path

Fix folder directory to COPY from Dockerfile

---

.gitignore
contracts/README.md
contracts/package.json
contracts/scripts/v0.1/admin-aggregator/dataFeedSample.json
contracts/scripts/v0.1/admin-aggregator/generate-aggregator-deployments.cjs

- adds command line argument for the script, `--pairs` and `--chain`
- generates `bulk.json` which can be used for bulk datafeed insert, removal, activation and deactivation

Update script to generate bulk json file

---

cli/package.json
cli/src/datafeed.ts
cli/test/datafeed.test.ts

Adds cli functionality to bulk remove datafeeds, test codes are included

Add bulk removal functionality

---

cli/src/cli-types.ts
cli/src/datafeed.ts
cli/src/settings.ts

Adds bulk activate and deactivate functionality, test codes aren't included. 
Since running and hosting listener, reporter and worker for test environment is another big challenge, it's better be done from other task

Bulk activate and deactivate

---

api/src/aggregate/aggregate.controller.ts

Adds path for previous version compatibility.

Allow previous path to deploy separately

---

api/src/aggregate/aggregate.controller.ts

Fix api route

---

api/src/aggregate/aggregate.controller.ts

adds comment for getting latest aggregates

Add comment for path to be deprecated

---

.github/workflows/cli.test.yaml
cli/package.json
contracts/package.json
core/package.json
fetcher/package.json

Remove unnecessary path specifier for yarn cwd option
- Also adds missing redis container for api server from cli test

Remove unnecessary directory specifier

---

util/package.json
yarn.lock

- `index.js` will be referenced from esm
- `index.cjs` will be referenced from commonjs
- Creates `index.cjs` file using rollup library.  
- https://stackoverflow.com/a/75348391
- https://nodejs.org/api/packages.html#conditional-exports

Fix import error from fetcher due to CommonJs compatibility

---

fetcher/src/job/job.controller.ts

will research more about obliterate function after fixing fetcher

Comment out obliterate for fetcher

---

core/src/errors.ts
core/src/listener/data-feed.ts
core/src/reporter/data-feed.ts
core/src/reporter/factory.ts
core/src/reporter/reporter.ts
core/src/reporter/types.ts
core/src/types.ts
core/src/utils.ts
core/src/worker/data-feed.ts
core/test/utils.ts

This reverts commit cf19e5e18dd65d5674ea7eb08e212565ad3c97ce.
only includes obliterate function

Hotfix to remove only roundId optimization codes

---

cli/src/cli-types.ts
cli/src/datafeed.ts

Read source given from bulk file also as file path

Read also from file path on bulk commands

---

contracts/package.json

Update package version to deploy new contracts package, and refer from consumer repository. (IAggregatorRouter.sol not yet included)

Update package version

---

core/src/reporter/reporter.ts
core/test/caver-js.test.ts

When transaction delegated fee breaks for any kind of reason, don't use it again in the next loop.

Delegated fee fallback

---

inspector/README.md
inspector/hardhat.config.ts
inspector/scripts/requestAndRead.ts

* Add more logs to Inspector's `requestAndRead.ts` script
* Update Inspector README
* Change Inspector's public JSON-RPC to use Allthatnode

Add more logs to Inspector

---

core/src/por/api.ts
core/src/types.ts
core/src/worker/request-response.ts
fetcher/src/job/job.processor.ts

modify datetime string format which is sent as request body on api call

Update datetime insert format

---

monitor/scripts/README.md
monitor/scripts/ecr-check.sh

Check on ECR + helm image check. It should help with daily check and avoid accidentally deleting currently used images from repository. It will need checks for VRF, RR, and Aggregator image tags, but it is good first step.
```
❯❯❯ ./ecr-check.sh
orakl-core: count FAIL (7 tags)
(cypress) orakl-core: vrf FAIL (v0.3.1.20231103.0653.19ca105)
(cypress) orakl-core: request-response FAIL (v0.3.1.20231016.1000.749dac8)
(cypress) orakl-core: aggregator OK (v0.5.1.20240122.0131.44014e7)
(baobab) orakl-core: vrf OK (v0.5.1.20240111.1440.dacb2ef)
(baobab) orakl-core: vrf OK (v0.5.1.20240111.1440.dacb2ef)
(baobab) orakl-core: vrf OK (v0.5.1.20240111.1440.dacb2ef)
(baobab) orakl-core: request-response OK (v0.5.1.20240111.1440.dacb2ef)
(baobab) orakl-core: request-response OK …
```

ECR + helm image check

---

contracts/src/v0.1/BatchSubmission.sol
contracts/src/v0.1/interfaces/IAggregatorSubmit.sol
contracts/test/v0.1/non-vrf/BatchSubmission.test.cjs

Add batchSubmission feature for datafeeds

Created batch submission smc + test case

---

inspector/README.md
inspector/hardhat.config.ts
inspector/inspector-task.ts
inspector/scripts/requestAndRead.ts
inspector/scripts/utils.ts

```shell
npx hardhat inspect --network baobab --service vrf
npx hardhat inspect --network baobab --service rr
npx hardhat inspect --network baobab
npx hardhat inspect --network cypress --service vrf
npx hardhat inspect --network cypress --service rr
npx hardhat inspect --network cypress
```

Separate inspector command based on service

---

inspector/README.md

Got burnt on this during daily checklist process.

Fix Inspector Command Typo

---

fetcher-v2/utils/libp2p.go

Concurrent peer search for faster discovery

(OraklNode) Concurrent search for peer discovery

---

fetcher-v2/README.md
fetcher-v2/utils/fetcher-node.go
fetcher-v2/utils/libp2p.go

README.md for offchain aggregator poc
Please leave any comments for missing contents

(OraklNode) Add README.md

---

dockerfiles/orakl-core.Dockerfile

Fix updated contract folder path
https://github.com/Bisonai/orakl/actions/runs/7741369249/job/21108260335

(Core) Update Dockerfile

---

core/src/reporter/state.ts

Adds warning for invalid reporter addresses

(Core) Add logger.warn for invalid reporter address

---

cli/src/delegator.ts
cli/src/listener.ts
cli/src/reporter.ts

`yarn cli reporter list`
`yarn cli listener list`
`yarn cli delegator reporterList`
now will be printing out datafeed pair name if possible

(CLI) Update cli list functions

---

fetcher-v2/main.go
fetcher-v2/utils/elector-node.go

Selects node among peers through round-robin method (take turns)

(OraklNode) Basic node selection

---

.github/workflows/vrf.integration.test.yaml

VRF integration test triggered by issue comments now triggered on branch push

(Contract) Update vrf integration test trigger

---

cli/package.json

last build was skipped since version update was missing
https://github.com/Bisonai/orakl/actions/runs/7753017467/job/21143550255

(CLI) Fix skipped publish without version update

---

.github/workflows/cli.test.yaml

This pr will contain all related updates where part of the code references node js api
Please leave a comment if I'm missing any side effects

GO-API migration side effect preperation

---

go-api/aggregator/controller.go

Chain field is not used for hash computation

(API) Except `Chain` field validation on aggregator hash request

---

fetcher-v2/main.go
fetcher-v2/node/raft-node.go

Implements raft without log replication
you can check out how leader is selected, leader resign when there are multiple leaders, how leader performs actions, how other leader is elected on shutdown and so on.
try to add or shut down console on your will
```bash
go run main.go -p="3001"
go run main.go -p="3002"
```

(OraklNode) Basic Raft Implementation

---

.github/CODEOWNERS

Previously, repository ownership was split among multiple contributors. This PR makes `Bisonai/orakl-team` a single owner of the whole repository.

Keep only orakl-team as codeowner

---

docker-compose.local-data-feed.yaml
dockerfiles/local-data-feed/contracts.Dockerfile

updates contracts path 
`contracts` -> `contracts-v0.1`

Update contracts path for local docker compose

---

docker-compose.local-data-feed.yaml
dockerfiles/local-data-feed/contracts.Dockerfile
dockerfiles/local-data-feed/scripts/deploy-contracts.sh

Local docker-compose had an issue with contract deployment script after the contracts path have been updated. checked it working after this update

Fix local docker-compose

---

node/pkg/aggregator/aggregator.go
node/pkg/raft/accessors.go
node/pkg/raft/raft.go
node/pkg/raft/types.go

Minor updates to remove unnecessary interfaces to reduce complications

(OraklNode) Update raft fields and remove interfaces

---

node/migrations/000001_initialize_tables.down.sql
node/migrations/000001_initialize_tables.up.sql

Adds table for fetcher
Q)
1. I have made default value for `active` column as true, should it be set into false?
2. Are there more constraints I should add?

(OraklNode) Add db migration file

---

node/pkg/db/pgsql.go
node/pkg/db/redis.go

As struct method aren't allowed to use generic types, updated package to utilize in less complicated way

(OraklNode)Update db package

---

.gitignore

Add `.env` to root `.gitignore`

---

node/taskfiles/taskfile.local.yml

Adds missing tasks to run tests

(OraklNode) Add missing tasks

---

fetcher/src/job/job.processor.ts

(Fetcher) Remove data & aggregate debug logs

---

core/src/listener/listener.ts

change log state from info to debug for `noop` listener result

(Listener) Update noop info log into debug state

---

.github/workflows/node.test.yaml
node/pkg/admin/tests/adapter_test.go
node/pkg/admin/tests/feed_test.go
node/pkg/admin/tests/main_test.go

removes global variables from admin test

(OraklNode) Update admin test code

---

node/pkg/admin/adapter/controller.go
node/pkg/admin/adapter/queries.go
node/pkg/admin/adapter/route.go
node/pkg/admin/fetcher/controller.go
node/pkg/admin/fetcher/router.go
node/pkg/admin/tests/adapter_test.go
node/pkg/admin/tests/fetcher_test.go
node/pkg/admin/tests/main_test.go
node/pkg/admin/tests/test_helper.go
node/pkg/admin/utils/utils.go
node/pkg/bus/bus.go
node/pkg/bus/bus_test.go
node/pkg/bus/types.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/main_test.go
node/taskfiles/taskfile.local.yml

- message bus will be used to communicate between admin <-> fetcher
- test code from admin side checks if the proper message has been sent
> PR for fetcher side implementation will be opened soon
Since deps are running in parallel, it lead to error on concurrently accessing db. updated to use `cmds` instead of `deps`

(OraklNode) bus & admin pkg update for fetcher control

---

fetcher/package.json

Removed uniswapV3 SDK in fetcher

---

core/src/reporter/utils.ts

changed the way to get wallet address in sendTransaction function

---

go.work.sum
node/README.md
node/cmd/main.go
node/go.mod
node/go.sum
node/pkg/admin/adapter/controller.go
node/pkg/admin/feed/controller.go
node/pkg/admin/fetcher/controller.go
node/pkg/admin/tests/test_helper.go
node/pkg/admin/utils/utils.go
node/pkg/aggregator/aggregator.go
node/pkg/fetcher/fetcher.go
node/pkg/libp2p/libp2p.go
node/pkg/libp2p/libp2p_test.go
node/pkg/raft/raft.go
node/pkg/utils/request.go

- Utilize zerolog(https://github.com/rs/zerolog) for leveled logging implementation
- Updates `DiscoverPeers()` to return error on failure

(OraklNode) Leveled logging implementation

---

node/migrations/000002_local_aggregates.up.sql
node/pkg/admin/adapter/controller.go
node/pkg/admin/utils/utils.go
node/pkg/bus/bus.go
node/pkg/bus/bus_test.go
node/pkg/fetcher/fetcher.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/main_test.go
node/pkg/fetcher/types.go

- subscription with separate goroutine
- message handling
- start adapter
- stop adapter
- update setup & cleanup codes
- add tests for new functions
- message exchange checks
- go routines checks
- use map instead of array for fetcher adapters
- bus package update to return error on publish failure
- add delay after message publish in adapter controller for message to be processed

(OraklNode) Fetcher control implementation

---

node/pkg/utils/request.go
node/pkg/utils/tests/request_test.go
node/taskfiles/taskfile.local.yml

Adds proxy request functions to utils/requests package, further later to be used from fetcher. Includes test codes with mocked servers and responses

(OraklNode) Utils proxy request and test codes

---

node/migrations/000003_proxy.down.sql
node/migrations/000003_proxy.up.sql
node/pkg/admin/proxy/controller.go
node/pkg/admin/proxy/queries.go
node/pkg/admin/proxy/route.go
node/pkg/admin/tests/main_test.go
node/pkg/admin/tests/proxy_test.go

- Adds proxy table migration file, and admin functionality for proxy CRUD
- Includes test code

(OraklNode) Proxy admin

---

node/pkg/admin/tests/adapter_test.go
node/pkg/admin/tests/feed_test.go
node/pkg/admin/tests/main_test.go
node/pkg/admin/tests/proxy_test.go

unifies temp variable names into tmp

(OraklNode) unify temp -> tmp

---

node/pkg/admin/tests/adapter_test.go
node/pkg/admin/tests/feed_test.go
node/pkg/admin/tests/fetcher_test.go
node/pkg/admin/tests/main_test.go
node/pkg/admin/tests/proxy_test.go

removes underscored function names

(OraklNode) Rename functions

---

node/pkg/admin/adapter/controller.go
node/pkg/admin/fetcher/controller.go
node/pkg/admin/tests/adapter_test.go
node/pkg/admin/tests/fetcher_test.go
node/pkg/bus/types.go
node/pkg/fetcher/fetcher.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/main_test.go
node/pkg/fetcher/types.go

used different naming for each element in fetcher package
the same rule will be applied to aggregator as well
it also updates related bus message variables and its usage from test codes
Fetcher / Adapter
App / Fetcher

(OraklNode) Update naming for fetcher package

---

node/go.mod
node/go.sum
node/pkg/fetcher/fetcher.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/main_test.go
node/pkg/fetcher/types.go
node/pkg/utils/request.go

- Add Proxy type into fetcher package, and proxy lists into fetcher structure
- Makes proxy request or non-proxy request depending on length of proxies
- Includes test code which runs actual proxy server in local and test proxy request

(OraklNode) Integrate proxy request into fetcher

---

node/pkg/raft/raft.go

Raft package is to be used from aggregator package and submitter package.
Through this update, it will more utilize the context given from utilizing packages, and stop if `ctx.cancel()` is called from utilizing packages.

(OraklNode) Update context usage from raft

---

node/pkg/admin/aggregator/controller.go
node/pkg/admin/aggregator/queries.go
node/pkg/admin/aggregator/route.go
node/pkg/admin/tests/aggregator_test.go
node/pkg/admin/tests/main_test.go
node/pkg/bus/types.go

includes CRUD for aggregator, activation and deactivation, and sync with adapter.
if there is a record which exist in adapters but not in aggregator, sync will add row to aggregators

(OraklNode) Aggregator control admin

---

go-delegator/utils/utils.go

adds if statement checking if loaded pk from gsm is empty

(Delegator) Check if pk string is empty

---

go-delegator/go.mod
go-delegator/go.sum
go-delegator/sign/controller.go
go-delegator/utils/utils.go

- add multiple logs for error
- add trimming "0x" from receiving pk

(Delegator) Update for debugging

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/node.go

- Removes comments
- Separates `loadLatestRoundId()` into function to write test codes
- Initialize round id from `aggregator/node.go` rather than `aggregator/aggregator.go`

(OraklNode) Minor code updates, removing comments

---

.github/workflows/node.test.yaml
node/pkg/aggregator/aggregator_test.go
node/pkg/aggregator/main_test.go
node/pkg/aggregator/node.go
node/pkg/aggregator/node_test.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/main_test.go
node/pkg/libp2p/main_test.go
node/taskfiles/taskfile.local.yml

- Adds test code for OraklNode aggregator
- It doesn't cover every part of the code since actual execution is done asynchronously throughout multiple decentralized peers.
- Includes minor code updates done while writing test code

(OraklNode) Aggregator test codes

---

node/pkg/libp2p/libp2p.go
node/pkg/libp2p/libp2p_test.go
node/pkg/utils/request.go

- Update request url protocol to http on proxy request
- update libp2p test to include bootnode on peersearching to reduce test time
- set global log level on testing to reduce logs

(OraklNode) Update url protocol into `http` on proxy request

---

node/pkg/admin/aggregator/controller.go
node/pkg/admin/aggregator/route.go
node/pkg/admin/fetcher/controller.go
node/pkg/admin/tests/aggregator_test.go
node/pkg/aggregator/aggregator.go
node/pkg/aggregator/aggregator_test.go
node/pkg/aggregator/types.go
node/pkg/fetcher/fetcher.go

- Adds missing control functions that's been set up as TODOs in comment
- Updates done with few vulnerabilities found while writing test codes

(OraklNode) Add aggregator controls and testcode

---

.github/workflows/godelegator.image+upload.yaml

Update helm-chart-pr job to depend on build, 
before checking out from remote branch, fetch all

(Deployment) Add job dependency, fetch all before checkout

---

.github/workflows/godelegator.image+upload.yaml

(Deployment) Update github action to set up account

---

.github/workflows/godelegator.image+upload.yaml

add branch push step

---

.github/workflows/godelegator.image+upload.yaml

Fix/update GitHub actions

---

go-delegator/README.md

(TEST) Trigger github action

---

.github/workflows/godelegator.image+upload.yaml

Fix typo, add branch name

---

go-delegator/README.md

Test update to trigger github action

---

.github/workflows/create-helmchart-pr.yaml

Github action file for helmchart pr generation was missing typo on `appVersion` declaration.

Add missing typo on version declaration

---

node/cmd/test_connection/main.go

add code to prevent unexpected exit on connection test 

(OraklNode) prevent exit on connection test

---

go-delegator/README.md

Test pr for github action trigger

---

node/script/test_raft/main.go

Takes bootnode as comand line parameter just as connection test to test with cases also with bootnode

(OraklNode) Include bootnode parsing for flexible tests

---

node/pkg/chain/utils/types.go

(OraklNode) Update default gas limit

---

dockerfiles/orakl-node.Dockerfile
node/pkg/admin/admin.go
node/taskfiles/taskfile.local.yml

Minor updates to improve go-task and app controls
- add more commands to go task file
- install `jq` from docker image to be used from go tasks
- add missing endpoint on running api

(OraklNode) Minor updates for app control

---

node/pkg/db/pgsql.go
node/pkg/db/pgsql_test.go
node/pkg/fetcher/fetcher.go

Will test out if Bulk Insert is more efficient than Bulk Copy for small records (less than 10)

(OraklNode) Separate bulk copy with bulk insert

---

fetcher/src/job/job.utils.ts

switch how DEX price is denominated by

Support reciprocal division for DEX fetcher

---

fetcher/src/job/job.utils.ts

Updates `extractFeeds` to take all definition attributes

Update extract feed function to take all definition attributes

---

contracts/v0.2/script/Full.s.sol

This PR updates deployment script of `Feed` contracts, and whitelists `oracle` (off-chain reporter) so that on-chain verification can executed.

(on-chain) Deployment script to whitelist reporter address

---

node/pkg/fetcher/fetcher.go
node/pkg/fetcher/types.go

Reciprocal division to switch denomination for certain price pairs

(OraklNode) support reciprocal division for fetcher

---

contracts/v0.2/script/Full.s.sol
contracts/v0.2/src/Feed.sol
contracts/v0.2/src/FeedProxy.sol
contracts/v0.2/src/FeedRouter.sol
contracts/v0.2/src/SubmissionProxy.sol
contracts/v0.2/src/interfaces/IFeed.sol
contracts/v0.2/src/interfaces/IFeedProxy.sol
contracts/v0.2/src/interfaces/IFeedRouter.sol
contracts/v0.2/test/Feed.t.sol
contracts/v0.2/test/SubmissionProxy.t.sol

* Mover verification from `Feed` to `SubmissionProxy`
* Remove `verified` property from `Round` struct
* Remove unverified submission function through `SubmissionProxy`
* Remove `onlyOracle` modifier from `SubmissionProxy` submission function
* Introduce minimum proof threshold property for each data feed

Move verification to submission proxy

---

node/pkg/aggregator/aggregator.go

(OraklNode) Hotfix declare syncedTimes from new aggregator

---

node/pkg/chain/utils/utils.go
node/pkg/reporter/reporter.go

Adds more logs to find the cause of issue

(OraklNode) Add more logs to fix not reporting issue

---

node/pkg/chain/utils/utils.go
node/pkg/reporter/reporter.go

Add more logs in ChainHelper and Reporter codes to debug

(OraklNode) Add more logs to find cause for the issue

---

node/pkg/chain/utils/utils.go

(OraklNode) Add more logs

---

node/pkg/chain/helper/helper.go

Rollback endpoint for delegator endpoint

(OraklNode) Rollback endpoint for delegator sign

---

dockerfiles/orakl-api.Dockerfile
dockerfiles/orakl-boot-api.Dockerfile
dockerfiles/orakl-cli.Dockerfile
dockerfiles/orakl-core.Dockerfile
dockerfiles/orakl-delegator.Dockerfile
dockerfiles/orakl-fetcher.Dockerfile
dockerfiles/orakl-general.Dockerfile
dockerfiles/orakl-node.Dockerfile

Removes package list cache files after linux package installation to reduce docker image size.

Minor updates to reduce docker image sizes

---

contracts/v0.2/src/SubmissionProxy.sol
contracts/v0.2/test/SubmissionProxy.t.sol

* Split `submit` function to `submit` and `verifyProof`
* Change order of submit parameters (`answers` and `timestamps` closer to each other)
* Rename `threshold` to `defaultThreshold`

On-Chain General Updates

---

node/pkg/chain/utils/utils.go

fix error where the app fails to load wallet

(OraklNode) Trim prefix 0x on saving wallet into memory

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/types.go

(OraklNode) Update global aggregates storing logics

---

node/pkg/libp2p/utils/utils.go
node/pkg/por/app.go
node/pkg/reporter/reporter.go
node/pkg/reporter/utils.go
node/pkg/utils/retrier/retrier.go
node/pkg/utils/tests/retrier_test.go

Minor refactoring separating retry logic into separate package for reusability

(OraklNode) Separate Retrier

---

node/pkg/aggregator/utils.go
node/pkg/fetcher/utils.go
node/pkg/reporter/utils.go

This PR utilizes recent redis helper package updates which adds function that stores or loads object instead of string.

(OraklNode) Refactor redis package reference using get/set object

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/aggregator_test.go
node/pkg/aggregator/app.go
node/pkg/aggregator/app_test.go
node/pkg/aggregator/main_test.go
node/pkg/aggregator/types.go

This updates rename `AggregatorConfig` -> `Config`. All related function and variable will be effected. It makes it more clear that the value comes from `configs` table and also aligns with reporter package which has similar structure

(OraklNode) Rename functions and variables

---

.github/workflows/cli.build+publish.yaml
.github/workflows/cli.test.yaml
cli/package.json

The orakl/cli build + publish is currently triggered on every branch except master. This PR implements both manual trigger and auto publishing on master branch.

update cli publish workflow and increment package version

---

delegator/utils/utils.go

Hotfix, remove pk prefix when loading from vault

---

.github/workflows/delegator.image+upload.yaml

add workflow dispatch in git action

add workflow dispatch

---

.github/workflows/delegator.image+upload.yaml
delegator/README.md

fixed add workflow dispatch space betwen

---

node/pkg/aggregator/main_test.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/main_test.go
node/pkg/reporter/main_test.go

- Add missing test cleanup codes
- Change fetcher test config which doesn't include klaytn mainnet dex src (Klaytn public json rpc blocks github action instance ip)

(OraklNode) Fix minor test issues

---

dockerfiles/orakl-por.Dockerfile

Docker build for IDC need to add flags (ubuntu)

POR  docker build for idc

---

node/pkg/fetcher/app.go
node/pkg/fetcher/app_test.go
node/pkg/fetcher/fetcher.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/types.go

Update `FetcherConfig` -> `Config` to follow conventions from other packages (`reporter`, `aggregator`)
Improves consistency aligns with db table name `configs`

(OraklNode) Rename `FetcherConfig` to `Config`

---

api/secrets/secrets.go
api/utils/utils.go

Update vault reference, store secrets once on package load

(API) Update vault code for api

---

api/go.mod
api/go.sum

(API) Add missing pkg

---

delegator/migrations/000003_remove_pk_table.down.sql
delegator/migrations/000003_remove_pk_table.up.sql
delegator/tests/globals_test.go
delegator/utils/utils.go

Removes table and code related to pk retrieval from db.

(Delegator) Remove unused code

---

contracts/v0.2/README.md
contracts/v0.2/addresses/datafeeds-addresses.json
contracts/v0.2/addresses/others-addresses.json
contracts/v0.2/script/collect-addresses.cjs

- Code mostly copy & pasted from `./contracts/v0.1/scripts/generate-contract-addresses.cjs` script.
- Collects addresses to generate json files `datafeeds-addresses.json` and `others-addresses.json`.
- Internal formats follows v0.1
https://raw.githubusercontent.com/Bisonai/orakl/master/contracts/v0.1/deployments/datafeeds-addresses.json
https://raw.githubusercontent.com/Bisonai/orakl/master/contracts/v0.1/deployments/other-addresses.json

(Contracts) Add script to collect deployed v2 contracts

---

contracts/package.json

Deploy package with updated contract events

---

dockerfiles/orakl-node.Dockerfile

Fixed docker cgo blast for Node

---

node/pkg/boot/peer/controller.go
node/pkg/libp2p/setup/setup.go

(OraklNode) Add error handling on connection check

---

.github/workflows/node.test.yaml
node/pkg/admin/config/controller.go
node/pkg/admin/tests/config_test.go
node/pkg/secrets/secrets.go

On calling config sync, it'll now remove entries from database which doesn't exist in orakl config.
Test code included

(OraklNode) Update based on expected behavior

---

delegator/sign/controller.go
delegator/tests/contract_test.go
delegator/tests/function_test.go
delegator/tests/globals_test.go
delegator/tests/organization_test.go
delegator/tests/reporter_test.go
delegator/tests/sign_test.go

Fix linter errors which led to build failure

(Delegator) Fix minor linter errors

---

node/pkg/db/redis.go
node/pkg/db/redis_test.go

Adds redis utility function to be utilized on data streaming, includes related test codes
- [LRange](https://redis.io/docs/latest/commands/lrange/)
- [LPush](https://redis.io/docs/latest/commands/lpush/)
- LPushObject (Same as LPush but takes interface{} to be json marshalled)
- PopAll (LRange all and Delete Atomically)
- PopAllObject (PopAll to get objects)

(OraklNode) Redis list functionalities

---

core/src/listener/utils.ts
core/src/reporter/state.ts
core/src/utils.ts
core/test/listener.test.ts
core/test/reporter.test.ts

Add address check on running listener and reporter
[related issue](https://github.com/Bisonai/orakl/issues/1070)

Add address validation on service launch

---

node/go.mod
node/go.sum
node/pkg/wss/utils.go
node/pkg/wss/utils_test.go
node/pkg/wss/wss.go
node/pkg/wss/wss_test.go
node/taskfiles/taskfile.local.yml

Building blocks for websocket functionalities

(OraklNode) Basic building block for wss

---

.github/workflows/api.image+upload.yaml
.github/workflows/api.test.yaml
.github/workflows/delegator.image+upload.yaml
.github/workflows/delegator.test+build.yaml
api/blocks/controller.go

It is better to find the issue before merging into main branch as lint or vet failure leads to image build failure

(API & Delegator) run lint and vet from test action

---

node/cmd/node/main.go
node/pkg/admin/config/controller.go

Add more logs in cmd

---

node/pkg/fetcher/fetcher.go

Fix typo and prevent possible unexpected channel close

---

node/pkg/fetcher/fetcher.go

Rollback to fix nilpoint err

---

node/pkg/fetcher/fetcher.go

Hotfix add missing return statement on switch default

---

node/pkg/websocketfetcher/app.go
node/pkg/websocketfetcher/common/type.go
node/pkg/websocketfetcher/common/utils.go
node/pkg/websocketfetcher/tests/utils_test.go

Update feed definition and db query for websocket feeds

(OraklNode) Update how feeds are parsed from database

---

node/pkg/fetcher/app.go
node/pkg/fetcher/types.go

Select only non websocket feeds from http request fetcher

(OraklNode) Select only non-wss feeds from http request fetcher

---

node/pkg/admin/wallet/controller.go
node/pkg/admin/wallet/route.go
node/taskfiles/taskfile.local.yml

To be referenced later on oracle expiration check

(OraklNode) Endpoint to get signer public addr

---

node/README.md
node/taskfiles/taskfile.local.yml

(OraklNode) Add refresh aggregator cli

---

node/cmd/node/main.go
node/pkg/admin/admin.go
node/pkg/admin/config/controller.go
node/pkg/admin/config/queries.go

AS-IS
sync db and orakl config by http requesting admin endpoint on app launch
TO-BE
sync through calling public function in admin package

(OraklNode) Sync Orakl Config through function call

---

node/.env.example
node/pkg/libp2p/utils/utils.go

Enable host ip address manual setting for node communication

(OraklNode) Designated host ip

---

node/cmd/node/main.go

`BOOT_NODE` env is not used anymore but emitting log after checking if exists. This PR removes related codes

(OraklNode) Remove unnecessary env check log

---

node/pkg/libp2p/setup/setup.go

Add NATPort map option to libp2p

---

node/pkg/websocketfetcher/app.go

include websocket fetcher providers after orakl-config update

(OraklNode) include unreferenced websocket fetcher providers

---

node/pkg/libp2p/setup/setup.go

(OraklNode) remove nat setting

---

node/pkg/libp2p/utils/utils.go

(OraklNode) add logs for debugging

---

node/pkg/libp2p/setup/setup.go

(OraklNode) Try out holepunch option

---

node/pkg/websocketfetcher/providers/mexc/mexc.go
node/pkg/websocketfetcher/providers/mexc/type.go
node/pkg/websocketfetcher/providers/mexc/utils.go

Mexc only allows maximum 30 subscription, which could lead to potential failure of subscription in the future. instead of subscribing for price pairs one by one, this pr will subscribe to batch ticker and only store the ones we're interested in

(OraklNode) Update Mexc subscription

---

.github/workflows/deployment.yaml

Update deployment.yaml for por

---

node/pkg/boot/peer/controller.go

(BootAPI) add logs for debugging

---

node/cmd/node/main.go

(OraklNode) Retry boot api connection 5 times with maximum 30 seconds delay

---

node/cmd/node/main.go

(OraklNode) Remove duplicate conn

---

node/pkg/libp2p/setup/setup.go

Retry peer connection after receiving peer connection from boot api

(OraklNode) Retry peer connection on failure

---

sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/signer/app.go
sentinel/pkg/checker/signer/utils.go

minor updates based on missed coderabbit revies
- fix typo
- print delayed time instead of offset in event checker
- add logs

(Sentinel) Minor sentinel updates

---

node/README.md

Include new packages, remove unused environment variable

(OraklNode) Minor docs updates

---

node/pkg/websocketfetcher/providers/kucoin/kucoin.go
node/pkg/websocketfetcher/providers/kucoin/type.go

PR to fix following issue
https://github.com/Bisonai/orakl/issues/1586
once kucoin fetcher retrieves token from the server, it also takes ping interval. based on this interval, ping message should be sent to kucoin server so that the connection is not lost

(OraklNode) Include ping handling into kucoin fetcher

---

node/pkg/websocketfetcher/providers/crypto/types.go

related issue
https://github.com/Bisonai/orakl/issues/1587
remove field which aren't relative

(OraklNode) Remove a field in crypto.com

---

node/pkg/reporter/reporter.go

(OraklNode) Update info level for reporter job duration

---

node/pkg/reporter/reporter.go

Add more logs to track down reporter bottleneck

(OraklNode) Add more logs to track down bottleneck

---

node/pkg/reporter/reporter.go

Adds more logs to measure time within reporter job

(OraklNode) Add more logs to debug

---

node/pkg/chain/utils/utils.go
node/pkg/error/sentinel.go
node/pkg/reporter/reporter.go

Try out submission with increased gas price

(OraklNode) Gas price increase by 20%

---

node/pkg/reporter/types.go

(OraklNode) Test 40% increase of gas price

---

node/pkg/reporter/reporter.go

(OraklNode) Add log to track number of valid aggregates

---

node/pkg/reporter/reporter.go
node/pkg/reporter/types.go

(OraklNode) Rollback gas multiplier, add logs

---

sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/event/types.go

if event is delayed for more than 3 times in a row, it'll send a message 

(OraklSentinel) Send slack message if delayed more than 3 times in a row

---

node/pkg/raft/accessors.go
node/pkg/raft/raft.go
node/pkg/raft/types.go

Remove manually implemented peer tracking logic which was for udp/quic compatibility.

(OraklNode) Rollback peer count logic

---

.github/workflows/cli.test.yaml
.github/workflows/delegator.test+build.yaml
.github/workflows/node.test.yaml
.github/workflows/sentinel.test.yaml
contracts/v0.1/hardhat.config.cjs
contracts/v0.2/foundry.toml
contracts/v0.2/package.json
core/test/reporter.test.ts
dockerfiles/local-data-feed/envs/.core.env
dockerfiles/local-data-feed/envs/.delegator.env
node/.env.local
node/pkg/chain/tests/chain_test.go

Replaces all uses of public JSON-RPC with Kairos public JSON-RPC according to https://klaytn.foundation/kaia-testnet-kairos-launch/

Update JSON-RPC to kairos

---

node/pkg/por/app.go

POR public address return failure due to os.Getenv, replacing it with secret

(POR)fix por pk retrieval

---

node/pkg/aggregator/utils.go
node/pkg/error/sentinel.go

Safety Bar for data insertion 🙏🥹

(OraklNode) Add validation on global aggregate insertion

---

node/pkg/aggregator/aggregator.go

Will be utilized for Q2 milestone proof to show global aggregate interval and communication between nodes

(OraklNode) Track global aggregation

---

node/README.md
node/taskfiles/taskfile.local.yml

cli for following functionalities are added
- remove wallet
- remove proxy
- remove json rpc

(OraklNode) Add cli to remove entries

---

node/pkg/reporter/reporter.go

Removes time measuring logs that has been used when debugging delayed offchain aggregation submission

(OraklNode) Remove time measurement logs for debugging

---

sentinel/pkg/checker/balance/app.go
sentinel/pkg/checker/balance/app_test.go

(Sentinel) Fix wallet string not being marshalled from por

---

core/src/reporter/state.ts

- Refactor remote nonce retrieval logic to separate function
- Use `Math.max` for `nonce` decision
- Limit infinite loop into the range of interest

Minor refactor suggestion

---

sentinel/cmd/main.go
sentinel/pkg/checker/balance/app.go
sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/health/app.go
sentinel/pkg/checker/signer/app.go

- Adds signer check code from main cmd
- Adds more logs

(Sentinel) Add missing signer check start and more logs

---

sentinel/pkg/checker/balance/app.go

reduce sleepage and increase default interval for balance check (10s -> 30s)

(Sentinel) Reduce sleepage for balance check

---

node/pkg/aggregator/aggregator.go

Clean up previous round data if exists on new Round Sync Message receive

(OraklNode) Removes prev round data on leaderjob start

---

node/pkg/aggregator/aggregator.go

(OraklNode) Update logs

---

node/pkg/aggregator/aggregator.go

Rollback round data cleanup logic 

(OraklNode) Rollback cleanup logic

---

.github/workflows/node.test.yaml
node/pkg/fetcher/app.go

replace deprecated all that node json rpc

(OraklNode) Update ethereum default public json rpc url

---

sentinel/pkg/checker/balance/app.go
sentinel/pkg/checker/balance/app_test.go

Do not track onchain aggregator reporter wallet balance anymore

(Sentinel) Skip onchain aggregator reporters

---

node/pkg/aggregator/aggregator.go

uncomment rollbacked code, remove previous round data on new round start

(OraklNode) Remove previous round data

---

.github/workflows/vrf.contracts.test.yaml

Add workflow_dispatch to vrf test workflow

---

sentinel/pkg/checker/health/baobab_healthcheck.json

(Sentinel) Remove onchain aggregators from health check

---

node/cmd/node/main.go

app runs without launch failed element. (ex. aggregator and reporter runs while fetcher failed to launch)
exit entire application on single element failure

(OraklNode) Stop entire application on launch fail

---

node/cmd/fetcher/main.go
node/taskfiles/taskfile.local.yml

Add task to run only fetcher from local environment

(OraklNode) Task to run only fetcher for debugging

---

sentinel/pkg/checker/event/app.go

Update event checker logic

---

.github/workflows/vrf.contracts.test.yaml

fix vrf test workflow build issue

---

inspector/hardhat.config.ts

replace allthatnode json rpc for baobab with kairos endpoint

---

fetcher/src/settings.ts

Update deprecated json rpc url

(Fetcher) Update json rpc url

---

sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/event/types.go

(Sentinel) sentinel por event check

---

node/pkg/fetcher/collector.go

This pr adds log to print out locally aggregated details

(OraklNode) Add log to print both vwap and med value

---

README.md
docker-compose.local-core.yaml
dockerfiles/local-vrf-rr/envs/.core-cli-contracts.env
dockerfiles/local-vrf-rr/scripts/clean-db-tables.sh
dockerfiles/local-vrf-rr/scripts/setup-rr.sh
dockerfiles/local-vrf-rr/scripts/setup-vrf.sh
dockerfiles/local-vrf-rr/scripts/update-hardhat-network.js
dockerfiles/local-vrf-rr/scripts/update-rr-migration.js
dockerfiles/local-vrf-rr/scripts/update-vrf-migration.js

Related issue: https://github.com/Bisonai/orakl/issues/867
- Replace hardcoded wallet, chain, etc values with variables that users can set in the relevant `.env` files
- Update readme file accordingly

replace hardcoded values with variables in vrf rr docker setup

---

sentinel/pkg/checker/health/baobab_healthcheck.json

Update sentinel health checker for updated vrf & rr structure

(Sentinel) Update healthcheck url

---

sentinel/README.md
sentinel/pkg/checker/health/cypress_healthcheck.json

Adds missing healthcheck endpoints (boot-api & node)

(Sentinel) Add missing cypress healthcheck endpoints

---

node/pkg/utils/request/request.go

increase context deadline from 1 second to 2 seconds

(OraklNode)Increase http context deadline for volume fetchers

---

node/pkg/websocketfetcher/app.go
node/pkg/websocketfetcher/providers/bingx/bingx.go
node/pkg/websocketfetcher/providers/bingx/type.go
node/pkg/websocketfetcher/providers/bingx/utils.go
node/pkg/websocketfetcher/providers/bitmart/bitmart.go
node/pkg/websocketfetcher/providers/bitmart/type.go
node/pkg/websocketfetcher/providers/bitmart/utils.go
node/pkg/websocketfetcher/providers/kraken/kraken.go
node/pkg/websocketfetcher/providers/kraken/type.go
node/pkg/websocketfetcher/providers/kraken/utils.go
node/pkg/websocketfetcher/providers/okx/okx.go
node/pkg/websocketfetcher/providers/okx/type.go
node/pkg/websocketfetcher/providers/okx/utils.go
node/pkg/websocketfetcher/providers/xt/type.go
node/pkg/websocketfetcher/providers/xt/utils.go
node/pkg/websocketfetcher/providers/xt/xt.go
node/pkg/wss/utils.go

Adds support for following exchanges
- [okx](https://www.notion.so/baea6d9524d74e2c900f3c183741944d?pvs=25)
- [kraken](https://docs.kraken.com/api/docs/websocket-v2/ticker/)
- [bingx](https://bingx-api.github.io/docs/#/en-us/swapV2/socket/market.html#Subscribe%20to%2024-hour%20price%20changes)
- [bitmart](https://developer-pro.bitmart.com/en/spot/#websocket-subscription)
- [xt](https://doc.xt.com/#websocket_publictickerRealTime)

(OraklNode) Add price providers

---

node/pkg/websocketfetcher/providers/bitstamp/utils.go

Fix error from bitstamp data time conversion
rollbacks to previous implementation

(OraklNode) Hotfix UnixMilli to previous implementation for `BitStamp`

---

contracts/v0.2/addresses/datafeeds-addresses.json
contracts/v0.2/script/collect-addresses.cjs

Reflects tags based on updated price providers,
Hopefully, it'll update frontend cards with new tags

Update price pair tags

---

node/pkg/admin/config/controller.go
node/pkg/chain/helper/helper.go
node/pkg/error/sentinel.go
node/pkg/fetcher/fetcher.go
node/pkg/fetcher/utils.go
node/pkg/libp2p/setup/setup.go
node/pkg/por/app.go
node/pkg/utils/request/request.go
node/pkg/utils/tests/request_test.go
node/pkg/websocketfetcher/providers/bitstamp/utils.go
node/pkg/websocketfetcher/providers/btse/utils.go
node/pkg/websocketfetcher/providers/gemini/utils.go
node/pkg/websocketfetcher/providers/kucoin/kucoin.go

Implement functional options pattern to request package

(OraklNode) Refactor request package

---

node/pkg/admin/aggregator/controller.go
node/pkg/admin/config/controller.go
node/pkg/admin/feed/controller.go
node/pkg/admin/fetcher/controller.go
node/pkg/admin/providerUrl/controller.go
node/pkg/admin/proxy/controller.go
node/pkg/admin/reporter/controller.go
node/pkg/admin/utils/utils.go
node/pkg/admin/wallet/controller.go

Log out error from orakl node admin

(OraklNode) Add admin logs

---

sentinel/pkg/checker/event/app.go

increase feed buffer into interval * 2 (30 secs)

Increase buffer

---

sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/event/types.go

Checks VRF fullfillment regularly and send alarm on failed cases

(Sentinel) Add VRF fullfillment check

---

sentinel/pkg/checker/event/app.go

(Sentinel) fulfillment table column name is `block$` not `block`

---

sentinel/pkg/checker/event/types.go

unlike json, pgsql should have all matching columns defined in struct, unless emit error for missing columns

(Sentinel) Fix query

---

sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/event/types.go

TODO:
[reference](https://github.com/jackc/pgx/wiki/Numeric-and-decimal-support)

(Sentinel) Remove unsupported column

---

sentinel/pkg/checker/event/app.go

(Sentinel) Add alarm skip condition(requested in 3 sec)

---

sentinel/pkg/checker/event/app.go

(Sentinel) fix wrong skip condition

---

.github/workflows/node.test.yaml
node/.env.example
node/pkg/chain/eth_client/eth_client.go
node/pkg/chain/utils/types.go
node/pkg/chain/utils/utils.go
node/pkg/chain/websocketchainreader/type.go
node/pkg/chain/websocketchainreader/websocketreader.go
node/pkg/error/sentinel.go
node/pkg/fetcher/app.go
node/pkg/fetcher/fetcher.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/types.go
node/pkg/fetcher/utils.go
node/pkg/fetcher/utils_test.go
node/pkg/websocketfetcher/app.go
node/pkg/websocketfetcher/common/type.go
node/pkg/websocketfetcher/providers/uniswap/uniswap.go
node/script/test_websocketDexFetcher/main.go
node/script/test_websocketchainreader/main.go
node/taskfiles/taskfile.local.yml

Websocket based dex price fetcher.

(OraklNode) Websocket dex fetcher

---

node/pkg/fetcher/app.go

Add http fetcher only if feeds exist

(OraklNode) Update fetcher init

---

sentinel/pkg/checker/health/cypress_healthcheck.json

Update cypress healthcheck endpoints for new structural update

(Sentinel) Update cypress rr and vrf endpoints

---

sentinel/pkg/checker/health/app.go

Related issue #1648 
- in healthcheck, send "<service_name> is back up" slack message after it's been down

send service is up slack message after it's been down

---

node/pkg/utils/request/request.go

(OraklNode) Update proxy request

---

node/pkg/fetcher/collector.go

Local aggregate in separate thread

(OraklNode) Execute local aggregate in thread

---

node/pkg/fetcher/collector.go
node/pkg/websocketfetcher/app.go

Reduce intervals for websocket data streaming and local aggregates

(OraklNode) Reduce intervals

---

sentinel/.env.example
sentinel/pkg/checker/signer/app.go

take signer through env variable

(Sentinel) Add external signers to signer check

---

node/README.md
node/pkg/admin/config/controller.go
node/pkg/admin/config/queries.go
node/pkg/admin/tests/main_test.go
node/taskfiles/taskfile.local.yml

Previous implementation somehow failed to remove deprecated feeds. tested with updated query working properly

(OraklNode) Update sync

---

sentinel/.env.example

minor fix for .env.example typo

(Sentinel) fix typo

---

node/pkg/common/types/types.go
node/pkg/fetcher/types.go
node/pkg/websocketfetcher/common/type.go

move Feed type to common types

---

node/pkg/boot/peer/controller.go
node/pkg/boot/peer/route.go
node/pkg/boot/tests/peer_test.go

- remove `get` and `post` peer apis
- update tests accordingly

remove unused boot api endpoints (get and post)

---

node/pkg/websocketfetcher/providers/uniswap/uniswap.go
node/script/test_websocketDexFetcher/main.go

- Update event definition for klayswap
- Remove slot based price fetching logic
- Update dex websocket fetcher script to print our from the channel
- checked event subscription through the script
example log
```
{"level":"debug","Player":"Uniswap","feedData":{"FeedID":12,"Value":97814835,"Volume":0,"Timestamp":"2024-06-27T13:11:45.563484+09:00"},"time":"2024-06-27T13:11:45+09:00","message":"price fetched"}
{"level":"info","data":{"FeedID":12,"Value":97814835,"Volume":0,"Timestamp":"2024-06-27T13:11:45.563484+09:00"},"time":"2024-06-27T13:11:45+09:00","message":"data"}
{"level":"debug","Player":"Uniswap","feedData":{"FeedID":12,"Value":97816515,"Volume":0,"Timestamp":"2024-06-27T13:11:45.563769+09:00"},"time":"2024-06-27T13:11:45+09:00","message":"price fetched"} …
```

(OraklNode) Update klayswap to use websockets again

---

node/cmd/aggregator/main.go
node/taskfiles/taskfile.local.yml

Run admin, fetcher, and aggreagtor

(OraklNode) Add aggregator entrypoint

---

sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/event/types.go

send slack message if feed submits more than 8 times in a min

---

node/pkg/websocketfetcher/providers/bybit/bybit.go
node/pkg/websocketfetcher/providers/bybit/type.go
node/pkg/websocketfetcher/providers/bybit/utils.go
node/script/test_websocketFetcher/main.go

(OraklNode) Update bybit v2 to v5

---

node/pkg/websocketfetcher/providers/bitget/bitget.go
node/pkg/websocketfetcher/providers/bitget/type.go
node/pkg/websocketfetcher/providers/bitget/utils.go
node/pkg/websocketfetcher/tests/utils_test.go

Updates Bitget api from v1 to v2

(OraklNode) Bitget api update from v1 to v2

---

sentinel/cmd/main.go
sentinel/pkg/checker/health/app.go
sentinel/pkg/checker/signer/app.go

update sentinel to shutdown on launch failure

(Sentinel) Ensure sentinel full launch

---

sentinel/pkg/checker/balance/app.go
sentinel/pkg/checker/event/app.go
sentinel/pkg/checker/signer/app.go
sentinel/pkg/request/request.go

found out that the orakl api call has delayed response leading to balance checker launch failure. this updates timeout for orakl api call, and also includes refactoring of request package

(Sentinel) Update request package and reference

---

node/pkg/db/redis.go
node/pkg/db/redis_test.go

Add Pub/Sub functionality into redis wrapper

(OraklNode) Redis pubsub

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/aggregator_test.go
node/pkg/aggregator/app.go
node/pkg/aggregator/app_test.go
node/pkg/aggregator/main_test.go
node/pkg/aggregator/streamer.go
node/pkg/aggregator/streamer_test.go
node/pkg/aggregator/types.go
node/pkg/aggregator/utils.go
node/pkg/common/keys/keys.go
node/pkg/db/redis.go
node/pkg/db/redis_test.go
node/pkg/error/sentinel.go

Publish GlobalAggregate & Proof through redis to be referenced later also from `data availability layer` application

(OraklNode) Pub/Sub based GlobalAggregate & Proof storage

---

node/pkg/wss/utils.go

Internal property not accessed concurrently, thus removing mutex

(OraklNode) Remove unnecessary mutex

---

node/pkg/fetcher/accumulator.go

fix accumulator cpu issue

---

.github/workflows/dal.test.yaml
node/.env.example
node/pkg/admin/tests/test_helper.go
node/pkg/dal/tests/api_test.go
node/pkg/dal/utils/utils.go
node/pkg/wss/utils.go

Basic api key implementation for beta

(DAL) Implement basic api key

---

.vscode/settings.json

Sets `settings.json` to format based on `gofmt` for vscode users

Consistent `Go` format settings

---

node/pkg/fetcher/accumulator.go

Add condition to prevent overwriting redis database with old local aggregate data.

(OraklNode) Add accumulator condition

---

node/pkg/reporter/types.go

Update deviation threshold for longer submission interval period preperation

(OraklNode) Update deviation threshold from 5% to 1%

---

.github/workflows/deployment.yaml

Update to fix github action build failure

Add dal as an exception in github action

---

node/README.md
node/pkg/admin/aggregator/controller.go
node/pkg/admin/aggregator/route.go
node/pkg/aggregator/app.go
node/pkg/aggregator/types.go
node/pkg/bus/types.go
node/taskfiles/taskfile.local.yml

Adds manual signer update functionality
Currently having 12hrs interval for auto sign renewal, should be waited for 12hs until first signer renew job execution

(OraklNode) Manual update signer

---

node/pkg/reporter/app.go
node/pkg/reporter/reporter.go

Possible fix for multiple wallets delegator request from baobab

(OraklNode) Define new chainhelper without additional wallets

---

sentinel/pkg/checker/health/baobab_healthcheck.json

removes unused redis healthcheck

(Sentinel) remove datafeed redis and fetcher redis healthcheck

---

.github/workflows/node.test.yaml

lint & vet taking too much time

(OraklNode) Remove lint & vet from github action

---

node/pkg/chain/helper/helper.go
node/pkg/chain/helper/signer.go
node/pkg/chain/helper/types.go
node/pkg/chain/utils/utils.go
node/pkg/reporter/app.go
node/pkg/reporter/reporter.go

AS-IS
wallets stored automatically into wallets table whenever new chainHelper has been initialized
TO-BE
add `WithoutWalletStore` option
AS-IS
explicitly check duplicate wallet before wallet insertion
TO-BE
add duplicate wallet check into InsertWallet func

(OraklNode) Minor updates related to reporter wallet insertion

---

node/pkg/dal/api/controller.go
node/pkg/dal/api/route.go

`/dal/symbols` endpoints returns all symbols in list of strings
docs will be updated accordingly

(DAL) Add endpoint to get all symbols

---

node/pkg/chain/helper/helper.go
node/pkg/chain/helper/signer.go
node/pkg/chain/tests/chain_test.go
node/pkg/chain/utils/utils.go
node/pkg/error/sentinel.go
node/pkg/reporter/reporter.go
node/pkg/reporter/types.go
node/script/test_submission/main.go

Remove gas multiplier function parameter

(OraklNode) Remove unused function parameter `GasMultiplier`

---

.github/workflows/api.test.yaml
.github/workflows/boot-api.test.yaml
.github/workflows/cli.build+publish.yaml
.github/workflows/cli.test.yaml
.github/workflows/contracts.test+publish.yaml
.github/workflows/core.test+build.yaml
.github/workflows/dal.test.yaml
.github/workflows/delegator.test+build.yaml
.github/workflows/node.test.yaml
.github/workflows/sentinel.test.yaml
.github/workflows/util.test.yaml
.github/workflows/vrf.build+publish.yaml
.github/workflows/vrf.contracts.test.yaml

Update github actions with deprecation warnings

Update github actions

---

sentinel/pkg/checker/health/baobab_healthcheck.json

(Sentinel) Include dal healthcheck endpoint

---

node/pkg/dal/utils/utils.go

(DAL) Add log for debugging

---

contracts/v0.2/migration/baobab/SubmissionProxy/20240708143044_update.json

fix type in SubmissionProxy migration

---

node/pkg/aggregator/aggregator.go
node/pkg/fetcher/accumulator.go
node/pkg/raft/raft.go
node/pkg/raft/types.go
node/pkg/reporter/reporter.go
node/script/test_raft/main.go

remove pool integration from accumulator and raft

---

node/pkg/aggregator/main_test.go
node/pkg/db/pgsql.go

Take context param instead of using context.Background

(OraklNode) Remove context.Background() from the db pkg

---

.github/workflows/dal.test.yaml

Removes lint & vet from github action

(DAL) Remove lint & vet from dal test

---

node/.env.example
node/pkg/dal/api/controller.go
node/pkg/dal/app.go
node/pkg/dal/tests/main_test.go

DAL will now call orakl node admin to get configs

(DAL) Load config through request

---

node/pkg/websocketfetcher/app.go

(OraklNode) Store websocket feed_data from thread

---

node/migrations/dal/000005_key_description.down.sql
node/migrations/dal/000005_key_description.up.sql

(DAL) Add description column to keys table

---

sentinel/pkg/checker/signer/app.go

update sentinel signer expiry check

---

node/pkg/utils/reducer/reducer.go
node/script/test_single_fetch/main.go
node/taskfiles/taskfile.local.yml

- remove `,` from float string when parsing from reducer
- add script that can test fetch single definition and related go task

(OraklNode) Update reducer & add single fetch script

---

.github/workflows/deployment.yaml
README.md
TAGS.md

image tag lists removed from the readme, adds new markdown file named `TAGS.md` which will now be updated instead.

Update auto tag doc generation

---

sentinel/cmd/main.go
sentinel/pkg/checker/peers/app.go

Checks number of peers every 10 seconds, adds message if the number of peers have changed

(Sentinel) Sentinel peer check

---

node/pkg/aggregator/streamer.go
node/pkg/aggregator/utils.go

This is not a pr that removes the cause.
The reason for invalid value entries should be investigated more deeply

(OraklNode) Hotfix, filter out invalid value

---

sentinel/pkg/checker/health/cypress_healthcheck.json

(Sentinel) Remove deprecated resource healthcheck

---

node/pkg/dal/utils/stats/stats.go

add ctx logs to dal middleware

---

node/pkg/dal/utils/stats/stats.go

allow free pass for health check on dal

---

util/.eslintrc
util/.gitignore
util/.prettierrc
util/jest.config.ts
util/package.json
util/src/errors.ts
util/src/index.ts
util/src/reducer.ts
util/src/types.ts
util/test/reducer.test.ts
util/tsconfig.json
yarn.lock

reducer codes were referenced from rr

Rollback utils

---

node/pkg/error/sentinel.go
node/pkg/websocketfetcher/app.go
node/pkg/websocketfetcher/providers/gopax/gopax.go
node/pkg/websocketfetcher/providers/gopax/type.go
node/pkg/websocketfetcher/providers/gopax/utils.go
node/pkg/wss/utils.go

Support Gopax as one of data provider

(OraklNode) Gopax support

---

README.md

(DOCS) Update readme

---

.github/workflows/deployment.yaml

Remove deprecated service from deployment.yaml

Remove aggregator and fetcher from deployment

---

sentinel/pkg/checker/health/baobab_healthcheck.json

(Sentinel)Update dal port for healthcheck

---

.github/workflows/node.test.yaml

update eth sepolia endpoint in node test workflow

---

node/pkg/dal/collector/utils.go
node/pkg/error/sentinel.go
node/pkg/websocketfetcher/providers/gopax/gopax.go

This is the Part 1 of multipart PR that separates reporter from node. The PR will be merged to its parent branch `feat/separate-reporter`, which in turn will get merged to `master` after all parts are merged. This PR:
- copies proof related functions from reporter to dal
- includes error checking in `gopax` implementation to pass lint
Related issue #1777 

[Separate Reporter Part 1] Copy proof functions from reporter to dal

---

node/pkg/dal/collector/utils.go

[separate reporter part 1 followup] make proof functions lowercase 

---

node/pkg/websocketfetcher/providers/huobi/huobi.go
node/pkg/websocketfetcher/providers/huobi/type.go

Subscription response handling, it will remove Huobi error on app start

(OraklNode) Handle Huobi websocket fetcher initial response

---

sentinel/pkg/checker/dal/app.go

- include network delay for checks
- add alarm offset which is 3, if fails more than 3 times in a row, it'll be alarmed

(Sentinel) Update sentinel dal api check conditions

---

node/pkg/aggregator/aggregator.go
node/pkg/zeropglog/app.go
node/pkg/zeropglog/types.go

Remove `MultiLevelWriter` and include `ConsoleWriter` inside `zeropglog`.
This PR is to fix following error constantly coming up
```
zerolog: could not write event: short write
```

(OraklNode) Remove `MultilevelWriter`

---

node/pkg/dal/api/controller.go

fix empty data return issue in dal multiple pair api

---

node/cmd/node/main.go
node/cmd/reporter/main.go
node/pkg/error/sentinel.go
node/pkg/reporter/app.go
node/pkg/reporter/app_test.go
node/pkg/reporter/main_test.go
node/pkg/reporter/reporter.go
node/pkg/reporter/reporter_test.go
node/pkg/reporter/types.go
node/pkg/reporter/utils.go
node/pkg/reporter/utils_test.go
node/taskfiles/taskfile.local.yml

This PR:
- deletes/comments out unnecessary code related to data processing in reporter and proofs
- temp comments out tests and deviation reporter
- implements initial logic for reporting using dal rest api
Part 3 will:
- replace dal rest api with websocket
- implement deviation reporter
- update tests
- refactor reporter into smaller functions
Related issue #1777

[Separate Reporter Part 2] base report logic with rest api

---

node/pkg/chain/helper/helper.go

increase timeout from 2s to 5s

(OraklNode) Increase delegator timeout from 2s->5s

---

node/pkg/dal/api/controller.go
node/pkg/dal/api/types.go

reference https://github.com/gorilla/websocket/issues/119

Potential fix for `concurrent write to websocket connection` panic

---

node/pkg/reporter/types.go
node/pkg/reporter/utils.go

[Separate Reporter Part 4] Clean up unused reporter utils

---

node/pkg/dal/api/controller.go

Fixes recent panic shutdown, tested through local env

(DAL) hotfix mutex implementation

---

.github/workflows/delegator.test+build.yaml
delegator/sign/controller.go
delegator/tests/sign_test.go
delegator/utils/utils.go

Update `insertV2` func referenced for tx sign from fee payer
- cache approved contract addresses
- update tx from defer func() after returning value
expected to reduce response time

(Delegator) delegator sign function optimization

---

node/pkg/chain/helper/helper.go
node/pkg/chain/helper/signer.go
node/pkg/chain/noncemanager/noncemanager.go
node/pkg/chain/tests/chain_test.go
node/pkg/chain/tests/noncemanager_test.go
node/pkg/chain/utils/types.go
node/pkg/chain/utils/utils.go
node/pkg/fetcher/accumulator_test.go
node/pkg/fetcher/main_test.go
node/pkg/por/app.go
node/pkg/reporter/reporter.go
node/script/test_dal_consumer/main.go
node/script/test_submission/main.go

Nonce manager pkg utilization
- concurrent tx submission test code is added

(OraklNode) nonce manager implementation

---

node/pkg/chain/helper/helper.go
node/pkg/chain/helper/signer.go
node/pkg/chain/helper/types.go
node/pkg/chain/noncemanager/noncemanager.go
node/pkg/chain/tests/chain_test.go
node/pkg/chain/tests/noncemanager_test.go
node/pkg/chain/utils/utils.go
node/pkg/fetcher/accumulator_test.go
node/pkg/fetcher/main_test.go
node/pkg/por/app.go
node/pkg/reporter/reporter.go
node/script/test_dal_consumer/main.go
node/script/test_submission/main.go

This feature is expected to be unnecessary after nonce manager implementation.
wallets db table removal will be added from follow up pr

(OraklNode) Remove multi-wallet implementation from chain helper

---

node/pkg/chain/helper/helper.go
node/pkg/chain/helper/signer.go
node/pkg/chain/helper/types.go
node/pkg/chain/noncemanager/noncemanager.go
node/pkg/chain/tests/chain_test.go
node/pkg/chain/tests/noncemanager_test.go
node/pkg/chain/utils/utils.go
node/pkg/fetcher/accumulator_test.go
node/pkg/fetcher/main_test.go
node/pkg/por/app.go
node/pkg/reporter/reporter.go
node/script/test_dal_consumer/main.go
node/script/test_submission/main.go

Basic nonce manager implementation with test code.
Will be building block for future implementation

(OraklNode) Nonce manager

---

contracts/v0.2/script/SubmissionProxy.s.sol
contracts/v0.2/src/SubmissionProxy.sol

based on the client request, strict submission is suggested, so that the submission can be validated after submission

(Contract) SubmissionProxy update

---

node/pkg/dal/api/controller.go
node/pkg/dal/collector/collector.go

Minor update, preallocate underlined memory for array

(DAL) Minor update

---

delegator/sign/controller.go

1. insert tx into db
2. validate tx
3. return signed tx
4. update tx in db (deferred func)
1. validate tx
2. return signed tx
3. insert signed tx in db (deferred func)

(Delegator) Update delegator logic

---

node/pkg/chain/helper/helper.go
node/pkg/chain/helper/signer.go
node/pkg/chain/helper/types.go
node/pkg/chain/tests/chain_test.go
node/pkg/chain/utils/utils.go
node/pkg/por/app.go
node/pkg/reporter/reporter.go
node/script/test_dal_consumer/main.go
node/script/test_submission/main.go

Add general submit func `SubmitDelegatedFallbackDirect` 
it will take care of nonce, client, delegator call

(OraklNode) Add general submit func

---

delegator/sign/controller.go

add missing pgs query parameter

(Delegator) Fix grafana not visualizing successful tx

---

node/pkg/dal/collector/collector.go
node/pkg/dal/common/types.go
node/script/test_dal_consumer/main.go

Return hexstring instead of [32]byte

(DAL) Change feedhash type

---

node/pkg/dal/api/types.go
node/pkg/dal/collector/collector.go
node/pkg/dal/collector/utils.go
node/pkg/dal/common/types.go
node/script/test_dal_consumer/main.go

```
[
{
"symbol": "BTC-USDT",
"value": "6427382496254",
"aggregateTime": "1721886508",
"proof": "0x518f1cbb5e9f4718357df1acc45c9e5f7bfec62be8263940cc108be966955dd8112bff89ff8e42f1760163ae8b09c02fb53bb3a1c3466e4e62e2ddd3a46defcc1b",
"feedHash": "0xa92bcb5bc51aa5535ed0cc3f522992dd9a6fb2e8dd6dcf484705d93eb3cd167a",
"decimals": "8"
}
]
```
please refer to consumer code update for right conversion

Return hexstring for bytes types

---

.github/workflows/node.test.yaml

add dal api key to node test env

---

.github/workflows/node.test.yaml

add dal ws endpoint to node workflow

---

node/pkg/reporter/app.go
node/pkg/reporter/app_test.go
node/pkg/reporter/main_test.go
node/pkg/reporter/reporter_test.go
node/pkg/reporter/types.go
node/taskfiles/taskfile.local.yml

fetch configs instead of querying from db
Related issue #1777 

fetch configs in reporter

---

node/pkg/fetcher/app.go
node/pkg/websocketfetcher/app.go

Update pre-jobs' interval before global aggregate

(OraklNode) Update intervals

---

.github/workflows/deployment.yaml
dockerfiles/orakl-reporter.Dockerfile

reporter dockerfile and deployment workflow

---

node/cmd/reporter/main.go

remove db dependency from reporter

---

node/pkg/reporter/app.go

(Reporter) Remove additional provider url usage

---

sentinel/pkg/checker/health/baobab_healthcheck.json
sentinel/pkg/checker/health/cypress_healthcheck.json

Will be merged after reporter service is live on baobab and cypress

health check for reporter service

---

sentinel/pkg/checker/balance/app.go
sentinel/pkg/checker/balance/app_test.go

remove admin wallet endpoint from sentinel

---

sentinel/pkg/checker/health/baobab_healthcheck.json
sentinel/pkg/checker/health/cypress_healthcheck.json

fix reporter endpoint

---

sentinel/pkg/checker/dal/app.go

(Sentinel) Update sentinel with new dal response format

---

node/pkg/dal/api/hub.go

unless manually deleting nested map entries, memory won't be fully released until golang garbage collector removes it

(DAL) Delete also subscription on unregister

---

node/pkg/dal/api/controller.go

CloseHandler is triggered when the server receives close msg from the client
It overwrites default closeHandler to ensure release of memory

(DAL) Close handler

---

node/pkg/dal/api/hub.go

(DAL) Hotfix add missing threading

---

node/pkg/chain/tests/cachedabi_test.go
node/pkg/chain/utils/abicached.go
node/pkg/chain/utils/cachedabi.go
node/pkg/chain/utils/utils.go
node/pkg/error/sentinel.go

Minor update for chain helper to cache abi in memory

(OraklNode) Cache abi

---

node/pkg/dal/api/hub.go

(DAL) Quick return from client handling if condition not met

---

node/pkg/dal/collector/collector.go

log timestamps for pairs in dal collector

---

node/pkg/dal/collector/collector.go

udpate dal collector info logs to warn

---

node/pkg/fetcher/accumulator.go
node/pkg/fetcher/collector.go
node/pkg/fetcher/utils.go

(OraklNode) Remove bulk rdb insertion, will be rollbacked if not effective

---

node/pkg/fetcher/accumulator.go
node/pkg/fetcher/collector.go
node/pkg/fetcher/utils.go

This reverts commit f01799b1cdb836faeb20fca1d58d2c991aaea0c2.

Revert "fix: will be rollbacked if not effective (#1947)"

---

node/pkg/aggregator/aggregator.go

(OraklNode) Experiment, remove cleanup (experiment)

---

node/pkg/aggregator/utils.go
node/pkg/fetcher/accumulator.go
node/pkg/websocketfetcher/providers/gopax/gopax.go

measure accumulatorJob execution time

---

node/cmd/node/main.go
node/pkg/aggregator/aggregator.go
node/pkg/aggregator/aggregator_test.go
node/pkg/aggregator/app.go
node/pkg/aggregator/main_test.go
node/pkg/aggregator/streamer_test.go
node/pkg/aggregator/types.go
node/pkg/bus/types.go
node/pkg/fetcher/accumulator.go
node/pkg/fetcher/accumulator_test.go
node/pkg/fetcher/app.go
node/pkg/fetcher/app_test.go
node/pkg/fetcher/collector.go
node/pkg/fetcher/main_test.go
node/pkg/fetcher/types.go

Use message bus instead of redis get set for latest local aggregate

(OraklNode) Use message bus for localAggregates

---

node/pkg/aggregator/aggregator.go

(OraklNode) Remove time validation

---

node/pkg/aggregator/utils.go

(OraklNode) add aggregator logs

---

node/pkg/dal/collector/collector.go

(DAL) Print log

---

node/pkg/dal/collector/collector.go

(DAL) Update buffer

---

node/pkg/aggregator/types.go
node/pkg/aggregator/utils.go
node/pkg/dal/collector/collector.go

temporary update to log pubsub latency for global aggregate and proof

(OraklNode) log redis latency

---

node/script/test_dal_consumer/main.go

(OraklNode) Update dal consumer script

---

node/pkg/reporter/reporter.go

(Reporter) add delay log

---

node/pkg/reporter/reporter.go

(Reporter) add delayed submission log

---

node/pkg/reporter/reporter.go

(Reporter) Thread submission from reporter

---

node/pkg/reporter/reporter.go

(Reporter) wg update

---

node/pkg/dal/collector/collector.go

update redis delay log

---

node/pkg/reporter/reporter.go
node/pkg/reporter/types.go
node/pkg/reporter/utils.go
node/script/test_dal_consumer/main.go

(Reporter) Rest reporter

---

node/pkg/websocketfetcher/providers/gopax/gopax.go

Gopax error log skip on unlisted price pair

(OraklNode) Prevent unnecessary error log

---

sentinel/cmd/main.go
sentinel/pkg/checker/dal/app.go
sentinel/pkg/checker/dal/app_test.go
sentinel/pkg/retrier/retrier.go
sentinel/pkg/ws/ws.go
sentinel/taskfile.yml

Store delayed returns from dal api websocket sends slack alarm if delayed over 5 seconds
- delay check: check if each pushed data is fresh
- push check: check if last pushed data is pushed within 1 second

(Sentinel) DAL ws checker

---

sentinel/go.mod
sentinel/go.sum

fix: go mod tidy

---

node/pkg/chain/helper/helper.go
node/pkg/chain/utils/utils.go

(OraklNode) Handle nonce error

---

node/pkg/aggregator/app.go
node/pkg/fetcher/app.go

(OraklNode) Faster app launch, reduce sleepage

---

node/pkg/chain/utils/utils.go

(OraklNode) error is not being catched by blockChain err objects

---

sentinel/pkg/checker/dal/app.go

(Sentinel) Update threshold to reduce message

---

sentinel/pkg/checker/dal/app.go

Based on client feedback, it seems to be working as expected for now
Will be reducing threshold, and keep updating more optimization PRs

(Sentinel) Change threshold to reduce alarm

---

node/pkg/dal/api/controller.go
node/pkg/dal/api/hub.go
node/pkg/dal/api/types.go
node/pkg/dal/collector/collector.go

- Check data freshness before post processing
- Use mutex instead of syncmap from dal

(DAL) check data freshness before updates, use mutex

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/app.go
node/pkg/aggregator/main_test.go
node/pkg/aggregator/types.go

the map involving multiple writes are recommended to use mutex

(OraklNode) Mutex lock instead of syncmap for local aggregate

---

sentinel/pkg/checker/dal/app.go

update to mutex for its use case

(DAL) remove sync.map from dal checker

---

node/pkg/dal/collector/collector.go

(DAL) dal logs for debugging

---

node/pkg/dal/api/controller.go

update for atomic function execution

(DAL) Prevent possible race condition

---

node/pkg/dal/api/controller.go
node/pkg/dal/api/hub.go

prevent race conditions to avoid deadlocks

(DAL) Fix ws deadlock

---

sentinel/pkg/checker/dal/app.go
sentinel/pkg/checker/dal/app_test.go

Now only interested in persisting errors 

(Sentinel) Alarm count offset for ws data

---

sentinel/pkg/checker/dal/app.go

(Sentinel) Initialize count if it passes

---

node/pkg/dal/api/controller.go

Tested through local environment 

(DAL) definite unlock through deferred func

---

node/script/test_dal_consumer_ws/main.go
node/taskfiles/taskfile.local.yml

subscribe and read ws results 

(DAL) WS consumer script for easy testing and logging

---

node/pkg/dal/api/controller.go
node/pkg/dal/api/hub.go
node/pkg/dal/api/types.go
node/pkg/dal/tests/api_test.go
node/pkg/wss/utils.go

Limit websocket connection maximum by 10

(DAL) IP limit

---

node/pkg/raft/raft_test.go
node/taskfiles/taskfile.local.yml

Implement missing raft test code

(OraklNode) Add missing raft test codes

---

sentinel/pkg/checker/dal/app.go
sentinel/pkg/checker/dal/app_test.go

(Sentinel) Chore, cleanup dal checker codes

---

node/pkg/aggregator/aggregator.go
node/pkg/raft/raft.go

prevent potential blocked channel

(OraklNode) Increase aggregator message buffer size

---

node/pkg/raft/accessors.go
node/pkg/raft/raft.go

`go r.handleMessage(ctx, msg)`
remove thread safe getter codes.
instead, handle mutex in each functions

(OraklNode) improve raft mutex & implement concurrent msg read

---

node/cmd/admin/main.go
node/cmd/fetcher/main.go
node/cmd/node/main.go
node/pkg/admin/admin.go
node/pkg/admin/tests/main_test.go
node/pkg/admin/utils/utils.go
node/pkg/aggregator/main_test.go
node/pkg/fetcher/main_test.go
node/script/test_fetcher/main.go
node/script/test_fetcher_and_aggregator/main.go

use passed ctx from admin setup

(OraklNode) Chore, use passed ctx from admin

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/streamer.go
node/pkg/aggregator/utils.go
node/pkg/db/redis.go
node/pkg/raft/raft.go

- remove cleanup code from aggregator since it is now no more necessary
- update aggregator streamer select loop into blocked operation since it's been regularly triggered by tickers
- etc

(OraklNode) Chore, minor code updates

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/aggregator_test.go
node/pkg/raft/raft.go
node/pkg/raft/raft_test.go
node/pkg/raft/types.go
node/script/test_raft/main.go

use passed ctx instead of context.Background() from msg publish

(OraklNode) Chore, use passed ctx from raft msg publish

---

contracts/v0.2/src/SubmissionProxy.sol
contracts/v0.2/test/SubmissionProxy.t.sol

convert unixmilli into unix before time comparison

(Contract) timestamp compare logic updates for unixmilli

---

node/pkg/chain/helper/signer.go
node/pkg/chain/tests/chain_test.go
node/pkg/dal/collector/collector.go
node/pkg/dal/collector/utils.go

(OraklNode) Offchain Proof and Timestamp based on unixmilli

---

.github/workflows/node.test.yaml

https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths

(Chore) Set ignore path for separate github action tests

---

.github/workflows/node.test.yaml

exclude logscribe migrations from node workflow

---

node/pkg/error/sentinel.go
node/pkg/logscribe/utils/utils.go

fix logscribe db not found error log

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/types.go
node/pkg/chain/tests/chain_test.go
node/pkg/dal/collector/utils.go
node/pkg/error/sentinel.go

- update access logic to aggregator prices and proofs map
- add more testcodes related to proof packing and unpacking
- add more logs to debug invalid proof issue

(OraklNode) Minor updates, add empty proof filter

---

node/pkg/dal/collector/utils.go

Update log to specify wrong signer

(DAL) update log

---

node/pkg/raft/raft.go
node/pkg/raft/raft_test.go
node/pkg/raft/types.go

prevent possible message replay

(OraklNode) Msg replay prevention from raft pkg

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/types.go

Prevent possible race condition

(OraklNode) Mutex lock roundID

---

node/pkg/admin/aggregator/controller.go
node/pkg/admin/aggregator/route.go
node/pkg/admin/tests/aggregator_test.go
node/taskfiles/taskfile.local.yml

update go task command and aggregator endpoint to get current signer public address

(OraklNode) add endpoint and task command

---

node/pkg/admin/aggregator/controller.go

(OraklNode) Admin, add fallback to get signer from env if not exists in db

---

node/pkg/raft/types.go

Remove unused codes, previously used for raft message replay prevention

(OraklNode) Chore, remove unused codes

---

node/pkg/aggregator/aggregator.go

leaderJob is only called from leader node yet cleanup was placed in leaderJob leading to memory leak

(OraklNode) Fix memory leak

---

node/script/test_dal_consumer_ws/main.go

update timestamp parsing logic into unixmilli

(OraklNode) Fix script for unixmilli

---

node/cmd/dal/main.go

(DAL) Set log lv from env

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/types.go

Possible fix for non-whitelisted signer error

(OraklNode) Add step to fix global aggregate

---

node/pkg/aggregator/aggregator.go
node/pkg/raft/raft.go

(OraklNode) Possible fix for memory leak

---

node/pkg/aggregator/aggregator.go

(OraklNode) Don't increase raft term from aggregator, add cleanup on publishing result

---

node/pkg/aggregator/aggregator.go

Rollback threading to reduce unnecessary threading

(OraklNode) remove unnecessary threading

---

node/pkg/raft/raft.go
node/pkg/raft/types.go

- take raw *pubsub.Message from message buffer
- include unmarshaling on reading message buffer
- simplify handle heartbeat func
- increase election timeout

(OraklNode) Improve message handling concurrency, simplify handle heartbeat

---

node/pkg/fetcher/accumulator.go
node/pkg/fetcher/collector.go

(Chore) Remove logs

---

node/pkg/libp2p/setup/setup.go

(OraklNode) Ignore libp2p error if self dial attempted

---

node/pkg/libp2p/setup/setup.go

(OraklNode) hotfix segmentation error

---

node/pkg/logscribeconsumer/app.go

provide default endpoint for logscribe

---

.github/workflows/logscribe.test.yaml
node/pkg/logscribeconsumer/app.go
node/pkg/logscribeconsumer/types.go

separate console and logscribe log levels

---

node/migrations/node/000031_zerologs.down.sql
node/migrations/node/000031_zerologs.up.sql

zerolog remove table up and down migration files

---

node/pkg/checker/dal/app.go
node/pkg/checker/dal/app_test.go

(Sentinel) update dal timestamp check based on millisec

---

node/pkg/websocketfetcher/providers/lbank/lbank.go
node/pkg/wss/utils.go

- ignore zerologging if it is normal closure from the host
- add logic to check if error is due to normal closure

(OraklNode) Fix lbank error

---

node/pkg/aggregator/aggregator.go
node/pkg/raft/raft.go
node/pkg/raft/raft_test.go

- increase roundID on start of `getTriggerMessage`
- enhance raft `handleRequestVote` for better readability & edge case handling
- increase election timeout for less leader re-election

(OraklNode) minor logic updates in Aggregator & Raft

---

node/pkg/dal/collector/collector.go
node/pkg/db/rediscribe.go
node/pkg/db/rediscribe_test.go

Integrate rediscribe into DAL.
Prepared for additional redis db subscription

(DAL) Rediscribe integration

---

node/pkg/aggregator/main_test.go
node/pkg/common/keys/keys.go
node/pkg/fetcher/main_test.go
node/pkg/fetcher/utils.go
node/pkg/fetcher/utils_test.go

(OraklNode) Chore, remove unused redis keys

---

node/pkg/db/pgsql.go

Will be later utilized from Sentinel

(OraklNode) Add functionality for transient db connection support

---

.github/workflows/node.test.yaml
node/cmd/sentinel/main.go
node/pkg/checker/health/app.go
node/pkg/checker/health/app_test.go

will ping pgsql every 10 seconds to check its liveness
pgsql connection url is loaded from vault secret rather than json file

(Sentinel) pgsql checker

---

node/pkg/checker/balance/app.go
node/pkg/checker/balance/types.go

Tracks wallet balance drainage.
checks drainage every 30 sec, if usage increased more than 5% will send slack message

(Sentinel) Track wallet balance drainage

---

node/pkg/fetcher/app.go
node/pkg/fetcher/feeddatabulkwriter.go
node/pkg/fetcher/fetcher.go
node/pkg/fetcher/fetcher_test.go
node/pkg/fetcher/types.go
node/pkg/fetcher/utils.go
node/pkg/fetcher/utils_test.go
node/pkg/websocketfetcher/app.go
node/pkg/websocketfetcher/common/utils.go
node/pkg/websocketfetcher/tests/utils_test.go

Replace redis list into in memory channel

(OraklNode) Replace feed data buffer redis list to in memory channel

---

node/pkg/checker/dbcronjob/app.go

(Sentinel) add missing for loop

---

node/pkg/db/pgsql.go
node/pkg/db/pgsql_test.go

update memory release and error handling from db package

(OraklNode) Potential fix for memory leak on db failure

---

node/pkg/checker/dbcronjob/app.go

Add missing query condition `status = 'failed'`

(Sentinel) Add missing status condition

---

node/pkg/checker/dalstats/app.go

Remove unnecessary condition from sql query

(Sentinel) query condition update

---

node/pkg/checker/event/app.go

Update message so that it is more easy to tell from DAL checks

(Sentinel) Update message

---

node/pkg/aggregator/aggregator.go

Rollback Term increase from aggregator leaderjob

(HOTFIX) Hotfix sync error

---

node/pkg/chain/helper/helper.go
node/pkg/chain/tests/chain_test.go

Simple single direct tx generation func to be used from sentinel

(OraklNode) Update for single direct tx

---

node/pkg/logscribe/logprocessor/logprocessor.go

(Logscribe) Increase bulk copy interval

---

node/cmd/sentinel/main.go
node/pkg/chain/helper/helper.go
node/pkg/chain/tests/chain_test.go
node/pkg/checker/inspect/app.go
node/script/inspector/main.go
node/taskfiles/taskfile.local.yml

Runs inspector at UTC 00:00 (KST 09:00) every day and sends result through slack
Can be run in local with following env variables,
And includes minor chainHelper updates to be used from inspector
```
KAIA_WEBSOCKET_URL=
INSPECTOR_PK=
ACC_ID=
VRF_KEYHASH=
INSPECT_CONSUMER_ADDRESS=
```
go task command is as followed
```
task local:script-inspector
```

(Sentinel) Sentinel auto inspector

---

node/cmd/sentinel/main.go

Possible cause for db cpu increase, will check after deployment

(Sentinel) Disable offset checker

---

node/pkg/checker/balance/app.go

Will be updated later with different logic

(Sentinel) Disable drainage check to reduce spamming

---

node/migrations/dal/000006_timestamp_index.down.sql
node/migrations/dal/000006_timestamp_index.up.sql
node/migrations/node/000032_add_missing_index.down.sql
node/migrations/node/000032_add_missing_index.up.sql
node/pkg/checker/dalstats/app.go

Add index to reduce cpu stress

Update dalstats checker query & add migrations

---

node/pkg/websocketfetcher/providers/crypto/types.go

Update crypto.com websocket endpoint

(OraklNode) Update crypto.com endpoint

---

node/pkg/websocketfetcher/providers/xt/type.go

(OraklNode) fix wrong quantity from xt cex

---

node/pkg/fetcher/localaggregator.go
node/pkg/fetcher/types.go

Add filtering logic that removes outliers from raw data source
if price difference between median value is over 50%, the value will not be considered on aggregation

(OraklNode) Filter outliers from raw feed data

---

node/pkg/delegator/utils/utils.go

all errors will be handled from fiber custom error handler

(Delegator) delegator zerologs

---

node/pkg/api/utils/utils.go

error caught from fiber will be all logged from zerolog

(API) zerologging from error handler

---

contracts/v0.1/src/libraries/ecc/EllipticCurve.sol

chore: update EllipticCurve.sol

---

node/cmd/sentinel/main.go

(Sentinel) Disable DAL checks

---

node/pkg/checker/balance/app.go
node/pkg/checker/balance/types.go

Update logic to compare based on 10 minutes changes rather than 1 min

(Sentinel) drainage check based on 10 minutes changes

---

node/pkg/db/pgsql.go

db querying will be canceled with basic timeout 10 sec

(OraklNode) Implement db query timeout

---

node/pkg/db/pgsql.go

This reverts commit f10ee33d1c42b9b1cfec6a0213b7a4756f66ad06.

Revert "feat: implement db query timeout (#2167)"

---

node/go.mod
node/go.sum
node/pkg/fetcher/localaggregator.go
node/pkg/fetcher/types.go

(OraklNode) Improve outlier removal logic

---

node/pkg/checker/event/app.go

Since we have a client submitting themselves, this is no more accurate alert

(Sentinel) Remove too many submissions check

---

node/migrations/node/000033_feed_data_index.down.sql
node/migrations/node/000033_feed_data_index.up.sql
node/migrations/node/000034_feeds_index.down.sql
node/migrations/node/000034_feeds_index.up.sql

(OraklNode) Add missing index

---

node/pkg/db/pgsql.go
node/pkg/db/pgsql_test.go

pgsql call timeouts after 15 seconds

(OraklNode) Set general DB timeout

---

node/pkg/db/pgsql.go
node/pkg/db/pgsql_test.go

(OraklNode) Increase db timeout for production

---

.github/workflows/update.image-tag.yaml

remove old tags for helm chart [CICD]

---

node/pkg/checker/dal/app.go
node/pkg/checker/dal/types.go

AS-IS
send alert if rest call exceeds certain amount of calls
TO-BE
send alert if last 10 seconds call count exceeds last 10 minutes call count

(Sentinel) update dal rest traffic checker logic

---

node/pkg/checker/signer/app.go

(Sentinel) Change unnecessary error log level

---

node/pkg/aggregator/app.go
node/pkg/aggregator/app_test.go
node/pkg/error/sentinel.go
node/pkg/utils/condition/condition.go
node/pkg/utils/tests/condition_test.go

start aggregator if condition is met where the local aggregate data is ready

(OraklNode) Wait aggregator start until data is ready

---

node/pkg/utils/retrier/retrier.go

error from retrier will be logged from higher level

(OraklNode) Remove log from retrier 

---

node/pkg/checker/health/app.go

These logs are part of expected behavior, leading to slack alerts, will lower the level

(Sentinel) update log level from healthcheck

---

node/pkg/db/rediscribe.go

Instead of reconnecting with certain errors, this update will make it try to reconnect redis pubsub whenever an error occurs

(DAL) Remove conditional reconnect

---

.github/workflows/node.test.yaml
.github/workflows/raft.test.yaml
node/pkg/raft/raft.go
node/pkg/raft/raft_test.go
node/pkg/raft/types.go

tolerate maximum 2 missed heartbeat before election start
if election has been done within 3 seconds, skip election
leader definitely takes larger term than followers or candidates, making it fixed in more robust way
remove from node since it contains lots of sleeps and require some time to run

(OraklNode) Update raft logic

---

node/pkg/checker/dalstats/app.go

(Hotfix) fix cronjob definition

---

node/cmd/node/main.go
node/pkg/checker/ping/app.go

working smoothly in local environment, not in production, adding logs to investigate deeper

(OraklNode) Pinger, add logs, increase launch sleep time

---

dockerfiles/orakl-node.Dockerfile
node/pkg/checker/ping/app.go

second method written in docs
https://github.com/prometheus-community/pro-bing?tab=readme-ov-file#linux

(OraklNode) attempt to enable ICMP pinging

---

node/pkg/websocketfetcher/app.go

This reverts commit 8b9bb7a25f9a43377051864490501e83b399b885.

Revert "feat: implement proxy for websocket fetchers (#2206)"

---

node/pkg/checker/ping/app.go

(OraklNode) Reduce pinger success log level

---

node/pkg/checker/inspect/app.go

(Sentinel) Add missing cron job start trigger

---

node/pkg/aggregator/aggregator.go
node/pkg/aggregator/app.go

Remove aggregator wait on start

(OraklNode) Remove aggregator wait

---

node/pkg/db/redis.go

Add condition for redis reconnection, 
possible fix for
https://github.com/Bisonai/orakl/issues/2183

(OraklNode) Add condition for redis reconnection

---

node/pkg/chain/websocketchainreader/websocketreader.go

Rollback block subscription.
Will be observed for a while after deployment

(OraklNode) Fix possible cause for memory leak, rollback block subscription

---

.github/workflows/deployment.yaml

(CI/CD) Fix pipeline slack channel id

---

node/pkg/raft/raft.go

handle edge case where there are two same leader with the same term.
step down based on leader id comparison

(Node) Update same term handling

---

node/pkg/chain/helper/signer.go
node/pkg/fetcher/utils.go

- add a bit more detail to empty feed data log
- run signer renewal at the beginning of the app
> will check the expiration and renew if required

(Node) Update log, change signer renewal logic

---

inspector/scripts/json-rpc-sync-check.sh

Update ip addr

---

node/pkg/websocketfetcher/app.go
node/pkg/websocketfetcher/providers/orangex/orangex.go
node/pkg/wss/utils.go

Support OrangeX exchange websocket ticker fetching
reference
https://openapi-docs.orangex.com/#ticker-instrument_name-interval

(Node) Support orangex

---

node/pkg/admin/config/controller.go

(Node) Check conflict not only with name but also configid

---

node/migrations/node/000035_update_feed_contraint.down.sql
node/migrations/node/000035_update_feed_contraint.up.sql

(Node) Update contraint for feeds table

---

node/pkg/reporter/reporter.go

refresh nonce also on context deadline exceed error

(Reporter) Refresh nonce on context deadline exceed

---

node/pkg/reporter/reporter.go

(Reporter) log on reporter error

---

node/pkg/reporter/reporter.go

fix unintended quick err return

[Reporter] Fix refresh nonce not being taken

---

node/pkg/dal/collector/collector.go
node/pkg/dal/collector/utils.go

[DAL] Hotfix addr comparison

---

node/pkg/websocketfetcher/providers/upbit/type.go

Remove upbit ticker dd property which lead to error

---

node/pkg/checker/offset/app.go

[Health] add missing skips

---

node/pkg/reporter/utils.go

use endpoint that returns available pairs instead of returning fail

(Reporter) use unstrict endpoint

---

node/cmd/sentinel/main.go
node/pkg/checker/subgraphcleaner/app.go

Subgraph cleaner to remove old feed contract historical data 

Subgraph cleaner

---

node/pkg/checker/subgraphcleaner/app.go

hotfix schema replacement

---

node/pkg/checker/subgraphcleaner/app.go

Reduce delays

---

node/pkg/dal/collector/collector.go
node/pkg/websocketfetcher/common/utils.go

Multiply decimals twice if value is too small

---

node/taskfiles/taskfile.local.yml
supervisor/boot-api.conf

Supervisord files for boot-api

Add supervisord settings

---

node/pkg/dal/collector/utils.go

Remove spamming log

---

node/pkg/dal/collector/collector.go

Reduce dal whitelist check interval (5sec -> 10sec)

---

node/pkg/chain/helper/helper.go
node/pkg/websocketfetcher/app.go

Use secrets for json rpc url

---

node/pkg/checker/health/cypress_healthcheck.json

Update orakl dal endpoint for healthcheck

---

node/pkg/dal/apiv2/controller.go
node/pkg/dal/utils/stats/stats.go

Chore, Dal log update

---

node/pkg/dal/apiv2/controller.go

strict route checks for health

Chore, Dal healthcheck handler

---

node/pkg/checker/health/cypress_healthcheck.json

Update boot api health endpoint

---

node/pkg/checker/health/cypress_healthcheck.json

Chore, fix boot api endpoint for healthcheck

---

node/pkg/dal/collector/utils.go

less restrictive comparison
possible fix for recent dal error

Update whitelist comparison logic

---

.github/workflows/deployment.yaml

chore: rollback new image deploy option

---

node/pkg/dal/collector/collector.go
node/pkg/dal/collector/utils.go

- trimspace before comparison
- deepcopy whitelist for comparison

potential fix for non-whitelisted error

---

node/migrations/dal/000007_update_rest_calls_id.down.sql
node/migrations/dal/000007_update_rest_calls_id.up.sql

rest calls exceeding the max int4 value, updating for compatibility

update table column

---

node/migrations/dal/000007_update_rest_calls_id.down.sql
node/migrations/dal/000007_update_rest_calls_id.up.sql

This reverts commit 830517160da5ea4773c314600ee8838d226b73e7.

Revert "feat: update table column (#2414)"

---

node/pkg/dal/utils/stats/stats.go

fix, remove unexpected large value from rest_calls table

---

node/pkg/websocketfetcher/providers/btse/btse.go
node/pkg/websocketfetcher/providers/gemini/gemini.go
node/pkg/websocketfetcher/providers/gemini/utils.go

fix minor errors, reduce log spamming

---

node/k6/dal-k6.js

(DAL) k6 testing

---

.github/workflows/api.test.yaml
.github/workflows/boot-api.test.yaml
.github/workflows/cli.test.yaml
.github/workflows/dal.test.yaml
.github/workflows/delegator.test.yaml
.github/workflows/deployment.yaml
.github/workflows/node.test.yaml
.github/workflows/raft.test.yaml
.github/workflows/reporter.test.yaml
.github/workflows/sentinel.test.yaml
dockerfiles/miko-api.Dockerfile
dockerfiles/miko-boot-api.Dockerfile
dockerfiles/miko-dal.Dockerfile
dockerfiles/miko-delegator.Dockerfile
dockerfiles/miko-node.Dockerfile
dockerfiles/miko-por.Dockerfile
dockerfiles/miko-reporter.Dockerfile
dockerfiles/miko-sentinel.Dockerfile

Update missing go versions

---

contracts/v0.2/addresses/datafeeds-addresses.json
contracts/v0.2/addresses/others-addresses.json
contracts/v0.2/script/collect-addresses.cjs

if # of price source is 1, return `single` tag

Add `single` group

---

node/pkg/bus/bus.go

concurrent map access prevention

---

node/pkg/checker/ping/app.go

dns ping checker refactoring

---

node/pkg/fetcher/localaggregator.go

ex. if there are 5 price providers, local aggregation is done only when there are prices more than 3 different providers

Set 50% threshold for local aggregation

---

contracts/v0.2/addresses/datafeeds-addresses.json

chore: collect addr

---

node/pkg/raft/raft.go
node/pkg/raft/types.go

- ~~less strict raft timeouts~~
- trigger leader job and heartbeat msg right after being elected

Chore, minor raft update

---

contracts/v0.2/addresses/datafeeds-addresses.json

Fix pair tag

---

node/pkg/utils/arr/arr.go
node/pkg/websocketfetcher/providers/gateio/gateio.go

Split gateio subscription payloads

---

node/pkg/websocketfetcher/providers/gateio/gateio.go
node/script/test_websocketFetcher/main.go

chore: reduce

---

node/pkg/websocketfetcher/app.go
node/pkg/websocketfetcher/common/type.go
node/pkg/websocketfetcher/providers/gateio/gateiov3.go

Use gateio v3 endpoint

---

node/cmd/por/main.go
node/pkg/por/app.go
node/pkg/por/por_test.go
node/pkg/por/types.go

Refactor por to support multiple jobs

---

node/pkg/utils/reducer/reducer.go

Chore, update reduce logic to handle different types

---

node/pkg/por/app.go

Fix, rollback set default val

---

contracts/v0.2/addresses/baobab/Feed_BORA-USDT.json
contracts/v0.2/addresses/cypress/Feed_BORA-USDT.json
contracts/v0.2/addresses/datafeeds-addresses.json

Remove deprecated pair

---

node/pkg/checker/price/app.go

Update price drift threshold

---

node/pkg/checker/price/app.go
node/pkg/checker/price/types.go

Price checker update

---

node/pkg/checker/price/app.go

price chcker, update message

---

node/pkg/por/app.go

Hotfix por retry condition

---

node/pkg/checker/offset/app.go

Offchain offset alert

---

node/pkg/checker/event/app.go
node/pkg/checker/event/types.go

Onchain offset alert

---

node/pkg/websocketfetcher/common/type.go
node/pkg/websocketfetcher/providers/bitstamp/utils.go
node/pkg/websocketfetcher/providers/btse/utils.go
node/pkg/websocketfetcher/providers/gemini/utils.go

Hotfix, concurrent map access failure prevention
