- core/src/reporter/aggregator.ts
- core/src/types.ts
- core/src/worker/aggregator.ts
When data feed operated by a single node operator is rebooted, fixed heartbeat is not relaunched and unless the latest data deviates enough from the latest submission (operated by random heartbeat), then the aggregator does not enter the healthy lifecycle.
This PR pushes a fixed heartbeat job to designated queue and restarts the process of collecting and submitting the latest values to aggregator smart contract. 
* Avoid using magic constant delay set in reporter for fixed delay queue
> Wake up single-node Data Feed reporters

- core/package.json
- core/src/utils.ts
Slack alarm call with unlimited time of interval issue.
This adds a feature of interval 1 min to send slack alarm notifications.
If the error message is different, it sends without an interval period.
> fixed slack interval and new error msg

- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/src/v0.1/VRFCoordinator.sol
Add new event to the constructor of `VRFCoordinator ` && `RequestResponseCoordinator `
Deployed to `Baobab` to test if the events working from constructor creation. Here is the [tx link](https://baobab.scope.klaytn.com/tx/0xfbaa17d3bd77be145cfcc340c0e295fa6afba23f14d644e7671cf0e6936fe68e?tabId=eventLog). 
-  As you can see from the event logs, `prepayment address` set to `016FB0D0D75997DB1EBc4422567F6dBab3Cb540D`
- https://baobab.scope.klaytn.com/tx/0x5b71c9e78c8c250b56f966c4f4c81372c09437535cc26880304f24600af30a19?tabId=eventLog
- https://baobab.scope.klaytn.com/tx/0xfbaa17d3bd77be145cfcc340c0e295fa6afba23f14d644e7671cf0e6936fe68e?tabId=eventLog
> Emit event when connecting prepayment with `VRFCoordinator` || `RequestResponseCoordinator`

- .github/workflows/api.test+build.yaml
- .github/workflows/cli.build+publish.yaml
- .github/workflows/contracts.publish.yaml
- .github/workflows/contracts.test.yaml
- .github/workflows/core.test+build.yaml
- .github/workflows/request-response.integration.test.yaml
This PR blocks the execution of GitHub actions pipeline after merging to master. Previously, certain actions have unnecessarily been executed.
> Don't run actions after merging to master

- core/adapter/btc-usdt.adapter.json
This PR is for fix naming in `BTC-USDT` adapter.
> Fix feed name from `BTC-USDT` adapter

- .github/workflows/api.test+build.yaml
- .github/workflows/cli.build+publish.yaml
- .github/workflows/contracts.publish.yaml
- .github/workflows/contracts.test.yaml
- .github/workflows/core.test+build.yaml
- .github/workflows/delegator.test+build.yaml
- .github/workflows/request-response.integration.test.yaml
- .github/workflows/vrf.build+publish.yaml
- .github/workflows/vrf.integration.test.yaml
Some tests have a hanging issues and keep running unreasonably long. This PR limits all GitHub actions to 3 minute timout.
> Add `timeout-minutes: 3` for every github actions pipeline

- contracts/src/v0.1/VRFCoordinator.sol
- [1] Cache length of s_provingKeyHashes array to memory before running for loop.
- [2] Default value of uint type is 0 so we don't need to assign it value to 0 again. 
- [3] Proving key hashes will be pushed by only contract owner so it can't be overflow 256 bit. So we can add ++i inside unchecked keyword
> Optimize gas fee

- .github/workflows/api.image+upload.yaml
- .github/workflows/cli.image+upload.yaml
- .github/workflows/core.image+upload.yaml
- .github/workflows/fetcher.image+upload.yaml
- api/docker-compose.build.yaml
- cli/docker-compose.build.yaml
- core/docker-compose.build.yaml
- fetcher/docker-compose.build.yaml
This pull request (PR) is about migrating the repository from Docker Hub to AWS ECR. The reason for this change is that Docker Hub has a limitation for upload after a certain megabyte or call, which slows down the upload speed significantly. Therefore, I decided to migrate the repository to AWS ECR.
To connect to AWS ECR, I do not store any AWS secrets on Git-Action-Secrets. Instead, I use AWS web-identity to log in to ECR.
I have made the repository in ECR public for now. However, I plan to write a description about the organization later.
This PR is only triggered when you merge into the 'Master' branch containing each service changed. After merging, this will create using docker-compose in 'src/'. These images will then be pushed to ECR.
> Migrate docker-hub to ECR using git-action

- api/prisma/migrations/20230328063843_aggregator_on_delete_cascade/migration.sql
- api/prisma/schema.prisma
- api/src/adapter/adapter.service.ts
- api/src/aggregator/aggregator.controller.ts
- api/src/aggregator/aggregator.service.ts
- cli/package.json
- cli/src/index.ts
Thi PR update Orakl Network CLI and Orakl Network API based on the feedback node operator.
* Version of Orakl CLI can be accesses through `orakl-cli version` command.
* `orakl-cli aggregator remove` removes related records from `Data` and `Aggregator` table as well.
* Produce nice error output when inserting aggregator with address that is already registered.
* https://github.com/Bisonai/orakl/issues/459
* https://github.com/Bisonai/orakl/issues/457
* https://github.com/Bisonai/orakl/issues/412
> Fix Orakl Network CLI Issues

- fetcher/README.md
- fetcher/src/job/job.api.ts
- fetcher/src/job/job.controller.ts
- fetcher/src/job/job.processor.ts
- fetcher/src/job/job.types.ts
- fetcher/src/job/job.utils.ts
Previously, when data collection failed for any resource, value of that data feed was set `undefined`. After submitting data with `undefined` value(s) to the Orakl Network API, the `undefined` value was rejected to be inserted and caused an error for all values that were supposed to be submitted at that time as a part of multi record insert transaction.
Additionally, this PR defines several types for safes object property access.
> Remove failed data feeds in Orakl Network Fetcher before inserting to the Orakl Network API

- core/src/listener/data-feed.ts
- core/src/listener/main.ts
- core/src/listener/request-response.ts
- core/src/listener/vrf.ts
- core/src/worker/data-feed.ts
- core/src/worker/main.ts
- core/src/worker/request-response.ts
- core/src/worker/vrf.ts
This PR adds a graceful shutdown for VRF and Request-Response worker and listener. Reporter is going to be updated soon to more general version #483  therefore it is not necessary to define it for VRF and Request-Response.
> Graceful shutdown for all services

- contracts/.solhint.json
- contracts/deploy/VRF/VRFCoordinator.ts
- contracts/package.json
- contracts/scripts/v0.1/request-response/integration/read-data.ts
- contracts/scripts/v0.1/request-response/read-data.ts
- contracts/scripts/v0.1/types.ts
- contracts/scripts/v0.1/utils.ts
- contracts/scripts/v0.1/vrf/read-vrf.ts
- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/src/v0.1/VRFCoordinator.sol
- contracts/src/v0.1/mocks/RequestResponseConsumerMock.sol
- contracts/src/v0.1/mocks/VRFConsumerMock.sol
- contracts/test/v0.1/Prepayment.test.ts
- contracts/test/v0.1/RequestResponseConsumerContract.test.ts
- contracts/test/v0.1/RequestResponseCoordinator.test.ts
- contracts/test/v0.1/VRF.test.ts
This PR changes the way how Coordinator registers and deregisters oracles. This change will give more direct access to registered metadata. The interface changes, therefore the version of `@bisonai/orakl-contracts` is bumped to 0.5.0.
* `sOracles()` -> `address[]`
* `oracleToKeyHash(address oracle)` -> `bytes32`
* `sKeyHashes()` -> `bytes32[]`
* `keyHashToOracle(bytes32 keyHash)` -> `address`
* `sOracles()` -> `address[]`
* `isOracleRegistered` -> `bool`
* Change order of functions within `*Coordinator` files based on Solidity guidelines for visibility
* Remove `s_` prefix pattern from `*Coordinator` files
* Updated VRF migration script for registration and deregistration of oracle
The VRF events below has to be updated in https://github.com/bisonai/orakl-subgraph through …
> An easy access to oracle addresses

- core/src/settings.ts
- core/src/types.ts
- core/src/worker/api.ts
- core/src/worker/data-feed.ts
This PR adds a check on data staleness to a Data Feed worker. If aggregated data are older than `MAX_DATA_STALENESS` (currently set to 5 seconds), then worker does not submit a job to reporter. The submission to heartbeat queue proceeds as usual.
> Check on data staleness to prevent submitting outdated data

- contracts/src/v0.1/Prepayment.sol
- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/src/v0.1/VRFCoordinator.sol
- contracts/src/v0.1/interfaces/PrepaymentInterface.sol
This PR add, AccType attribute for AccountID
> added accType attribute for Accounts

- .github/workflows/api.image+upload.yaml
- .github/workflows/cli.image+upload.yaml
- .github/workflows/core.image+upload.yaml
- .github/workflows/fetcher.image+upload.yaml
There is currently an issue with the aws credentials in Git Actions not being updated after switching from SDK version 2 to 3. Although version 2 is still working, it is in maintenance mode, so it's unclear whether it will continue to work properly. However, the credentials are still being received correctly when pushing to the repository in myside.
It may be helpful for you to try again to see this was temporary or not.
Additionally, the warning (deprecated) that was raised is unrelated to the credentials issue but fixed with this.
> fix git actions deprecated warning

- fetcher/src/job/job.controller.ts
- fetcher/src/job/job.processor.ts
- fetcher/src/settings.ts
Repeatable job of Orakl Network fetcher seems to be limited by sequential processing of jobs from queue. This PR increases the concurrency of job processing to 5. We expect to see increased processing speed.
> Increase Orakl Network Fetcher concurrency to 5

- contracts/src/v0.1/Prepayment.sol
- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/src/v0.1/VRFCoordinator.sol
- contracts/src/v0.1/interfaces/IPrepayment.sol
This PR changes a way how we check for a registered consumer under a specific amount. Previously, we used a clumsy way through nonce which is still used under the hood but now we support validity for both `regular` and `temporary` accounts with a simpler expression.
> Check for a validity of a `consumer` under `accId`

- api/prisma/migrations/20230419030642_reporter_remove_serviceId_from_unique/migration.sql
- api/prisma/schema.prisma
This PR is to change uniqueness of Reporter, which is to force make unique `reporter` in each `chain` for all types of services. Previously, it was allowed to use same reporter for different services.  
> remove `serviceId` from Reporter table

- contracts/src/v0.1/libraries/MajorityVoting.sol
- contracts/src/v0.1/mocks/MajorityVotingMock.sol
- contracts/test/v0.1/MajorityVoting.test.cjs
This PR implemented majority voting library for `boolean` data type. Majority voting can be applied only on boolean arrays of even length. If odd length array is passed to the library function, `EvenLenghtArray` error will be thrown.
> Majority voting for Boolean

- api/prisma/migrations/20230421082517_remove_reporter_uniqueness/migration.sql
- api/prisma/schema.prisma
This PR is to remove uniqueness from Reporter table. 
We need to remove uniqueness of reporter address to be able to use same data feed, but for two different aggregators.
> remove reporter uniqueness from `Reporter`

- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
Recent changes to Request-Response that implemented submission by multiple oracles did not include a constraints on a single submission per oracle to a single request. This PR implements those constraints together with tests.
> Don't allow to submit to Request-Response coordinator twice for the same request

- contracts/src/v0.1/VRFCoordinator.sol
- contracts/test/v0.1/VRFCoordinator.test.cjs
This PR changes basic data structures in `VRFCoordinator` in order to allow registration of multiple off-chain oracles under the same keyhash. This will allow to scale off-chain service better without being subject to blockchain transaction limitations.
Additionally this PR includes tests for VRF temporary account fulfillment.
> Allow to register multiple reporters in VRF to enable better off-chain scaling

- contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
- contracts/test/v0.1/VRFCoordinator.test.cjs
This PR implements tests to confirm that `reqCount` increases after fulfilling the request. The increase of `reqCount` happens indirectly inside of `chargeFee` through calls between multiple contracts (EOA off-chain oracle -> Coordinator -> Prepayment -> Account).
> Increase `reqCount` test

- contracts/src/v0.1/Aggregator.sol
- contracts/src/v0.1/AggregatorProxy.sol
- contracts/src/v0.1/interfaces/IAggregator.sol
- contracts/src/v0.1/interfaces/IAggregatorProxy.sol
- contracts/test/v0.1/Aggregator.test.cjs
This PR includes an integration of `typeAndVersion` function to `Aggregator` contract and allow to access it through `AggregatorProxy` as well. Test were appropriately updated.
> Use `typeAndVersion` for Aggregator

- contracts/src/v0.1/libraries/Median.sol
Solidity compiler is not able to understand that infinity loop never finishes, therefore it assumes that there is a chance that return variable might not be initialized and warns about that during compilation step. It recommends to name the variable which we cannot do in our case because we are reusing the same input parameter as return value as well.
According to https://github.com/ethereum/solidity/issues/13746, we can simply add a `revert()` statement that notifies compiler with a zero cost that loop will never break, therefore we do not need to add an additional return statement after an infinite loop.
> Remove compilation warning from `Median` library

- contracts/hardhat.config.cjs
- contracts/src/v0.1/Aggregator.sol
- contracts/src/v0.1/CoordinatorBase.sol
- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/src/v0.1/VRFCoordinator.sol
- contracts/src/v0.1/interfaces/IRequestResponseCoordinatorBase.sol
- contracts/src/v0.1/interfaces/IVRFCoordinatorBase.sol
- contracts/src/v0.1/mocks/RequestResponseConsumerMock.sol
- contracts/src/v0.1/mocks/VRFConsumerMock.sol
- contracts/test/v0.1/Account.test.cjs
- contracts/test/v0.1/Account.utils.cjs
- contracts/test/v0.1/Aggregator.test.cjs
- contracts/test/v0.1/Aggregator.utils.cjs
- contracts/test/v0.1/CoordinatorRevertFulfillment.test.cjs
- contracts/test/v0.1/Prepayment.test.cjs
- contracts/test/v0.1/RequestResponse.config.cjs
- contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
- contracts/test/v0.1/RequestResponseCoordinator.test.cjs
- contracts/test/v0.1/RequestResponseCoordinator.utils.cjs
- contracts/test/v0.1/VRFCoordinator.config.cjs
- contracts/test/v0.1/VRFCoordinator.test.cjs
- contracts/test/v0.1/VRFCoordinator.utils.cjs
* New parameter (`address refundRecipient`) when requesting for service with temporary account
* Move payment in Request-Response service after `cleanupAfterFulfillment` (return list of oracles that should be paid)
* `estimateFee` made `public` so consumers can know how much $KLAY to send before requesting for service
> Mix of contract modifications and tests

- contracts/src/v0.1/Aggregator.sol
- contracts/test/v0.1/Aggregator.test.cjs
- contracts/test/v0.1/Aggregator.utils.cjs
This PR slightly changes and improve Aggregator contract code and add more tests.
* Made `MAX_ORACLE_COUNT` public
* Replaced some `require` with `revert`
* Added auxiliary function `currentRoundStartedAt` that will be used by off-chain oracle to compute synchronized delay
* Added comments to not so obvious functions and code statements
* Added more Aggregator tests
> Aggregator related updates

- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/test/v0.1/CoordinatorRevertFulfillment.test.cjs
- contracts/test/v0.1/RequestResponseConsumerContract.test.cjs
`jobId` should be unique to every fulfillment function based on the `response` data type. This PR add a security check for `jobId` passed in `RequestCommitment` to every Request-Response fulfillment function.
> Reflect audit finding 2

- core/src/settings.ts
- core/src/worker/data-feed.ts
- core/src/worker/types.ts
- fetcher/src/app.settings.ts
- fetcher/src/job/job.api.ts
- fetcher/src/job/job.controller.ts
- fetcher/src/job/job.module.ts
- fetcher/src/job/job.processor.ts
- fetcher/src/job/job.types.ts
- fetcher/src/job/job.utils.ts
- fetcher/src/settings.ts
This PR implements deviation worker and queue.
> added queue and worker for deviation

- contracts/src/v0.1/Prepayment.sol
- contracts/src/v0.1/RequestResponseCoordinator.sol
- contracts/src/v0.1/VRFCoordinator.sol
- contracts/src/v0.1/interfaces/ICoordinatorBase.sol
- contracts/src/v0.1/interfaces/IPrepayment.sol
- contracts/src/v0.1/mocks/VRFConsumerMock.sol
- contracts/test/v0.1/VRFCoordinator.test.cjs
Request created by temporary account can be canceled. In both VRF https://github.com/Bisonai/orakl/blob/8d4657c6587ca4346a538c651fedbc41a2ff6ce5/contracts/src/v0.1/VRFCoordinator.sol#L364-L372 and RR https://github.com/Bisonai/orakl/blob/8d4657c6587ca4346a538c651fedbc41a2ff6ce5/contracts/src/v0.1/RequestResponseCoordinator.sol#L518-L529, request commitment and owner of request are stored in contract local storage. The exactly same code is used for temporary account and permanent account. Any request can therefore be canceled using `cancelRequestFunction` https://github.com/Bisonai/orakl/blob/8d4657c6587ca4346a538c651fedbc41a2ff6ce5/contracts/src/v0.1/CoordinatorBase.sol#L124-L137. Once the request is canceled, it cannot be fulfilled by any oracle because we have a validation of response …
> Allow to withdraw $KLAY from temporary account

- core/src/worker/data-feed.utils.ts
- core/src/worker/state.ts
This PR changes the way how data feed worker finds out the start time of the current round. Previously, we had to call `oracleRoundState` twice. After merging this PR, we can make a single call with `currentRoundStartedAt` to obtain the same information. We hope this will speed up the data feed worker and mitigate synchronization issues.
> Use `currentRoundStartedAt` instead of 2x `oracleRoundState`

- delegator/src/contract/contract.service.ts
- delegator/src/reporter/reporter.service.ts
- delegator/src/sign/sign.service.ts
This PR is to solve address mismatch with delegator and transaction. I provide solution for this problem by taking lowercase `contract` and `reporter` account address.
> `lowercase` delegator `contract` and `reporter` account addresses

- core/src/errors.ts
- core/src/reporter/reporter.ts
- core/src/reporter/utils.ts
This PR defines a fallback function for `Orakl Network Data Feed` reporters in case they cannot reach `Orakl Network Delegator`. If `Orakl Network Delegator` cannot be reached, reporters will submit transactions and pay for it by themselves.
> Fallback for data feed reporter when delegator fails

- core/src/listener/state.ts
This PR is to fix running multiple reporters with `repeatable delayed jobs`. The problems is when we start all the reporters at once, all of the jobs will have same job id. 
- This collusion `jobId` is fixed by adding manual repeat job id as listening contract address. By making this all of the jobs will be unique by contract address. 
- Additional, this PR is also include fixing of deactivation of listeners. 
> fix listener `bullmq` `worker_id` collusion

- core/src/settings.ts
Increase `VRF_FULFILL_GAS_MINIMUM` because of nondeterministic computation of VRF proof verification on chain. We can observe the  gas used for verification over the time and then lower it if necessary.
> Increase VRF_FULFILL_GAS_MINIMUM to 450k

- contracts/hardhat.config.cjs
This PR is ready to review and merge. With this PR I added new hardhat task, to transfer native token from the wallet to any account. Wallet will be created from `PRIVATE_KEY` or `MNEMONIC` env variable. 
How to use
- The following command is how to transfer money with address and amount as a input variable. 
` npx hardhat send-klay --address ${address} --amount 1`
> hardhat task to transfer Klay

- core/src/reporter/utils.ts
This PR is ready to review and merge. The main change with this PR is to use `.call()` before sending transaction on `orakl-core` reporter to check if the transaction compatible to execute with latest blockchain state. 
This change effect for all `orakl-services` such as `Price-Feed`, `RR`, and `VRF`.
> use `call()` method before sending transaction

- fetcher/src/job/job.types.ts
previous feed headers definition had array of IHeader type and `IHeader` type contained only `Content-Type` key which wasn't compatible with axios request parameter type. now fixing the data type to object that can have multiple headers attributes.
it was running without any errors since type checking wasn't happening in `fetcher/src/job/job.utils.ts`, sending parameter with `any` type.
> Update headers type to match axios request parameter

- contracts/deployments/baobab/Prepayment.json
- contracts/deployments/cypress/Prepayment.json
- contracts/package.json
- contracts/src/v0.1/Prepayment.sol
We have accidentally left a typo inside of `Prepayment`s event name. To limit the spread to other parts of codebase, this PR fixes the name inside of ABI (baobab and cypress) which has no impact on use of `Prepayment` smart contract with updated ABI. Additionally, the package of `@bisonai/orakl-contracts` was bumbed to version `1.2.1`.
> Rename event name `disCount` -> `discount`

- core/src/worker/data-feed.utils.ts
I found a small issue where we get data in wrong format in data feed worker. While we launch `data-feed worker` or `activate data-feed` we checks the remaining time to submit for the round. 
> Fix return type of `startedAt` on price feed worker

- cli/src/adapter.ts
fixed error message to see detailed reason
```bash
// before
yarn cli adapter hash --verify --source '/Users/nick/development/orakl-config/adapter/wemix-usdt.adapter.json'
yarn run v1.22.19
$ node --no-warnings --experimental-specifier-resolution=node --experimental-json-modules dist/index.js adapter hash --verify --source /Users/nick/development/orakl-config/adapter/wemix-usdt.adapter.json
Adapter hash could not be computed. Reason:
Request failed with status code 400
// after
❯❯❯ yarn cli adapter hash --verify --source '/Users/nick/development/orakl-config/adapter/wemix-usdt.adapter.json'
yarn run v1.22.19
$ node --no-warnings --experimental-specifier-resolution=node --experimental-json-modules dist/index.js adapter hash --verify --source …
```
> Fix `cli adapter hash` error msg

- cli/src/aggregator.ts
`fetcherType` has been defined as optional parameter from cli
```
const insert = command({
name: 'insert',
args: {
data: option({
type: ReadFile,
long: 'source'
}),
chain: option({
type: cmdstring,
long: 'chain'
}),
fetcherType: fetcherTypeOptionalOption
},
handler: insertHandler()
})
```
yet the wrapped function which was called inside wasn't setting the parameter as optional. so the error has occured
```bash
nick@NICKui-MacBookPro ~/development/orakl/cli   master ✭ 1 ?1              ✔
❯❯❯ yarn test
yarn run v1.22.19
$ node --no-warnings --experimental-vm-modules node_modules/jest/bin/jest.js
FAIL  test/aggregator.ts
● Test suite failed to run
test/aggregator.ts:22:27 - error TS2345: Argument of type '{ data: { active: boolean; name: string; address: string; fixedHeartbeatRate: number; …
```
> fix cli test failure

- cli/src/utils.ts
Previously, when requested `cli fetcher active` with wrong host and port, it returned following message
`Orakl Network Fetcher [${url}] is down`.
Now it checks if url is valid and returns
`Invalid URL` on wrong request
> Detailed err message on wrong request url

- core/src/reporter/data-feed.ts
Running many data feeds requires higher reporter concurrency. Trying to double and see how much it helps.
> Increase data feed reporter concurrency from 5 to 10

- .github/workflows/admin.image+upload.yaml
- .github/workflows/api.image+upload.yaml
- .github/workflows/cli.image+upload.yaml
- .github/workflows/core.image+upload.yaml
- .github/workflows/delegator.image+upload.yaml
- .github/workflows/fetcher.image+upload.yaml
- .github/workflows/monitor.image+upload.yaml
This PR updates Github action pipelines that generated images and publish them to Amazon ECR. These pipelines are triggered by `closing` PR, however, we want to trigger such pipelines when PR is merged to master branch.
Recently, one PR was accidentally closed https://github.com/Bisonai/orakl/pull/847 which caused to trigger the pipeline https://github.com/Bisonai/orakl/actions/runs/6821457480. 
The change is from on `pull_request` to on `push`, and removes `closed` activity.
> Don't publish images on closed PRs

- core/src/reporter/data-feed.ts
- core/src/settings.ts
checks current chainId on building reporter and allow delegated fee only from `baobab` and `cypress`.
`baobab`: 1001
`cypress`: 8217
> Use delegated fee only from `cypress` and `baobab`

- core/src/reporter/data-feed.ts
- core/src/settings.ts
This PR allows to set a data feed reporter concurrency without rebuilding reporter. The data feed concurrency can be set through `DATA_FEED_REPORTER_CONCURRENCY` environment variable. If environment variable is not supplied, the default value of 15 workers is used.
> Allow to set data feed reporter concurrency through env var

- fetcher/src/job/job.errors.ts
- fetcher/src/job/job.reducer.ts
some foreign exchange only supports reversed pairs.
for example `USD-KRW` is supported rather than `KRW-USD`.
somehow, after getting 1 USD price in KRW, for example `1USD = 1350KRW`, 
to get 1 KRW price in USD, it should be calculated with reversed division `1 KRW = 1 / 1350 USD`.
this PR adds reducer for that functionality
> Add reducer for fetcher

- fetcher/README.md
- fetcher/src/settings.ts
Introduce `CONCURRENCY` environment variable to `Orakl Network Fetcher` and set its default value to 20.
> Increase fetcher workers 11 -> 20

- api/README.md
- api/prisma/migrations/20231116075406_add_proxy_location/migration.sql
- api/prisma/migrations/20231116080058_set_proxy_location_optional/migration.sql
- api/prisma/schema.prisma
- api/src/proxy/dto/proxy.ts
- api/src/proxy/proxy.service.spec.ts
- cli/src/proxy.ts
- cli/src/utils.ts
- fetcher/src/job/job.types.ts
- fetcher/src/job/job.utils.ts
Some data source url requires ip of specific area. To deal with this problem, certain url should be requested by certain proxy with appropriate ip address. To use locational proxy following updates are made.
- adds `location` column to `proxy` table.
- `cli` is now able to add proxy with optional `location` parameter
- when distributing proxies for each element in adapter feeds, if `location` is defined, it'll randomly assign proxy with same location value -> any suggestion for better logic is welcomed
- further notes: adapters for recently added foreign exchange should be redefined
> Add proxy location

- api/src/aggregate/aggregate.service.ts
This PR will rollback behavior when item not found, it'll return `null`
previous code
```
return await this.prisma.aggregate.findFirst({
where: { aggregator: { aggregatorHash } },
orderBy: [
{
timestamp: 'desc'
}
]
})
```
this will fix current error which fetcher is not working for newly added aggregator
> Rollback expected behavior, return null if empty result

- api/package.json
- delegator/package.json
- fetcher/package.json
- l2-api/package.json
- monitor/package.json
Removes `--fix` option from lint commands
Even though `yarn lint` has been called from github actions, certain package.json had lint command with `--fix` option which ended up with successful github action lint command which shouldn't have.
> Remove fix option from package lint commands

- core/package.json
- core/src/types.ts
- core/src/worker/vrf.ts
- core/yarn.lock
- vrf/package.json
- vrf/src/index.ts
- vrf/src/types.ts
This PR removes duplicated function definition `processVrfRequest` from `@bisonai/orakl` and instead uses the same function defined from `@bisonai/orakl-vrf`.
This change required an update to `@bisonai/orakl-vrf` which defines output type `IVrfResponse` and version of `@bisonai/orakl-vrf` has been increased to `0.2.1`.
We have a test which checks whether VRF functionality has been affected at https://github.com/Bisonai/orakl/blob/master/core/test/vrf-worker.test.ts triggered at https://github.com/Bisonai/orakl/actions/runs/7001192921/job/19042932016?pr=976
```
PASS test/vrf-worker.test.ts (13.702 s)
VRF Worker
✓ Composability test (1127 ms)
```
> Use `processVrfRequest` from `@bisonai/orakl-vrf` rather than redefine it in worker

- .github/workflows/contracts.test.yaml
- .github/workflows/vrf.contracts.test.yaml
- contracts/.husky/pre-commit
- contracts/package.json
- core/.husky/pre-commit
only `contracts` package is using name `eslint` for linting command while all other packages use `lint`
> Modify command name `eslint` -> `lint` for consistency

- contracts/package.json
- contracts/tsconfig.json
- contracts/utils/index.ts
Adds functionality to get contract address from the package
use following functions to get contract addresses
`import {getContractAddressExact, getAggregatorAddress, getAggregatorProxyAddress} from @bisonai/orakl-contracts/utils`
> Get contract addresses from `contracts` package

- package.json
Prisma client works as a singleton which leads to problem when trying to access different databases from same instance. For instance, currently if orakl api and orakl delegator server is run in the same instance, only the one which later built works. Loading prisma from each workspace can prevent this error
> Set prisma dependency to nohoist

- core/package.json
Remove fetcher build from core prebuild step since it's no more referenced. This fixes docker-compose build failure issue for core image
> Remove fetcher build from core prebuild step

- .github/workflows/api.image+upload.yaml
- .github/workflows/cli.image+upload.yaml
- .github/workflows/fetcher.image+upload.yaml
- .github/workflows/monitor.image+upload.yaml
Currently, the updates in workspace directory has to be changed in master branch push to trigger image build.
As new `fetcher` image build is required after `util` workspace updates, adding workflow dispatch condition to manually trigger image build would be nice
> Add workflow dispatch for image builds

- fetcher/src/job/job.utils.ts
- fetcher/src/settings.ts
This PR adds a timeout to every fetcher call. The default timeout is set to 1 second.
> Define timeout for Fetcher calls

- core/src/por/main.ts
- core/src/por/reporter.ts
- core/src/por/utils.ts
- core/src/settings.ts
- use timeout for por call and rpc check
- adds `checkRpcUrl()` function to check if rpc url is alive 
- adds `FALLBACK_PROVIDER_URL` to be used in case of default rpc url fail
- adds `POR_TIMEOUT` to set total por run timeout ms
- adds `RPC_URL_TIMEOUT` to set timeout for RPC url alive
> POR updates

- core/src/listener/data-feed.ts
- core/src/reporter/data-feed.ts
- core/src/worker/data-feed.ts
- fetcher/src/job/job.controller.ts
obliterate queues when launching data-feed l,w,r and fetcher
expected to remove necessity of redis flush queue
> Remove jobs from queue on starting data feed

- core/src/listener/data-feed.ts
- core/src/reporter/data-feed.ts
- core/src/worker/data-feed.ts
- fetcher/src/job/job.controller.ts
Since obliterate emits error on active jobs in queue, force obliterate on service start is required
> Add force obliterate option

- core/src/errors.ts
- core/src/listener/data-feed.ts
- core/src/reporter/data-feed.ts
- core/src/reporter/factory.ts
- core/src/reporter/reporter.ts
- core/src/reporter/types.ts
- core/src/types.ts
- core/src/utils.ts
- core/src/worker/data-feed.ts
- core/test/utils.ts
Datafeed related queue optimization based on roundId
<details>
<summary>Click to expand</summary>
- isRoundIdFresh: checks if given roundId is new inside given queue
https://github.com/Bisonai/orakl/blob/53f2e18a5877455a337537eacf728283b62f5d1a/core/src/utils.ts#L110-L125
- dataFeedReporter: add functionality to skip reporting for old roundId
https://github.com/Bisonai/orakl/blob/53f2e18a5877455a337537eacf728283b62f5d1a/core/src/reporter/reporter.ts#L73-L92
</details>
If roundId is low, jobs won't be added to following queues
- workerQueue
- reporterQueue (aggregatorQueue)
If roundId is low, reporter will skip reporting.
> Queue optimization based on roundId

- core/src/listener/data-feed.ts
latestListenerQueue was empty after obliterate was called,
and then from `clear()`, it tried to get jobs from queue based on remaining activeListeners which was already empty leading to error
this fixes certain error by removing activeListeners before obliterate
> remove listener state before obliterate

- core/src/reporter/factory.ts
AS-IS
Print out every information about reporter in factory.
TO-BE
Print out only `address` and `oracleAddress` about reporter in factory.
> Display `address` and `oracleAddress` during reporter launch

- go-api/adapter/controller.go
- go-api/aggregate/controller.go
- go-api/aggregator/controller.go
- go-api/apierr/controller.go
- go-api/chain/controller.go
- go-api/data/controller.go
- go-api/feed/controller.go
- go-api/l2aggregator/controller.go
- go-api/listener/controller.go
- go-api/main.go
- go-api/proxy/controller.go
- go-api/reporter/controller.go
- go-api/service/controller.go
- go-api/utils/utils.go
- go-api/vrf/controller.go
**it's okay to only review utils/utils.go file**
- Mostly relies on fiber logger middleware
- No information for stacktrace or filepath
- Unintended status code 200 on panic
```bash
2024/02/03 12:15:19.630830 controller.go:127: [Panic] no rows in result set
12:15:19 | 200 |   38.638583ms | 127.0.0.1 | GET | /api/v1/adapter/94 | -
```
```bash
12:18:03 | 404 |    2.466833ms | 127.0.0.1 | GET | /api/v1/docs | Cannot GET /api/v1/docs
```
- No more logs for successful requests
- Panic error will print out stack trace
```bash
2024/02/03 11:43:51 | (adapter/controller.go:126) panic: no rows in result set
goroutine 26 [running]:
runtime/debug.Stack()
/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/debug/stack.go:24 +0x64
go-api/utils.CustomStackTraceHandler(0x0?, {0x1026ecca0?, 0x102b2cd40}) …
```
> Improve api logging

- fetcher-v2/go.mod
- fetcher-v2/go.sum
- fetcher-v2/utils/fetcher-node.go
- fetcher-v2/utils/utils.go
Each peer was generating roundId based on timestamp from each machine. Since each machine could have difference with its generated timestamp, they could've been submitting to different roundId at same tick
This update adds publishing & subscribing layer to synchronize roundId
1. Generates roundId based on timestamp from each peer
2. Publish generated roundId
3. Collects roundIds from subscribed messages
4. Once collected roundIds exceeds number of subscribers, select max value among collected roundIds and proceed
- Now receive message also from itself and updates data only from subscription. If data update happens both from subscription and publish, it's difficult to handle conditional execution
- Limited length of roundID string to 6
- Refactoring based on phase of communication. …
> (OraklNode) sync roundId based on max suggested id

- go-api/aggregate/controller.go
- go-api/utils/utils.go
it'll no more panic on empty query result, but rather return empty result
> (API) Fix default behavior of empty row on `ErrNoRows`

- go-api/adapter/controller.go
- go-api/feed/queries.go
- go-api/migrations/000001_initialize_tables.up.sql
Prisma used to auto handle constraint deletion, so it deleted feeds when adapter deletion requested. However, it wasn't handled in go-api. This PR adds feature to remove all related feeds on removing adapter
> (API) Hotfix adapter removal

- core/package.json
- core/src/api.ts
- core/src/errors.ts
> (CORE) Add error code and catch error

- .github/workflows/node.test.yaml
- node/pkg/admin/tests/adapter_test.go
- node/pkg/admin/tests/feed_test.go
- node/pkg/aggregator/aggregator.go
- node/pkg/db/pgsql.go
- node/pkg/db/redis.go
- node/pkg/raft/raft.go
- node/taskfiles/taskfile.local.yml
- linter and vet checks
- minor updates to fix shadowing error and lint error found while writing github action
> (OraklNode) Add github action for testing

- node/pkg/db/pgsql.go
- node/pkg/db/redis.go
Keeps calling `os.Getenv()` whenever there is an access to db
Save error from `once.Do()` and refer to error on db access
> (OraklNode) Use global error instead of env load everytime

- node/pkg/aggregator/aggregator.go
- node/pkg/raft/raft.go
- node/pkg/raft/types.go
- libp2p related variables lay inside Raft object, this pr will remove duplicate from aggregator structure.
- `job` inside Raft pkg seems better to be implemented through raft utilizing packages (aggregator & submitter), so related codes are removed
> (OraklNode) Remove struct elements from Aggregator & Raft

- node/cmd/boot/main.go
- node/pkg/libp2p/libp2p.go
- node/taskfiles/taskfile.local.yml
- SetBootNode : function to setup bootnode
- Setup: setup libp2p host and pubsub to be used
- GetBootNode: gets bootnode address string based on command line flag parameter or env variable
- GetListenPort: gets listenport for libp2p host based on command line flag parameter or env variable
- main.go file to run bootnode, used for testing purpose
> (OraklNode) Update libp2p package with setup functions and bootnode setups

- node/pkg/db/pgsql.go
- node/pkg/db/redis.go
- node/pkg/fetcher/fetcher_test.go
- node/pkg/raft/raft.go
Removes variable names starting with underscore which were supposed to solve shadowing issue, yet leading to less readability
> (OraklNode) Remove underscore var

- go-delegator/utils/utils.go
Provider url has been declared but never been used in production code, only being used in test code. so removing it from application initialization
> (GO-Delegator) Remove provider url

- node/pkg/aggregator/node.go
- node/pkg/aggregator/node_test.go
- node/pkg/raft/raft.go
- node/pkg/raft/types.go
Tried to fix issues found while running nodes locally. 
- When there are more than 3 nodes connected and leader disconnects, sometimes leader job ticks twice every 5 seconds
-> used timer instead of ticker
-> added condition on triggering `becomeLeader` to be called only if current role is candidate
- When there are more than 2 nodes connected and another node joins, sometimes leader resigns and joined node hangs as a candidate. and nodes keeps doing infinite voting
-> added condition to `handleHeartbeat` function to prevent unexpected resign of leader
-> added condition to `handleRequestVote` function to prevent unexpected grant denial
- When new node has joined or new leader has been elected, sometimes the roundID is synced to lower ones
-> sync roundID only if current role is not …
> (OraklNode) Update raft stability

- node/pkg/admin/adapter/controller.go
- node/pkg/admin/aggregator/controller.go
- node/pkg/admin/fetcher/controller.go
- node/pkg/admin/tests/adapter_test.go
- node/pkg/admin/tests/aggregator_test.go
- node/pkg/admin/tests/fetcher_test.go
- node/pkg/admin/utils/utils.go
- node/pkg/aggregator/aggregator.go
- node/pkg/aggregator/main_test.go
- node/pkg/bus/bus.go
- node/pkg/bus/bus_test.go
- node/pkg/fetcher/fetcher.go
Updates message bus package to use msg response channel. After sending message, sender can access response through `Response` channel element of message struct
it includes related implementation updates and test codes updates
- [] If it is a core feature, I have added thorough tests.
> (OraklNode) Improve message bus to take msg response

- node/cmd/test_connection/main.go
this main code is to measure connection time of gossipSub nodes
can send flag if using bootnode or not
> (OraklNode) Script to measure gossipsub connection time

- api/main.go
- api/utils/utils.go
Emit error message for empty environment variable such as `REDIS_HOST`, `REDIS_PORT` or `ENCRYPT_PASSWORD`
> (API) error message for empty environment variables

- api/chain/controller.go
- api/proxy/controller.go
- api/service/controller.go
API
```
2024/03/29 17:48:28 | (chain/controller.go:33) panic: ERROR: duplicate key value violates unique constraint "chains_name_key" (SQLSTATE 23505)
goroutine 22 [running]:
runtime/debug.Stack()
/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/debug/stack.go:24 +0x64
bisonai.com/orakl/api/utils.CustomStackTraceHandler(0x14000001c20?, {0x100f30e60?, 0x140001740f0})
/Users/nick/development/orakl/api/utils/utils.go:333 +0x1d8
bisonai.com/orakl/api/utils.Setup.New.func2.1()
/Users/nick/.go/pkg/mod/github.com/gofiber/fiber/v2@v2.52.0/middleware/recover/recover.go:31 +0x70
panic({0x100f30e60?, 0x140001740f0?})
/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/panic.go:914 +0x218
bisonai.com/orakl/api/chain.insert(0x100f20820?)
/Users/nick/development/orakl/api/chain/controller.go:33 +0x17c …
```
> (Maintenance) Partial API updates for db failure

- node/pkg/aggregator/aggregator.go
- node/pkg/aggregator/types.go
- node/pkg/aggregator/utils.go
- node/pkg/reporter/main_test.go
- node/pkg/reporter/reporter.go
Separated struct for pgsql and rdb from aggregator while using the same struct in reporter
Remove `redisGlobalAggregate` type and use `globalAggregate` type instead for rdb
> (OraklNode) Unify struct for global aggregate

- cli/src/settings.ts
currently env variables should also be updated from pods
commands such as followed aren't working unless sending host port parameter together
`yarn cli listener active`
```
Error: getaddrinfo ENOTFOUND orakl-core-aggregator-listener.orakl.svc.cluster.local
```
Assuming it should be updated to `http://orakl-aggregator-listener.orakl.svc.cluster.local`
> Update cli settings urls

- node/pkg/aggregator/aggregator.go
- node/pkg/raft/raft.go
- node/pkg/reporter/reporter.go
Previously, `StopHeartbeatTicker` function has been called to resign as leader, this renames the function and add few more missing steps to smoothly resign from raft leader
- Updates own role into `follower`
- Updates saved leader into empty string
- Starts ElectionTimer
> (OraklNode) Rename function, `StopHeartbeatTicker` -> `ResignLeader`

- node/pkg/reporter/app.go
- node/pkg/reporter/main_test.go
- node/pkg/reporter/reporter.go
- node/pkg/reporter/reporter_test.go
- node/pkg/reporter/types.go
- node/pkg/reporter/utils_test.go
- Deviation Intervals used to have fixed value which was 5 seconds, now will follow aggregate interval
- Update Reporter initialize function to use functional options pattern
- Rename `ReporterConfig` -> `Config`. Now `ReporterConfig` stand for the configuration used on initializing reporter object. `Config` will stand for value returned from `configs` table which derives from orakl-config 
> (OraklNode) Refactor reporter, set deviation intervals

- node/cmd/node/main.go
- node/pkg/aggregator/main_test.go
- node/pkg/boot/boot.go
- node/pkg/boot/peer/controller.go
- node/pkg/boot/tests/peer_test.go
- node/pkg/fetcher/app.go
- node/pkg/reporter/main_test.go
- node/pkg/reporter/reporter.go
- node/pkg/reporter/utils.go
- node/pkg/reporter/utils_test.go
- node/script/test_connection/main.go
- node/script/test_fetcher_and_aggregator/main.go
- node/script/test_raft/main.go
In Go, it's generally recommended to avoid underscores in package names and aliases. This is because Go's naming conventions favor camelCase and all lowercase letters without underscores or hyphens.
> (OraklNode) Remove underscored naming for named imports

- .vscode/extensions.json
- cli/.eslintrc
- cli/package.json
- cli/src/adapter.ts
- cli/src/aggregator.ts
- cli/src/chain.ts
- cli/src/cli-types.ts
- cli/src/datafeed.ts
- cli/src/delegator.ts
- cli/src/fetcher.ts
- cli/src/index.ts
- cli/src/listener.ts
- cli/src/proxy.ts
- cli/src/reporter.ts
- cli/src/service.ts
- cli/src/utils.ts
- cli/src/vrf.ts
- cli/tsconfig.json
- yarn.lock
Closes #1454 
We are using ES modules in the `cli` workspace and currently, most if not all of our imports in the cli workspace don't include the file extension, which is a requirement in ES modules. Since tsc doesn't add .js extension during compilation, there is a `module not found` error when we try to run `node dist/index.js`. 
This PR:
-  manually adds `.js` extensions to all imports
-  adds an `eslint-plugin-import` package to provide linting error suggestions when imported file extension is not provided (ignores the test dir)
I've tested running the cli executable after these implementations and the `module not found` error has been resolved.
> Manually add .js extension to relative imports

- node/.env.example
- node/pkg/chain/helper/helper.go
- node/pkg/db/pgsql.go
- node/pkg/libp2p/setup/setup.go
- node/pkg/por/app.go
- node/pkg/secrets/secrets.go
- node/pkg/utils/encryptor/encryptor.go
First tries to load settings from vault, fallbacks to environment variable if not exists in vault. use `sync.Once` to load vault secrets only once on package load
- `KLAYTN_REPORTER_PK`
- `SIGNER_PK`
- `ETH_REPORTER_PK` (but not utilized at the moment)
- `PRIVATE_NETWORK_SECRET`
- `ENCRYPT_PASSWORD`
- `DATABASE_URL`
- `POR_REPORTER_PK`
> (OraklNode) Vault integration

- contracts/v0.2/src/SubmissionProxy.sol
Adds logic to store last submission time and check if submitted timestamp is newer than last submission
> (Contract) Add check based on last submission time

- api/secrets/secrets.go
sync.Once is logically duplicate since `init()` is executed only once
> (API) Remove sync.Once as init is executed only once

- delegator/sign/controller.go
- delegator/sign/route.go
- delegator/tests/sign_test.go
Adds endpoint which returns fee payer public address, to be referenced from orakl-sentry
> (Delegator) Add endpoint to retrieve eoa addr

- node/pkg/admin/tests/main_test.go
- node/pkg/admin/tests/wallet_test.go
- node/pkg/admin/wallet/controller.go
- node/pkg/admin/wallet/route.go
- node/pkg/chain/helper/helper.go
- node/pkg/chain/tests/chain_test.go
- node/pkg/chain/utils/utils.go
- node/pkg/por/app.go
- adds admin endpoint which returns all stored wallets' public addresses
- if reporter pk from env variable is not inside the table, it'll try to insert it
- adds por endpoint which returns por reporter wallet's public address
> (OraklNode) Public address retrieval functionalities

- core/package.json
- yarn.lock
Implement nodemon for having hot reload running services (listener, worker, reporter). This will allow better local development experience where simply hitting a save key in any file will trigger the server restart. _Note_: hot reload in this case means recompile and restart the service
> Nodemon for listener, worker, and reporter services

- node/pkg/admin/config/controller.go
- node/pkg/admin/feed/controller.go
- node/pkg/admin/providerUrl/controller.go
- node/pkg/admin/proxy/controller.go
- node/pkg/admin/tests/aggregator_test.go
- node/pkg/admin/tests/config_test.go
- node/pkg/admin/tests/feed_test.go
- node/pkg/admin/tests/fetcher_test.go
- node/pkg/admin/tests/providerUrl_test.go
- node/pkg/admin/tests/proxy_test.go
- node/pkg/admin/tests/wallet_test.go
- node/pkg/admin/wallet/controller.go
ID's data type in PGSQL is int4 which could be represented as int32 type in golang.
This PR updates the types and unifies with other packages (fetcher, aggregator, and reporter)
> (OraklNode) update id types from node admin

- node/pkg/db/redis.go
Load rdb connection pool once on application start and reuse forever
Whenever getting redis pool try to ping the connection, if fails, try reinitialize connection
RDB ip can change unexpectedly during k8s pod operation and cached pool fails to connect to new redis ip address
> Update rdb pkg structure

- node/pkg/fetcher/app.go
- node/pkg/fetcher/types.go
- node/pkg/fetcher/utils.go
local aggregator didn't try to aggregate websocket feeds as query to load feeds excluded those. this update tries to fix the issue
> (OraklNode) fix issue with collectors

- node/cmd/node/main.go
For easier node connection bug fix, don't exit but wait after failure on setting libp2p node from boot api
> (OraklNode) Infinite wait on libp2p node fail

- node/pkg/websocketfetcher/app.go
- node/pkg/websocketfetcher/common/utils.go
- node/pkg/websocketfetcher/providers/huobi/huobi.go
- node/pkg/websocketfetcher/providers/huobi/type.go
- node/pkg/websocketfetcher/providers/huobi/utils.go
- node/pkg/websocketfetcher/providers/mexc/mexc.go
- node/pkg/websocketfetcher/providers/mexc/type.go
- node/pkg/websocketfetcher/providers/mexc/utils.go
- node/pkg/wss/utils.go
Include missing price provider
- Huobi
- Mexc
Different from other data providers, Huobi returns data in gzip compressed format. To handle the case, a new option has been added to WebsocketHelper.
> (OraklNode) Add Huobi and Mexc websocket fetchers

- node/.env.example
- node/cmd/node/main.go
- node/pkg/aggregator/main_test.go
- node/pkg/boot/tests/peer_test.go
- node/pkg/libp2p/setup/setup.go
- node/pkg/libp2p/setup/type.go
- node/pkg/libp2p/tests/libp2p_test.go
- node/pkg/libp2p/utils/utils.go
- node/pkg/raft/accessors.go
- node/pkg/raft/raft.go
- node/pkg/raft/types.go
- node/pkg/reporter/main_test.go
- node/pkg/utils/set/set.go
- node/pkg/utils/tests/set_test.go
Track cluster peers manually instead of using built in function [pubsub.ListPeers](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub#PubSub.ListPeers)
> (OraklNode) Track peers manually

- node/pkg/chain/utils/types.go
- node/pkg/chain/utils/utils.go
Slight delays from cypress assumed to be due to mine wait failure which is 5 seconds at the moment.
Increasing it into 10 seconds to see how it goes
> (OraklNode) Wait longer to be mined (10secs)

- node/pkg/chain/helper/helper.go
- node/pkg/chain/tests/chain_test.go
- node/pkg/chain/utils/utils.go
- node/pkg/error/sentinel.go
- node/pkg/reporter/reporter.go
- node/pkg/reporter/types.go
- node/pkg/reporter/utils.go
- node/script/test_submission/main.go
From previous implementation, it has been attempted to only update gasPrice value from the transaction which lead to transaction failure. It has been revealed that gasPrice value is also referred on generating transaction sign.
This solves the issue by taking gasPrice multiplier from transaction generating function, so that updated gasPrice is included when signing the transaction
> (OraklNode) Reimplement gas price multiplier

- core/package.json
- core/src/errors.ts
- core/src/reporter/data-feed-L2.ts
- core/src/reporter/data-feed.ts
- core/src/reporter/factory.ts
- core/src/reporter/nonceManager.ts
- core/src/reporter/reporter.ts
- core/src/reporter/request-response-L2-fulfill.ts
- core/src/reporter/request-response-L2-request.ts
- core/src/reporter/request-response.ts
- core/src/reporter/state.ts
- core/src/reporter/types.ts
- core/src/reporter/utils.ts
- core/src/reporter/vrf-L2-fulfill.ts
- core/src/reporter/vrf-L2-request.ts
- core/src/reporter/vrf.ts
- core/src/settings.ts
- core/src/types.ts
- core/src/worker/request-response.ts
- core/src/worker/vrf.ts
- core/test/nonce-manager.test.ts
- core/test/reporter.test.ts
- yarn.lock
Related [issue](https://github.com/Bisonai/orakl/issues/1570)
This PR implements:
- Manual nonce management function in reporter state. The function is mutex, meaning only a single process can execute it at any given time. Other concurrent calls to the function will be on queue until the lock becomes free
- Nonce manager queue and worker in reporter service. The Worker service's worker submits jobs to `nonceManagerQueue` and `nonceManagerWorker` in Reporter service submits them to `reporterQueue` along with a nonce value
Part 2 of "Revamp reporter" will be handling edge cases such as json rpc unresponsiveness, service restart/crash, and redis flushes.
> Revamp reporter (1/2): Implement nonce manager mutex, queue, and worker

- core/.eslintrc
- core/src/errors.ts
- core/src/reporter/reporter.ts
- core/src/reporter/state.ts
- core/src/reporter/utils.ts
- core/src/settings.ts
- core/src/utils.ts
- core/test/caver-js.test.ts
- core/test/nonce-manager.test.ts
- core/test/reporter.test.ts
Closes #1570 
Implements infinite polling in predefined intervals, currently 1 second, when json rpc goes down and `wallet.getTransactionCount()` operation fails in the nonce manager mutex function. There will be an error log and slack message at certain intervals, currently set to 10 mins, until the json rpc becomes available
> Revamp reporter (2/2): handle json rpc down and server restart/crash

- .github/workflows/node.test.yaml
- node/.env.example
- node/.env.local
- node/README.md
- node/pkg/chain/helper/helper.go
- node/pkg/chain/helper/types.go
- node/pkg/chain/tests/chain_test.go
- node/pkg/error/sentinel.go
- node/pkg/por/app.go
- node/pkg/por/por_test.go
- node/pkg/por/types.go
- node/pkg/reporter/app.go
- node/pkg/reporter/reporter.go
- node/pkg/reporter/reporter_test.go
- node/pkg/reporter/types.go
- node/script/test_submission/main.go
Update variable and function names including `Klaytn`
> (OraklNode) Update Klaytn -> Kaia

- core/src/worker/request-response.ts
`e.code` is undefined in `worker/request-response.ts` when the `e` is of type `Error`, in which case `e.code.toString()` will cause the app crash. This PR checks the `instanceof` the error and accesses the error code if the error type is `OrakleError`
Closes #996 
> fix rr worker e.code is undefined issue

- node/pkg/wss/utils.go
some errors are hard to find the source, try to add details from websocket helper package
```
{"level":"error","Player":"Bitstamp","error":"context deadline exceeded (Client.Timeout or context cancellation while reading body)","time":"2024-06-20T05:07:25Z","message":"error in fetchVolumes"}
│ {"level":"error","error":"failed to read JSON message: failed to get reader: received close frame: status = StatusNormalClosure and reason = \"\"","time":"2024-06-20T05:07:35Z","message":"error readin
│ {"level":"error","error":"failed to read JSON message: failed to get reader: received close frame: status = StatusNormalClosure and reason = \"\"","time":"2024-06-20T05:07:35Z","message":"error readin
│ {"level":"error","error":"Get \"https://www.bitstamp.net/api/v2/ticker/\": context deadline …
```
> (OraklNode) Include websocket endpoint into error log

- node/pkg/websocketfetcher/providers/xt/xt.go
XT takes lowercase symbols for subscription, which wasn't taken cared of from local testing. This PR adds symbol string to lowercase logic into xt.com exchange websocket fetcher
> (OraklNode) xt takes lowercase symbols

- node/pkg/websocketfetcher/providers/xt/xt.go
Even though official documents says it is possible to subscribe to multiple pairs with single request, there are limitation for this. it should be requesting subscription one by one
> (OraklNode) Fix xt hidden subscription limitation

- node/pkg/db/redis.go
- node/pkg/websocketfetcher/common/utils.go
- node/pkg/websocketfetcher/providers/bitmart/bitmart.go
- node/pkg/websocketfetcher/providers/bybit/bybit.go
Even though it is written that multiple subscription through single message is possible, some api doesn't work as expected for too many pairs. this pr tries to fix
> (OraklNode) Split subscription

- node/pkg/websocketfetcher/providers/bitget/bitget.go
- node/pkg/websocketfetcher/providers/bitget/type.go
- node/pkg/websocketfetcher/providers/bitmart/bitmart.go
- node/pkg/websocketfetcher/providers/crypto/crypto.go
- node/pkg/websocketfetcher/providers/crypto/types.go
- node/pkg/websocketfetcher/providers/lbank/lbank.go
- node/pkg/websocketfetcher/providers/lbank/type.go
Some websocket api requires manual ping pong from application level to keep connected. this adds related code updates for following exchanges
- lbank
- crypto.com
- bitget
- bitmart
> (OraklNode) Add missing ping pong functionality

- node/pkg/aggregator/aggregator.go
- node/pkg/fetcher/collector.go
- node/pkg/websocketfetcher/app.go
Local aggregate interval was depending on fetcher frequency of each configuration.  
sets local aggregate interval through `LOCAL_AGGREGATE_INTERVAL`, and defaults to 500ms (0.5sec)
1 sec -> 0.5 sec
1 round -> 2 round : due to short global aggregate interval, 1 round might lead to deletion of on going aggregation
> (OraklNode) Updates for subsec requirements

- node/pkg/chain/websocketchainreader/type.go
- node/pkg/chain/websocketchainreader/websocketreader.go
- node/pkg/websocketfetcher/providers/uniswap/uniswap.go
wss event subscription fails from klaytn, rollbacks to slot0 call to retrieve price from the pool
> (OraklNode) Rollback klayswap back to `slot0` call

- node/pkg/admin/utils/utils.go
- node/pkg/db/redis.go
- node/pkg/db/redis_test.go
- node/pkg/error/sentinel.go
- node/pkg/utils/retrier/retrier.go
reduce redis server round trip
- AS-IS
Whenever there is an operation, `ping` redis server to check connection and reconnect if ping fails
- TO-BE
Reconnect only when operation fails with connection error
Redis client is more generally used while redis conn is mostly used only for multi step operation
Retrial fails returns specified error that occurs execution failure
> (OraklNode) Refactor redis wrapper

- node/pkg/aggregator/streamer.go
5 -> 3 seconds default interval to store latest data if the value has not changed
> (OraklNode) Reduce default latest data update interval

- node/pkg/chain/websocketchainreader/type.go
- node/pkg/chain/websocketchainreader/websocketreader.go
- node/pkg/error/sentinel.go
- node/pkg/websocketfetcher/app.go
- node/script/test_websocketDexFetcher/main.go
- node/script/test_websocketchainreader/main.go
Use functional options pattern for initialization
return error only when both eth websocket url and kaia websocket url are not provided
> (OraklNode) refactor websocketchainreader init code

- node/pkg/reporter/app.go
- node/pkg/reporter/reporter.go
- node/pkg/reporter/types.go
Deviation job used to follow the interval of global aggregate interval, which is now 400ms. It is unnecessarily short since block generation is theoretically done every second from Kaia chain.
This update fixes deviation job interval into 2 seconds
> (OraklNode) Set fixed deviation reporter job interval

- node/pkg/websocketfetcher/app.go
Increase websocket feed data buffersize for 300% increased price pairs
> (OraklNode) Websocket feed data buffer preparation for 100+ more price pairs

- .github/workflows/deployment.yaml
This pr adds DAL as an option for dispatch deployment github action file
Main source code update can be found from following pr
https://github.com/Bisonai/orakl/pull/1720
Docker file update can be found from following pr
https://github.com/Bisonai/orakl/pull/1722
> (DAL) Add into deployment option

- node/pkg/dal/tests/api_test.go
- node/pkg/dal/utils/utils.go
Use [Keyauth](https://docs.gofiber.io/api/middleware/keyauth/) instead of manual implementation.
Adds test to check if it fails to get result without proper api key header.
> (DAL) Update dal key validation

- node/pkg/dal/tests/api_test.go
- node/pkg/dal/tests/main_test.go
- node/pkg/dal/utils/utils.go
Update filter for health check api (no auth for the healthcheck endpoint)
> (DAL) Update key validation

- node/pkg/dal/api/controller.go
Later will be improved with per api keys and more measurements
> (DAL) basic implementation to store logs

- sentinel/pkg/checker/event/app.go
- sentinel/pkg/checker/event/types.go
Current logic:
- get submission count from db in the last `1 minute`
- oversubmission_count = 1 minute / `feed.ExpectedInterval`, which used to be okay when the `ExpectedInterval` is 15 seconds. But this doesn't work when the interval is over 1 minutes
Updated to:
- get submission count from db in the last `feed.ExpectedInterval seconds`
- oversubmission_count = 2
- if submission count >= oversubmission_count send slack message
> sentinel oversubmission in checker

- .github/workflows/node.test.yaml
- node/pkg/fetcher/accumulator.go
- node/pkg/fetcher/accumulator_test.go
Current:
- create and destroy a goroutine every 250ms, which might be a cpu intensive process (goroutines are lightweight but the overhead of creating and destroying might still add up)
Updated:
- create a certain number (now 3) of goroutines, called `accumulatorWorker`, that are always active. 
- trigger an available worker through a dummy channel
> optimize fetcher accumulator cpu usage

- node/pkg/reporter/reporter.go
- node/pkg/reporter/types.go
SubmissionProxy contract has max batch size of 50, if single submission entries length exceed 50, it should be splitted.
This PR adds `splitReport` function which splits submission based on max batch size 50 
> (OraklNode) Splitted report

- node/pkg/reporter/reporter.go
- node/pkg/reporter/reporter_test.go
- node/pkg/reporter/types.go
- node/pkg/reporter/utils.go
set deviation threshold based on submission interval 
https://go.dev/play/p/0NuWyupgKRf
```golang
func main() {
// Example usage
fmt.Println(getDeviationThreshold(15 * time.Second)) // 15 seconds
fmt.Println(getDeviationThreshold(1 * time.Hour))    // 1 hour
fmt.Println(getDeviationThreshold(30 * time.Minute)) // 30 minutes
fmt.Println(getDeviationThreshold(1 * time.Second))  // 1 second (extrapolation)
fmt.Println(getDeviationThreshold(2 * time.Hour))    // 2 hours (extrapolation)
}
/*
0.05
0.01
0.030083682008368202
0.05
0.01
*/
```
> (OraklNode) Deviation Threshold based on submission interval

- node/pkg/aggregator/aggregator.go
- node/pkg/fetcher/accumulator.go
- node/pkg/raft/raft.go
- node/pkg/raft/types.go
- node/pkg/reporter/reporter.go
- node/pkg/utils/goroutine-pool/pool.go
- node/pkg/utils/pool/pool.go
- node/pkg/utils/tests/pool_test.go
- node/script/test_raft/main.go
- implement goroutine_pool package
- integrate it to `Accumulator` and `raft`'s `becomeLeader` function
> implement goroutine_pool package and integrate

- node/pkg/dal/api/controller.go
- node/pkg/dal/collector/collector.go
- node/pkg/dal/tests/api_test.go
based on local test, this updates rest api response time from
200ms -> less than 10ms
rest api
1. call redis db to get proof and global aggregate
2. post process data into outgoing data
3. return data
- collector constantly stores latest data from redis subscription
- rest api gets latest data from collector without any post processing and returns data
> (DAL) Latest outgoing data from collector

- sentinel/pkg/checker/signer/app.go
- sentinel/pkg/checker/signer/utils.go
Previously:
- get orakl signer address from node endpoint
- use hardcoded kf signer address
- send slack message if it's 5 weeks left until either of the signers expire, every 6 hours
Currently:
- get orakl and kf signer addresses and expiry dates from SubmissionProxy
- check if any of the signers have expired every 24 hours and send slack message 
Fixes #1741 
> update sentinel signer expiry check

- .github/workflows/cli.test.yaml
- .github/workflows/dal.test.yaml
- .github/workflows/delegator.test+build.yaml
- .github/workflows/node.test.yaml
- .github/workflows/sentinel.test.yaml
- contracts/v0.1/hardhat.config.cjs
- contracts/v0.2/foundry.toml
- contracts/v0.2/package.json
- core/test/caver-js.test.ts
- core/test/nonce-manager.test.ts
- core/test/reporter.test.ts
- dockerfiles/local-data-feed/envs/.core.env
- dockerfiles/local-data-feed/envs/.delegator.env
- inspector/hardhat.config.ts
- inspector/scripts/json-rpc-sync-check.sh
- node/.env.local
- node/pkg/chain/tests/chain_test.go
update deprecated public json rpc url
> update public url

- sentinel/pkg/checker/event/app.go
- sentinel/pkg/checker/event/types.go
Issue: `time` column has been treated as timestamp but turned out it's data type is numeric
Solution: convert `now()` into a numeric value (unit is seconds) as well and subtract the interval (unit is seconds)
> fix oversubmission query timestamp issue

- node/cmd/node/main.go
- node/migrations/boot/000003_add_url_constraints.down.sql
- node/migrations/boot/000003_add_url_constraints.up.sql
- node/pkg/admin/admin.go
- node/pkg/admin/host/controller.go
- node/pkg/admin/host/route.go
- node/pkg/admin/tests/host_test.go
- node/pkg/admin/tests/main_test.go
- node/pkg/admin/tests/test_helper.go
- node/pkg/boot/peer/queries.go
- node/pkg/bus/types.go
- node/pkg/libp2p/helper/app.go
- node/pkg/libp2p/setup/setup.go
- node/pkg/libp2p/tests/helper_test.go
- node/pkg/libp2p/tests/libp2p_test.go
- node/taskfiles/taskfile.local.yml
This will run alongside with other application on node start
1. Receives command through message bus with following commands
> - `GET_PEER_COUNT` : returns peer count inside orakl cluster
> - `LIBP2P_SYNC` : execute sync, reconnect to existing peers in the cluster
2. Listens to libp2p event, attempt synchronization on peer disconnect event
Sentinel will use the endpoint to track number of peers 
- `/peercount`: returns number of peers inside cluster
- `/sync`: execute sync, reconnect to existing peers in the cluster
- `get-peer-count`, `sync-libp2p`
1. Add unique constraint into peers table, preventing duplicate peer entry
2. Update peer insert query to insert only if there's no duplicate entry
3. Update `ConnectThroughBootApi` function to skip peer connection attempt if already connected …
> (OraklNode) Libp2p reconnect attempt after disconnection

- .github/workflows/boot-api.test.yaml
- node/pkg/boot/boot.go
- node/pkg/boot/peer/controller.go
- node/pkg/boot/tests/main_test.go
- node/pkg/boot/tests/peer_test.go
- node/pkg/boot/utils/utils.go
Instead of generating new libp2p host every time the check happens, use single host for repeated checks
> (BootAPI) Keep boot host alive

- node/pkg/libp2p/utils/utils.go
Refresh job is run every 10 seconds, checking if hosts in db is alive or not. previously it was kept disconnecting at the end of `IsHostAlive` call. however, it has been revealed that this is not reflected to peer count from opponent host immediately. 
Rather just keeping it connected seems to reduce unexpected updates of peer count, making number of peers easier to be tracked later through sentinel.
> (BootAPI) Remove unnecessary disconnection

- node/pkg/dal/api/controller.go
- node/pkg/dal/api/route.go
- node/pkg/dal/app.go
- node/pkg/dal/collector/collector.go
- node/pkg/dal/tests/api_test.go
- node/pkg/dal/tests/collector_test.go
- node/pkg/dal/tests/main_test.go
- node/pkg/dal/utils/initializer/initializer.go
Refactor package to remove global variables
> (DAL) Remove global variable

- sentinel/pkg/checker/event/app.go
Group feeds to check by its submission interval (ex, 15 sec, 1hr)
make submission event checks based on submission interval
if submission interval is 15sec -> check every 15sec
> (Sentinel) Group feed checks by its submission interval

- node/pkg/dal/api/controller.go
- node/pkg/dal/api/route.go
- node/pkg/dal/tests/api_test.go
- node/pkg/dal/utils/initializer/initializer.go
Related issue: https://github.com/Bisonai/orakl/issues/1777
- update `getLatestFeed` api to `getLatestMutlipleFeeds`
- takes a list of symbols as a param separated by comma
- returns an array of requested data
[Updated docs](https://www.notion.so/bisonai/DAL-API-Beta-4685cad8dad741b39b68942dea10928d?pvs=4)
> get multiple data feed by symbols

- .github/workflows/api.test.yaml
- api/main.go
- api/tests/apierr_test.go
- api/tests/chain_test.go
- api/tests/listener_test.go
- api/tests/proxy_test.go
- api/tests/reporter_test.go
- api/tests/service_test.go
- api/tests/vrf_test.go
- api/utils/utils.go
Remove redis reference which were looking at `data-feed` redis
> (API) Remove unused redis reference

- sentinel/pkg/checker/balance/app.go
- sentinel/pkg/checker/balance/app_test.go
increase delegator alarm amount to 50000
> (Sentinel) Higher Delegator balance alarm threshold for mainnet

- node/pkg/dal/api/route.go
- node/pkg/dal/app.go
- node/pkg/dal/tests/api_test.go
- node/pkg/dal/tests/collector_test.go
- node/pkg/dal/tests/main_test.go
- node/pkg/dal/utils/initializer/initializer.go
- node/pkg/dal/utils/stats/stats.go
- sentinel/pkg/checker/health/baobab_healthcheck.json
- sentinel/pkg/checker/health/cypress_healthcheck.json
simplify endpoint before official launch
- AS IS
`https://dal.baobab.orakl.network/api/v1/dal/symbols`
- TO BE
`https://dal.baobab.orakl.network/symbols`
the healthcheck endpoints should also be updated from helmchart yaml files
> (DAL) Simplify api endpoint

- node/pkg/aggregator/aggregator.go
- node/pkg/dal/tests/collector_test.go
- node/pkg/fetcher/collector.go
- node/pkg/libp2p/helper/app.go
- sentinel/pkg/checker/signer/app.go
- sentinel/pkg/checker/signer/utils.go
> downgrade some info logs to debug

- .github/workflows/sentinel.test.yaml
- sentinel/.env.example
- sentinel/cmd/main.go
- sentinel/pkg/checker/balance/app_test.go
- sentinel/pkg/checker/dal/app.go
Every 10 seconds it'll call dal api endpoint `/dal/latest-data-feeds/all` and check response data freshness
if response data freshness is over 5 seconds, it'll send alarm to slack
(Before deploying this update, the vault secret `DAL_API_KEY` should be updated)
* also removed lint & vet check from github action test for sentinel
> (Sentinel) Dal api freshness checker

- node/pkg/dal/api/controller.go
- node/pkg/dal/api/route.go
- node/pkg/dal/api/types.go
Adds two endpoints
```
api.Get("/latest-data-feeds/bulk/all", getAllLatestFeedsBulk)
api.Get("/latest-data-feeds/bulk/:symbols", getLatestFeedsBulk)
```
it'll return data in following format
```
{
"symbols": [
...
],
"values": [
...
],
"aggregateTimes": [
...
],
"proofs": [
....
],
"feedHashes": [
...
],
"decimals": [
...
]
}
```
> (DAL) Add endpoint which returns in different format

- node/pkg/reporter/app.go
- node/pkg/reporter/app_test.go
- node/pkg/reporter/reporter.go
- node/pkg/reporter/types.go
- node/pkg/reporter/utils.go
> [Separate Reporter Part 5] Implement deviation reporter

- node/pkg/aggregator/aggregator.go
implement less strict time validation rule, the only concern is if the data is older than last round
> (OraklNode) Less strict global aggregate time validation

- node/pkg/dal/api/hub.go
Send disconnection message to the client through writeControl
[reference](https://medium.com/@blackhorseya/properly-closing-websocket-connections-in-golang-a902f97716c1)
```
In the WebSocket protocol, a close message is a special control message used to indicate that the endpoint wishes to close the connection. It is an orderly and graceful shutdown process, allowing the peer to send a corresponding close message in response.
After sending a close message, the application typically continues to receive data until it receives a close message from the peer. This ensures that both sides have the opportunity to complete any pending data exchange, adhering to the normal termination process of WebSockets.
```
> (DAL) writeControl

- node/pkg/dal/api/controller.go
- node/pkg/dal/api/hub.go
- node/pkg/dal/api/types.go
- node/pkg/dal/app.go
- node/pkg/dal/tests/api_test.go
- node/pkg/dal/tests/collector_test.go
- node/pkg/dal/tests/main_test.go
- node/pkg/dal/utils/initializer/initializer.go
- previous api controller renamed to hub
- hub / controller separated into different files
- separate collector from hub
- add collector into fiber locals
> (DAL) Refactor package structure

- node/pkg/reporter/app_test.go
Testing missing env variables is meaningless since those vairables are provided from helm charts not from this repo. This will fix failing reporter tests issue
> remove unnecessary tests

- node/pkg/aggregator/aggregator_test.go
- node/pkg/aggregator/streamer.go
- node/pkg/aggregator/streamer_test.go
- node/pkg/aggregator/utils.go
Aggregator Streamer used to store latest global aggregate and proof into rdb, this pr removes the feature now since the data is referenced from DAL through redis pubsub
> (OraklNode) Remove unnecessary code

- node/pkg/dal/collector/collector.go
> update redis delay log

- node/pkg/chain/helper/helper.go
The nonce is incremented only when the transaction is picked up by a miner, included in a block, and the block is successfully added to the blockchain. if the function fails before tx being mined, the nonce shouldn't be increased
This pr update nonce increase condition accordingly
please refer to following code for error `errorSentinel.ErrChainTransactionFail` 
https://github.com/Bisonai/orakl/blob/85b145c908e355a337d66c0f1e2a1e95e99dc9b2/node/pkg/chain/utils/utils.go#L348-L375
> (OraklNode) Add condition to increase nonce

- node/pkg/aggregator/types.go
- node/pkg/aggregator/utils.go
- node/pkg/dal/collector/collector.go
- node/pkg/reporter/reporter.go
related delays will be caught from sentinel
> (Chore) cleanup debug logs added to solve reporter issue

- node/pkg/aggregator/aggregator.go
- node/pkg/aggregator/utils.go
- node/pkg/dal/api/hub.go
> (Chore) fix linter errs

- node/pkg/dal/api/client.go
- node/pkg/dal/api/controller.go
- node/pkg/dal/api/hub.go
- node/pkg/dal/api/types.go
- node/pkg/dal/tests/stats_test.go
- node/pkg/dal/utils/stats/stats.go
- Syncmap instead of map + mutex
- Implement threadsafe websocket client for better `WriteJson` performance
> (DAL) syncmap implementation

- node/pkg/aggregator/types.go
- node/pkg/aggregator/utils.go
- node/pkg/dal/collector/collector.go
> add data delay logs to node and dal

- node/pkg/aggregator/types.go
- node/pkg/aggregator/utils.go
- node/pkg/dal/collector/collector.go
> rollback node and dal data delay logs

- node/pkg/chain/utils/utils.go
- node/pkg/dal/collector/utils.go
Potential fix for invalid signer error
> (DAL) Update proof related codes

- node/pkg/aggregator/aggregator.go
- node/pkg/aggregator/types.go
- reduce aggregation steps
- reduce mutex locks
> (OraklNode) Optimize aggregator

- node/pkg/dal/api/controller.go
- node/pkg/dal/api/hub.go
- node/pkg/dal/api/types.go
- `h.clients` access is not thread safe, this update covers full mutex lock for single subscribe command
- also uses Mutex instead of RWMutex
> (DAL) Prevent deadlock from multiple lock and unlock from single func

- node/pkg/dal/api/client.go
- node/pkg/dal/api/hub.go
- node/pkg/dal/api/types.go
- Rollback RWMutex
- Reduce mutex lock contention from `castSubmission` func
> (DAL) Minor improvement

- node/pkg/raft/raft.go
- node/pkg/raft/raft_test.go
- Separate raft test codes into multiple scenarios
- Rollback recover from leaderjob panic
> (OraklNode) partition `raft` test codes, rollback recover

- node/pkg/dal/api/hub.go
- node/pkg/dal/api/types.go
- node/pkg/dal/collector/collector.go
- node/pkg/dal/tests/api_test.go
- node/pkg/dal/tests/collector_test.go
Pass data by reference from the channel
> (DAL) Chore, minor dal optimization

- node/pkg/aggregator/aggregator.go
- node/pkg/aggregator/types.go
- node/pkg/utils/calculator/calculator.go
- store senders per round for price & proof, validate if it has been already sent
- lock round price aggregation or proof generation once it has been executed
- trigger round logic only when prices or proofs equals length of cluster nodes. (previously it was equal or greater than)
- rollback cleanup logic to remove data 20 rounds ago on new round start (approximately 8 secs ago)
- add 'if' statements to bypass sorting from median calculation if length of parameter is lower than 2
> (OraklNode) Prevent duplicate raft message from aggregator

- node/pkg/dal/collector/collector.go
reload whitelist in separate thread to prevent delayed response
> (DAL) Renew signer from separate thread

- node/pkg/aggregator/aggregator.go
- node/pkg/aggregator/types.go
- node/pkg/dal/api/hub.go
- node/pkg/raft/raft.go
instead of removing only specified round data, remove all except the last 10 data
> (OraklNode) fix memory leak & lint error

- node/pkg/libp2p/setup/type.go
Set golibp2p pubsub option for message cache ttl
> (OraklNode) Reduce default 120 sec -> 10 sec for msg ttl

- node/pkg/aggregator/app.go
- node/pkg/aggregator/main_test.go
- node/pkg/aggregator/types.go
- node/pkg/common/types/types.go
- node/pkg/dal/api/hub.go
- node/pkg/dal/api/types.go
- node/pkg/dal/app.go
- node/pkg/dal/collector/collector.go
- node/pkg/dal/tests/main_test.go
- node/pkg/fetcher/collector.go
- node/pkg/fetcher/types.go
- node/pkg/reporter/types.go
- node/pkg/websocketfetcher/common/type.go
- node/script/test_dal_consumer_ws/main.go
Fix wrong type alias declaration and add missing alias references
```
type LocalAggregate types.LocalAggregate
```
```
type LocalAggregate = types.LocalAggregate
```
> (OraklNode) chore, fix alias declaration

- node/pkg/aggregator/aggregator_test.go
- node/pkg/aggregator/app.go
- node/pkg/aggregator/main_test.go
- node/pkg/aggregator/types.go
- node/pkg/aggregator/utils.go
- node/pkg/fetcher/accumulator_test.go
- node/pkg/fetcher/app.go
- node/pkg/fetcher/collector.go
- node/pkg/fetcher/types.go
Update structure type properties into pointer type
> (OraklNode) Chore, send local aggregate through pointer

- node/pkg/websocketfetcher/common/type.go
- node/pkg/websocketfetcher/providers/bitstamp/utils.go
- node/pkg/websocketfetcher/providers/btse/utils.go
- node/pkg/websocketfetcher/providers/gemini/utils.go
prevent context deadline exceeded error on caching trading volume
```bash
│ 5:10AM ERR error in FetchVolumes error="Get \"https://www.bitstamp.net/api/v2/ticker/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" Player=Bitstamp
│ 5:10AM ERR error in fetchVolumes error="Get \"https://www.bitstamp.net/api/v2/ticker/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" Player=Bitstamp
```
> (OraklNode) Increase volume fetch interval for certain ws

- node/pkg/checker/dal/app.go
- node/pkg/checker/dal/types.go
if request count for last 10 seconds exceeds 100, sends slack message
> (Sentinel) DAL request traffic checker

- node/pkg/common/keys/keys.go
- node/pkg/common/types/types.go
- node/pkg/fetcher/app.go
- node/pkg/fetcher/app_test.go
- node/pkg/fetcher/feeddatabulkwriter.go
- node/pkg/fetcher/fetcher.go
- node/pkg/fetcher/fetcher_test.go
- node/pkg/fetcher/localaggregatebulkwriter_test.go
- node/pkg/fetcher/localaggregator.go
- node/pkg/fetcher/main_test.go
- node/pkg/fetcher/types.go
- node/pkg/fetcher/utils.go
- node/pkg/fetcher/utils_test.go
- node/pkg/websocketfetcher/app.go
- node/pkg/websocketfetcher/common/utils.go
- node/pkg/websocketfetcher/tests/utils_test.go
- Use in memory RWMap to store and load latest feed data instead of redis
- Use in memory channel to store pgsql dump feed data instead of redis
> (OraklNode) Replace redis into in memory data types

- node/pkg/dal/api/controller.go
- node/pkg/dal/api/hub.go
- node/pkg/dal/api/types.go
Cleanup job will remove invalid entries and reassign every 1 hour
reference: https://github.com/golang/go/issues/20135
> (DAL) Potential fix for dal memory leak

- node/pkg/dal/collector/collector.go
Update validate logic to prevent duplicate broadcasts
> (DAL) Update logic to prevent duplicate broadcasts

- node/cmd/sentinel/main.go
- node/pkg/checker/offset/app.go
Checks local aggregate & global aggregate offset every 5 min. if the value is over 5 seconds, it'll send an alert
> (Sentinel) Offset checkers

- node/pkg/aggregator/aggregator.go
- node/pkg/raft/raft.go
- node/pkg/raft/raft_test.go
- node/script/test_dal_consumer_ws/main.go
This PR aims to fix possible unsync scenarios
- both nodes might handle each other's heartbeat messages and then step down as followers at the same time, and then restart election timers and go through same process again, without either one becoming a stable leader
- two nodes receive each other's votes and become candidates at the same time. each node grant vote to each other but neither will have enough votes to become a leader
To prevent this scenario this PR updates followings
- Modify the handleHeartbeat function to only step down if the received heartbeat’s term is strictly greater than the current term (i.e., > instead of >=). This will prevent nodes from stepping down when they receive a heartbeat with the same term, which should help avoid a "tie" scenario where both nodes become …
> (OraklNode) Update raft implementation

- node/pkg/dal/apiv2/controller.go
- node/pkg/dal/apiv2/types.go
- node/pkg/dal/app.go
- node/pkg/dal/tests/main_test.go
- node/pkg/dal/utils/stats/stats.go
User statistics for rest calls weren't being collected after migration of framework from fiber to go/http
This adds functionality to collect user rest call stats alongside with bulk insertion every certain interval (previously inserted each entries)
> (DAL) Bulk insert user stats

- node/cmd/sentinel/main.go
- node/pkg/checker/offset/app.go
- update previous delay check query so that it doesn't give too much stress to the db
- add check to compare difference between global aggregate value and local aggregate value, if the difference if over 10% it'll send alert
> (Sentinel) Update offset checker

- node/pkg/wss/types.go
- node/pkg/wss/utils.go
- node/pkg/wss/utils_test.go
It'll now reconnect on following 2 conditions
- if it has been running for more than `reconnectInterval` (default 12hr)
- if there were no incoming messages over `inactivityTimeout` (default 15min)
> (OraklNode) WebsocketHelper improve auto reconnect

- node/cmd/sentinel/main.go
> (Sentinel) Rollback dal checkers

- node/cmd/fetcher/main.go
- node/cmd/node/main.go
- node/pkg/admin/admin.go
- node/pkg/admin/tests/config_test.go
- node/pkg/api/utils/utils.go
- node/pkg/boot/boot.go
- node/pkg/boot/utils/utils.go
- node/pkg/checker/balance/app.go
- node/pkg/checker/balance/app_test.go
- node/pkg/checker/balance/types.go
- node/pkg/checker/event/app.go
- node/pkg/checker/event/types.go
- node/pkg/checker/peers/app.go
- node/pkg/dal/apiv2/controller.go
- node/pkg/por/app.go
didn't include environment variables updates which contains `orakl` since it requires helm chart value or vault secret updates
> (Rebranding) refactor internal variables and strings in `node`

- node/pkg/wss/utils.go
previously, wasn't setting timer properly, not having difference from using ticker, through this update, it'll reset timer relatively based on last update time
> (OraklNode) Update timer relative to last update time

- node/pkg/db/pgsql.go
- node/pkg/db/pgsql_test.go
> fix: rollback db timeout

- node/pkg/fetcher/utils.go
`FetchSingle()` is a function referenced only from POR
Instead of using 2 seconds default timeout, pass 10 seconds timeout so that it can be more tolerant to slow responses
> (POR) Increase timeout for por request

- node/pkg/checker/dalstats/app.go
errorlog
```
Error getting keys {"error": "struct doesn't have corresponding row field key"}
Error running DAL DB stats {"error": "struct doesn't have corresponding row field key"}
```
I don't understand why this error has happened, perhaps it could be because `key` is some kind of preserved name?
please share any suggestion for this fix
> (Sentinel) DAL Stats not running as expected, implement possible fix

- node/pkg/checker/dal/app.go
- node/pkg/checker/dal/types.go
instead of using default 2 seconds timeout, use 10 seconds from sentinel dal checks
> (Sentinel) Increase timeout for DAL rest calls

- node/cmd/node/main.go
In local, the ping connection has been working at the very launch of the application, however from production, it seems to require some time until pinging public DNS works as expected,
I'm assuming it will start working after it connects to boot api, which it is also retried multiple times before app launch until the network is ready
> (OraklNode) run ICMP checker after boot api connected

- node/pkg/websocketfetcher/app.go
use proxy from websocket fetchers.
> (OraklNode) Implement proxy for websocket fetchers

- node/pkg/checker/ping/app.go
Count option should not be specified to make it run indefinitely
https://pkg.go.dev/github.com/prometheus-community/pro-bing@v0.4.1#Pinger.Count
> (OraklNode) Remove pinger count option

- node/.env.example
- node/README.md
- node/pkg/checker/ping/app.go
Currently `privileged` setting for pinger isn't compatible in local environment, which runs without build and from mac. add option so that it can be customized in local
> (OraklNode) Add env for local run

- node/pkg/aggregator/aggregator.go
- node/pkg/aggregator/aggregator_test.go
- node/pkg/aggregator/app.go
- node/pkg/aggregator/globalaggregatebulkwriter.go
- node/pkg/aggregator/globalaggregatebulkwriter_test.go
- node/pkg/aggregator/utils.go
- node/pkg/common/keys/keys.go
- node/pkg/dal/collector/collector.go
- node/pkg/dal/hub/hub.go
- node/pkg/dal/tests/api_test.go
- node/pkg/dal/tests/collector_test.go
- node/pkg/dal/tests/main_test.go
- node/pkg/reporter/app_test.go
It has been revealed that even though `DAL` was subscribing to multiple nodes, there were data delay when deploying bisonai node. After investigating this issue, it has been found that there were wrong implementation regarding redis pubsub
Publish & Subscription redis key was based on config id
Publish & Subscription base on symbol name
Config id is not a consistent value among different nodes
Through this update it will properly utilize data from multiple nodes from DAL
> (OraklNode) Update redis publish key and related codes

- node/pkg/aggregator/app.go
- Remove time.sleep and jitter codes on starting aggregators
-> now it waits for localAggregates data to be ready which aren't produced at the same time
-> and even if it starts at same time, it has no external calls so aggregators shouldn't matter
- Add log to count started global aggregator
> (OraklNode) Update aggregator start func

- node/pkg/checker/inspect/app.go
random sleep on start so that 2 inspectors in idc(BAOBAB, CYPRESS) doesn't make 2 http requests at the same time
> (OraklNode) Jitter on inspector start

- node/pkg/chain/eth_client/eth_client.go
- node/pkg/chain/utils/types.go
- node/pkg/chain/websocketchainreader/websocketreader.go
reference: https://community.infura.io/t/websocket-close-1006-abnormal-closure-unexpected-eof/5210/7
- Updates websocket json rpc fetcher to also subscribe to latest block so that it doesn't get disconnected due to long idle connection
- Reduce log level which ended up in multiple 
`[Websocket: close 1006 (abnormal closure): unexpected EOF](https://community.infura.io/t/websocket-close-1006-abnormal-closure-unexpected-eof/5210)`, since it auto reconnects to the wss json rpc url, it should be okay with `Warn` level
> (OraklNode) Subscribe to new header to avoid unexpected disconnection

- node/pkg/checker/dal/app.go
- node/pkg/checker/dal/app_test.go
- node/pkg/checker/dal/types.go
- node/pkg/checker/event/app.go
- node/pkg/checker/offset/app.go
Alarm per pair will be sent with 10 times of offset,
for less occurrences, it'll send cnt message for previous offset 
> (Sentinel) reduce spamming from dal checks, offsetchecks, and event checks

- node/pkg/chain/websocketchainreader/websocketreader.go
block channel kept being increased without being consumed leading to memory leak.
this pr fixes the issue
> (OraklNode) consume channel to fix memory leak

- contracts/v0.2/package.json
- contracts/v0.2/test/SubmitStrict.t.sol
This PR includes a test that allows for long-term testing of a single feed through [`submitStrict`](https://github.com/Bisonai/orakl/blob/a91e164e724e37653a33544930e5efa2dec8f983/contracts/v0.2/src/SubmissionProxy.sol#L399-L416) method. The contract call is executed in forked environment for each new submission.
The test is composed of three steps:
1. Cleanup of previous generated file `submission.json`.
2. Fetch the latest submission data from DAL to `submission.json`.
3. Simulation of submission execution to Orakl Network, and reading the latest submitted round followed by comparison of the block timestamp of the latest submission as shown below.
```
require(block.timestamp == blockTimestamp, "Timestamps do not match");
```
* forge
* yarn
Execute from `contracts/v0.2` directory.
The …
> Test for `submitStrict` method

- node/pkg/admin/fetcher/controller.go
- node/pkg/admin/fetcher/router.go
- node/pkg/admin/tests/fetcher_test.go
- node/pkg/fetcher/app.go
- node/pkg/websocketfetcher/app.go
- Remove admin endpoint
> - activate/deactivate: fetcher start/stop based on config id isn't compatible anymore for websocket fetcher
- Remove fetcher bus message command
> - `ACTIVATE_FETCHER` & `DEACTIVATE_FETCHER`: command no more compatible to run based on configID
- Add WebsocketFetcher `Stop` func: include websocketFetcher Stop in fetcher app StopAll func
> (OraklNode) Update restartFetcher

- node/pkg/checker/dal/app.go
add missing alarm msg with number of delayed websocket counts
> (Sentinel) Add missing msg for delayed websocket counts

- node/pkg/checker/event/app.go
Checks weren't incremented when condition has met, this pr fixes the issue
> (Sentinel) Add missing check increment

- node/pkg/dal/hub/hub.go
- node/pkg/utils/pool/pool.go
Goroutine pooling on broadcasting data
> (DAL) Pooling broadcast

- node/pkg/dal/hub/hub.go
- node/pkg/utils/pool/pool.go
This reverts commit 12378aea7e2c2eefe1165131385e0669298300e2.
> Revert "(DAL) Pooling broadcast (#2246)"

- node/pkg/chain/helper/helper.go
- node/pkg/checker/inspect/app.go
> (Sentinel) Remove nonce manager dependency from inspector

- node/pkg/por/app.go
POR doesn't make concurrent submission, removing manual nonce management will make it safer
> (POR) Remove manual nonce management dependency

- node/pkg/checker/ping/app.go
Instead of simply comparing RTT with absolute delay, 
Use average delay and check sudden increase of delay
> (Node) Remove max delay logic, instead use alpha with avg

- node/pkg/aggregator/types.go
- node/pkg/aggregator/utils.go
- node/pkg/dal/apiv2/controller.go
- node/pkg/dal/app.go
- node/pkg/dal/collector/collector.go
- node/pkg/dal/hub/hub.go
- node/pkg/dal/tests/collector_test.go
- node/pkg/dal/tests/main_test.go
- node/pkg/error/sentinel.go
- node/pkg/reporter/app_test.go
- node/pkg/reporter/main_test.go
- remove config id reference from dal
- remove node admin api dependency from dal
> (DAL) Remove config id reference

- node/pkg/aggregator/aggregator.go
- Add more logs to understand cluster status
- Rollback round update logic execution order
> (Node) Add more logs

- node/pkg/aggregator/aggregator.go
- Refactoring: encapsulate certain part of the code for readability
- Set minimal timeout in `HandlePriceDataMessage `, `HandleProofMessage `  so that it doesn't hang forever on delayed price or proof message
> (Node) Timeout for aggregator msg handling

- node/pkg/aggregator/aggregator.go
- increase timeout 100ms -> 150ms
- update logic so that timeout logic is executed on first message regardless of current number of subscribers 
> (Node) Increase timeout

- .github/workflows/node.test.yaml
- contracts/v0.1/hardhat.config.cjs
- core/test/nonce-manager.test.ts
- core/test/reporter.test.ts
- inspector/hardhat.config.ts
- inspector/scripts/json-rpc-sync-check.sh
- node/pkg/checker/ping/app.go
> (Node) Reduce ping error loggings

- node/pkg/chain/helper/helper.go
- node/pkg/chain/noncemanager/noncemanager.go
reset nonce from block in case of nonce error
> (Reporter) Update nonce error handling

- node/pkg/aggregator/aggregator.go
- node/pkg/raft/raft.go
- node/pkg/raft/types.go
> (Node) update logs, update logic order

- node/pkg/websocketfetcher/app.go
- node/pkg/websocketfetcher/common/type.go
- node/pkg/wss/utils.go
utilize ws proxy to reduce network pressure
> ws proxy support

- contracts/v0.2/src/SubmissionProxy.sol
- contracts/v0.2/test/SubmitStrict.t.sol
Review for https://github.com/Bisonai/orakl/pull/2314
> Review of superseded feature

- node/pkg/checker/dal/app.go
- node/pkg/checker/dal/app_test.go
- node/pkg/checker/dal/types.go
Remove buggy check, leave only push offset checker
> [Sentinel] Remove ws delay checker

- node/pkg/checker/dal/app.go
- node/pkg/checker/dal/types.go
checks network delay of dal
returns error if delayed more than certain threshold
> (Sentinel) DAL rest network delay checker

- node/pkg/chain/helper/signer.go
Leave log on initial signer renewal failure
> (Chore) Add log

- .github/workflows/dal.test.yaml
- .github/workflows/reporter.test.yaml
- node/pkg/chain/helper/helper.go
- node/pkg/chain/helper/signer.go
- node/pkg/chain/helper/types.go
- node/pkg/chain/noncemanagerv2/noncemanagerv2.go
- node/pkg/chain/tests/chain_test.go
- node/pkg/checker/inspect/app.go
- node/pkg/por/app.go
- node/pkg/reporter/app.go
- node/pkg/reporter/reporter.go
- node/script/test_dal_consumer/main.go
- node/script/test_submission/main.go
Remove additional json rpc usage from the logic
use nonce pool with pool reset on regular interval
> [ChainHelper] reduce complexity, pool based noncemanager

- node/pkg/websocketfetcher/providers/coinex/coinex.go
- node/pkg/websocketfetcher/providers/coinex/type.go
- node/pkg/websocketfetcher/providers/coinex/utils.go
- node/pkg/websocketfetcher/tests/utils_test.go
> Migrate to coinex v2

- node/pkg/websocketfetcher/providers/bingx/bingx.go
- node/pkg/websocketfetcher/providers/coinex/coinex.go
- node/pkg/wss/utils.go
Reduce log level that has been spamming `logscribe`.
these are wrapped in retrial logic and should be okay with lowered log level
> (Node) Reduce logs

- node/pkg/websocketfetcher/providers/orangex/orangex.go
Orangex data format changed, updating based on actual return values
> (Node) Fix orangex formatting

- node/pkg/checker/dal/app.go
- node/pkg/checker/delisted.go
- node/pkg/checker/event/app.go
Remove alert for the symbol to be delisted
> [Health] Reduce alert spamming

- node/pkg/wss/utils.go
> skip empty message

- node/pkg/dal/apiv2/controller.go
> (DAL) Unstrict endpoint for reporter

- node/pkg/websocketfetcher/providers/xt/utils.go
- node/pkg/websocketfetcher/providers/xt/xt.go
> Reduce log spamming

- node/pkg/fetcher/utils.go
- node/pkg/por/app.go
- node/pkg/por/types.go
> [por] minor updates for m7 integration
